### ISSUE TITLE
RasterRDD TMS Viewer

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1119]
It would be very helpful to be able to view a `RasterRDD` through a TMS service directly, perhaps launching it from a spark shell. While a single RDD could only present a single zoom level we should be able to perform pyramid up and down operations on the fly.

This functionality could be re-used to display a `RasterRDD` in spark notebook.

**Comment by lossyrob** [comment]
I believe that we will end up implementing this as part of the upcoming jupyter notebook integration.

**Comment by echeipesh** [comment]
It is so: https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/tms.py

Currently there is no component in GeoTrellis sub-projects that would really benefit from gaining an `akka-http` dependency. Likely some underlying features like multi-value RDD lookup will make it into `geotrellis-spark`, but we don't need this issue to track that work.
