### ISSUE TITLE
Feature request: hierarchical precomputation

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech/geotrellis#1183]
For some applications, like computing histograms of large rasters clipped against polygons, it would be helpful to not have to recompute histograms for portions of the raster contained entirely within the polygon.

For example, if there is a raster that is broken up into tiles and those tiles are indexed by a [k-d tree](https://en.wikipedia.org/wiki/K-d_tree) or similar, at each node in the tree, it is possible to store the histogram for the entire area covered by that node.

In the case of an implicit tree (like with a space filling curve), prefixes of addresses can be treated as subtrees would be in the case described above.

If the polygon is of bounded aspect-ratio and contains _n_ tiles, this should allow the histogram to be approximately computed by retrieving only about _log(n)_ pieces of information (because you would only expect to need about that many [internal] nodes to almost cover the interior of the polygon).  

Exact answers would probably require in the neighborhood of _sqrt(n)_ downloads because the boundary of the polygon would be expected to cross about that many tiles (and tiles which are partially inside and partially outside of the  polygon must be completely downloaded).

Motivated by https://github.com/WikiWatershed/mmw-geoprocessing/issues/5

**Comment by lliss** [comment]
+1 This would indeed be a helpful feature.

**Comment by kdeloach** [comment]
+1!

**Comment by jamesmcclain** [comment]
Perhaps we should consider closing this.

**Comment by lliss** [comment]
I think that is fair.

**Comment by jamesmcclain** [comment]
!

**Comment by jamesmcclain** [comment]
This seems to have been superseded by some other research project.

**Comment by kdeloach** [comment]
👍

**Comment by lossyrob** [comment]
@jamesmcclain that research actually doesn't quite apply to this issue. It's fine to close it, but if at some point you would want to take the task on of trying this idea out, we might want to leave it open.

**Comment by jamesmcclain** [comment]
Many distinguished former Azavea employees in this thread.

**Comment by jamesmcclain** [comment]
@lossyrob I will probably be able to find other things to work on.
