### ISSUE TITLE
Parquet backend support

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#1254]
This is an issue to keep track of the now-defunct PR https://github.com/geotrellis/geotrellis/pull/1118

**Comment by echeipesh** [comment]
I think its clear now that any parquet writing is going to require DataFrame/DataSet support where we decompose our types into specific fields a-la: https://github.com/locationtech/geotrellis/issues/2051

There is a subtext in these efforts of also doing spatial queries on parquet file, but that does not seems as relevant right now. Closing this issue for now.
