### ISSUE TITLE
`geotrellis-gdal` Feature Advancements

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1396]
The https://github.com/geotrellis/geotrellis-gdal project needs to be expanded in order to integrate more fully with GeoTrellis data types and expose more of GDAL capabilities.

Particularly interesting is tho option of providing an API that is convenient to use from the Scala REPL allowing users to perform map algebra operations interactively. Ability to do is always a mark of a well designed API.

It is possible that in the process of pushing this feature forward we may find that GeoTrellis data types need to extended or expanded to better represent the types covered by GDAL. This is a good thing.

**Comment by lossyrob** [comment]
@echeipesh Should this be an issue on the geotrellis-gdal repo?

**Comment by echeipesh** [comment]
Closing this because the issue here. `geotrellis-gdal` could use API work but we don't really have a an acute need for it right now so its hard to say what the direction should be.
