### ISSUE TITLE
Proj4J extraction and submission to LocationTech

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1397]
Currently GeoTrellis hosts a version of Proj4J in our repository (https://github.com/geotrellis/geotrellis/tree/master/proj4/src/main/java/org/osgeo/proj4j) to allow for tighter integration in our work of developing distributed geospatial library on spark. In our work we have made improvements to Proj4J project that we wish to contribute back to the community. 

The Proj4J java project needs to be extracted into its own project, undergo further testing and development, and submitted to LocationTech working group where it will be maintained in the future.

**Comment by lossyrob** [comment]
A good start is #1481

**Comment by lossyrob** [comment]
This has been submitted to locationtech, so the work here is to depend on the community version once there is a release.
