### ISSUE TITLE
Vector Tile Stitching/Pyramiding

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1400]
Vector tiles compactly encode geometries into tiles that have a defined resolution. This encoding makes them an optimized representation for geometries that need to be rendered on a web map but is more flexible than fully rendered images. Additionally they are conceptually interesting because they bridge the gap between infinitely precise geometries, which are difficult to work with in distributed environment, and rasters which are easily distributed but have defined resolution.

GeoTrellis is adding support for vector tiles in Scala both as a presentation and a computation datatype. This work is in early stages and requires active contributions. Of particular interest is the process of pyramiding vector tiles which will join the geometries of neighboring tiles, stitching them together, and simplify them to match the resolution of the target tile. This project is to push further both the implementation and API with ultimate goal of using vector tiles to implement vector raster computations on Spark.

**Comment by kamicut** [comment]
@echeipesh [Awesome vector tiles](https://github.com/mapbox/awesome-vector-tiles) has  https://github.com/ElectronicChartCentre/java-vector-tile listed as a java vector tile encoder/decoder. It could be a starting point for encoding.

**Comment by lossyrob** [comment]
This work is happening in https://github.com/geotrellis/vectorpipe. See https://github.com/geotrellis/vectorpipe/issues/14
