### ISSUE TITLE
JVM Native NetCDF Reader

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1402]
[NetCDF](https://en.wikipedia.org/wiki/NetCDF) is a data encoding format commonly used to encode multi-dimensional scientific data. In particular we encountered this format when working on geospatial analysis of climate change models produced by the IPCC reports. While we have used GDAL to read these files it is very desirable to be able to read these formats natively in Scala. This project will need to provide a reader capable of reading both version 3.0 and 4.0 of NetCDF format. NetCDF Version 4.0 uses [HDF5](https://en.wikipedia.org/wiki/Hierarchical_Data_Format) which adds complexity. It is possible that some components from [DawnScience/scisoft-core](https://github.com/DawnScience/scisoft-core) may be extract and re-used to read the HDF5 format.
https://github.com/DawnScience/scisoft-core/blob/master/uk.ac.diamond.scisoft.analysis/src/uk/ac/diamond/scisoft/analysis/io/LoaderFactory.java#L140

While the ability to read this formats is important for GeoTrellis these features are clearly defined and possibly have wider audience. A stretch goal of this project should be to produce and publish a library capable of reading and writing these formats. Because these files often get large and are hosted over HTTP an additional goal can be to provide a streaming reader capable of reading only the header and skipping foward to read only the relevant portions of the file.

**Comment by echeipesh** [comment]
I would be tempted to suggest using [scodec](https://github.com/scodec/scodec) for these tasks. There appears to be some streaming support and previous experiments with the library showed that is produced encoders/decoders of acceptable performance.

Likely if taking this route a benchmarking task would be desirable after the first viable encoder. Version 3.0 of the format is not very complicated so an ideal scenario would be to have a head-to-head shootout between: C decode, Java native decoder: https://github.com/Unidata/thredds, Scodec decoder.

**Comment by pomadchin** [comment]
From gitter channel (thx to @bjvanlinschoten), there is pointer for hdf5 / netcdf4: https://github.com/valiantljk/h5spark

**Comment by echeipesh** [comment]
https://github.com/geotrellis/geotrellis-netcdf
