### ISSUE TITLE
Python library to read GeoTrellis Avro records as Rasterio tiles

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#1403]
GeoTrellis uses [Apache Avro](https://avro.apache.org) serialization when storing its tiled map layers. While GeoTrellis is a Scala project Avro provides libraries for multiple languages, including python. This project is to implement a python library that will read and write persisted GeoTrellis layers and present them as [NumPy](http://www.numpy.org) datatypes that can be used by [rasterio](https://github.com/mapbox/rasterio). Once the basic translation is supported the next step would be to read GeoTrellis layer in a distributed Python Spark job and use rasterio to perform geospatial computations.

Interoperability between GeoTrellis and rasterio will allow for complex, multi-stage geospatial workflows that do not suffer the usual performance penalties when working mixed Spark Scala/Python environment, expanding the utility of both libraries.

**Comment by timothymschier** [comment]
+1

**Comment by lossyrob** [comment]
Code notes from meeting with @shiraeeshi 

```python
# Code notes from meeting

rdd = GeoTrellis.rddFromS3(..)

rdd.map(lambda (key, tile): tile

tile <- rasterio Raster




Decision:
- Should we try to use py4j like Spark is?
* Should we be loading/saving RDD's of rasterio rasters, or of geotrellis.raster tiles?



LayerReader():
  _layerReader = jvm.AccumuloLayerReader.spaceTimeMultibandTile

  def read(name, zoom):
    geoTrellisRdd = _layerReader.read(jvm.LayerId.apply(name, zoom))
    geoTrellisRdd.mapValues { lambda geoTiffBytes: rasterio.read(geoTiffBytes) }
    





package goetrellis.api.python

object AccumuloLayerReader {
    def spaceTimeMultiBandTile(instanceName: String, ..) =
      AccumuloLayerReader(...).reader[SpaceTimeKey, MultibandTile, TileLayerMetadata[SpaceTimeKey]]()
}

f: RDD[(SpaceTimeKey, MultibandTile)] => RDD[(SpaceTimeKey, GeoTiff)] =>  RDD[(SpaceTimeKey, Array[Byte])]
```

**Comment by lossyrob** [comment]
This work is happening in https://github.com/locationtech-labs/geopyspark
