### ISSUE TITLE
GeoTrellis and Leaflet use different z/x/y indexing for 512x512 tiles

### ISSUE THREAD

**Issue by RickMohr** [locationtech/geotrellis#1550]
Using `L.TileLayer(url, {tileSize: 512})`, Leaflet requests the 512x512 tile below as 11/297/388.
GeoTrellis indexes this tile as 10/297/388.

Who is right?

Note that using `L.TileLayer(url)` (default tile size of 256), Leaflet requests this tile as 10/297/388. It appears that during ingest GeoTrellis does not take the tile size into account when determining the index. Should it?

![tile](https://cloud.githubusercontent.com/assets/2162993/16082419/5048fb94-32df-11e6-8e8d-802ced598a85.png)

**Comment by RickMohr** [comment]
The difference is easy to accomodate. Just wanted to bring it to your attention.

**Comment by RickMohr** [comment]
In the example above, custom Scala code was handling Leaflet's tile request and could tweak the requested zoom to fetch it successfully via GeoTrellis.

But here's an example where 512x512 tiles are being fetched directly from S3 so there's no opportunity for adjusting the zoom. (Put the code below in a file, run `python -m SimpleHTTPServer` from that folder, and hit http://localhost:8000)

The tiles don't load when `tileSize: 512` is specified, but do load with the default of `tileSize: 256`.

For example, with `tileSize: 512` Leaflet requests this tile as https://c.tiles.azavea.com/treecanopy-2006-2008-pa/11/284/385.png but GeoTrellis has indexed it as `10/284/385`.

The tiles are on S3, `azavea-datahub` user, as `tiles.us-east-1.azavea.com/treecanopy-2006-2008-pa`. They were ingested using https://github.com/lossyrob/treecanopy-ingest

![image](https://cloud.githubusercontent.com/assets/2162993/16307138/2f35801c-392e-11e6-9a3c-74b1febdbc10.png)

```html
<!DOCTYPE html>
<html>
<head>
    <title>Tile Example</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
</head>
<body>
    <div id="mapid" style="width: 800px; height: 800px"></div>
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
    <script>
        var mymap = L.map('mapid').setView([40.4313, -79.9806], 11);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.streets'
        }).addTo(mymap);
        L.tileLayer('http://c.tiles.azavea.com/treecanopy-2006-2008-pa/{z}/{x}/{y}.png', {
            maxZoom: 17,
            tileSize: 512
        }).addTo(mymap);
    </script>
</body>
</html>
```

**Comment by pomadchin** [comment]
I think it is discussed [there](https://github.com/Leaflet/Leaflet/issues/4391) and looks really like a leaflet _feature_ and the issue for 512x512 tiles can be fixed by using `zoomOffset: -1`

**Comment by RickMohr** [comment]
Thanks -- I'll try it.

**Comment by lossyrob** [comment]
Closing. Please reopen if this is still an issue.
