### ISSUE TITLE
Additional documentation for quickstart guide

### ISSUE THREAD

**Issue by jpolchlo** [locationtech/geotrellis#1604]
On the recommendation of a user, some common use cases should be documented to help new users come up to speed faster.  Some suggestions for coverage are as follows:

 [x]  1. Open `spark-shell` with spark-etl functions available.
2. Handle spatio-temporal data.  (create new issue) 
3. Read a GeoTIFF from a local file or HDFS, tile it, and store to HDFS or Accumulo; perform an operation on the stored tiles and store these results back to the database. ( split to new issue )
4. Related to 3: create a catalog in Accumulo, ingest data into it, and expose the catalog for use in a web application.   (split to new issue? table for now? maybe not a 1.0 release mile stone. ) (how to accumulo. how to docker....how to geodocker.... ? should geodocker have its own documentation? ....its own separate doc...)

These basic suggestions will go a long way toward more rapid onboarding of new users.  Additional suggestions that go above and beyond these basic four involved setting up a project with web service capabilities, including the ability to dynamically add layers that are visible to web applications without restarting a web server, though this level of detail most likely exceeds the scope of a quickstart guide.

**Comment by fosskers** [comment]
This seems essentially taken care of, minus Accumulo stuff. Good to close?

**Comment by jpolchlo** [comment]
Yeah, that seems right to me.

**Comment by fosskers** [comment]
This should be closable, @lossyrob .
