### ISSUE TITLE
Release stable version compatible with Spark 2.x

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#1655]
Just putting in my vote for having a released version compatible with Spark 2.x and it's downstream dependencies. If there are blocking issues holding a release up, could they be referenced here?

**Comment by timothymschier** [comment]
+1
We're about to start using a new environment, would be great to have it based on the Spark 2 (and similar) work.

**Comment by lossyrob** [comment]
Thanks for pushing for this, it's good to know people are looking for it to keep pressure on the release cycle.

The main holdup is that we want to release under LocationTech as we graduate from their incubation process, which puts more that development and testing on the blocking issue list.

I've discussed with the LocationTech folk and we're going to try and push ahead this month, and have set a mid-November target date for a GeoTrellis 1.0 release, which would include Spark 2.x support.

**Comment by fosskers** [comment]
Until an official release, stable-ish snapshots of the current `master` branch (1.0.0 w/ Spark 2 and other goodies) can be found here: https://bintray.com/azavea/geotrellis

**Comment by lossyrob** [comment]
Closed with 1.0
