### ISSUE TITLE
GeoWave Code Currently Non-Functional

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech/geotrellis#1669]
The GeoWave integration code (at least the raster portion of it) is currently non-functional.  Our code currently relies on GeoWave `0.9.3-SNAPSHOT` rather than a specific hash or release, and some incompatible changes were introduced at some recent point in the past.

Hopefully there will be some resolution before `0.9.3` is released an we can depend on that, or we can find a way to depend on a particular hash (`c127c16` is known to work).

A [GeoWave issue](https://github.com/ngageoint/geowave/issues/914) has been created.  The present issue is for keeping track of state of that issue with respect to our code.

The pull request https://github.com/geotrellis/geotrellis/pull/1665 fixes our tests so that they pass on GeoWave `c127c16`.

**Comment by lossyrob** [comment]
If this is not fixed before the release, we'll have to mark this feature as experimental.

**Comment by jamesmcclain** [comment]
That is logical.

**Comment by jamesmcclain** [comment]
This appears to have been fixed by locationtech/geotrellis#1933
