### ISSUE TITLE
docs issues #1604 subtask 2 of 4: Handle spatio-temporal data.

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1740]
Did we decide this is more a task for Eugene?

**Comment by jpolchlo** [comment]
That was my understanding of it.  Eugene can comment if he needs someone to
take on the task.

**Comment by lossyrob** [comment]
@rossbernet is this still a task that should be open? If so, it could use a good description.

**Comment by rossbernet** [comment]
@echeipesh @jpolchlo Should this be closed? Lack of context makes it tough for me to say. Don't remember exactly what this was referring to.

**Comment by jpolchlo** [comment]
I'm not sure if spatio-temporal data is yet handled in the docs.  @fosskers
might be the best person to say at this point.

**Comment by fosskers** [comment]
To be honest I'm not sure what "handle spatial-temporal data" means in this context. Does this mean tile layers indexed by `SpaceTimeKey`s? Do we want examples? Do we need examples? etc.

**Comment by jpolchlo** [comment]
I think the idea was to have examples of importing data with space-time
keys.  I never wrote a demo of that, and wonder if there already exists an
example like that in the docs.  Maybe the best way to go here is to use ETL
for spatio-temporal data?
