### ISSUE TITLE
docs issues #1604 subtask 4 of 4: Accumulo 

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1742]
Create a catalog in Accumulo, ingest data into it, and expose the catalog for use in a web application. (split to new issue? table for now? maybe not a 1.0 release mile stone. )

Sounds like this is not 1.0 possible. 

And we talked about possibly not having this on main geotrellis docs page, but rather on some kind of geodocker RTD?

**Comment by jpolchlo** [comment]
This is a fairly tall order, and may be better addressed by chatta demo or
landsat demo.  If that is the case, then the issue can be solved by
referencing those projects.
