### ISSUE TITLE
Cross compile/publish to 2.12

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#1751]
We need to compile and publish to 2.12.

We should use this opportunity of having multiple travis builds also to break out Travis tests into more than 2 build sets, since build times are exceeding the time limit sometimes. (Seems like SET 1 is the culprit)

**Comment by pomadchin** [comment]
Spark 2.12 support issue: https://issues.apache.org/jira/browse/SPARK-14220

**Comment by lossyrob** [comment]
Ah, I thought it was already building on 2.12...

**Comment by lossyrob** [comment]
Pushing to 1.1, as 2.12 is too fresh for now...

**Comment by pomadchin** [comment]
A small update: `Spark 2.3.0` is expected to support `Scala 2.12`

**Comment by pomadchin** [comment]
Update: hopefully `Scala 2.12` support would be by the end of this year.

**Comment by metasim** [comment]
Interested in sharing lessons learned, as we go through this process.

**Comment by pomadchin** [comment]
@metasim no real story would be behind it; GT already can be compiled against 2.12; the only bug / feature i faced is: https://github.com/locationtech/geotrellis/pull/2727/files#diff-b79f2573bbab4c81247de9ca82d2d6f8R31

looking forward to see spark 2.4 to create a proper PR, i expect some some possible changes in runtime.

**Comment by pomadchin** [comment]
https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-maven-hadoop-2.7-ubuntu-scala-2.12/ :tada: first Spark 2.12 green builds!

**Comment by pomadchin** [comment]
Release! http://central.maven.org/maven2/org/apache/spark/spark-core_2.12/2.4.0/  :tada:
