### ISSUE TITLE
Fix VectorJoin

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1795]
The current implementation of the VectorJoin forces a broadcast of the `right` partition after pulling it to the driver. This is not what we expect and needs to be changed to avoid using the driver memory through cartisian join on rtrees.

Also there exists another version of a VectorJoin on `RDD[(K, V)]` that builds the rtree on the `K`, which must be mappable to `Envelope` and then uses the index to produce a "smart" cartisian product through an RDD.flatMap or something.

**Comment by jamesmcclain** [comment]
A few additional notes:

Using the [PointsToDem code](https://github.com/jamesmcclain/PointsToDem/tree/feature/vector-join-experiments) as a proxy for the typical vector join workload (using this command: `$SPARK_HOME/bin/spark-submit --master 'local[*]' --class geotrellis.dem.Dem dem/target/scala-2.11/dem-assembly-0.jar $algo 30`), I got the following results when testing [a number of different vector join approaches](https://github.com/jamesmcclain/geotrellis/tree/fix/vector-join).

(Expand/reduce is not a vector join approach, it is there for comparison.)

Algorithm|Millis
---|---
Expand/Reduce|18062
Vector Join (current master)|24073
Vector Join (produce list of keys per Geometry)|152538
Vector Join (Eugene's original w/ optimal `LayoutDefinition`)|143234

Conclusion: the current vector join implementation is pretty good.  It is computationally optimal but sub-optimal in terms of communication.  I cannot find anything in the list of standard Spark "transformations" and "actions" that provides a way forward in terms of reducing communication overhead (there may or may not be be something in the developer APIs).
