### ISSUE TITLE
Inconsistencies in Required Output-Schema Fields for Spark ETL

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#1818]
According to this section of the docs [link](https://github.com/locationtech/geotrellis/blob/master/docs/spark-etl/spark-etl-intro.md#output-json-description), `tileSize` is optional, and leaving it blank is assumed use the whole, original tile. However, looking at the source code shows `tileSize` is required [link](https://github.com/locationtech/geotrellis/blob/master/spark-etl/src/main/resources/output-schema.json#L112). Therefore, we need to fix the source code as to not force the user to submit a `tileSize` when the the entire tile is desired.

**Comment by pomadchin** [comment]
@jbouffard that would be enough just to fix validation schema, as it's handled correct in code: https://github.com/locationtech/geotrellis/blob/master/spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala#L283

**Comment by jbouffard** [comment]
@pomadchin Okay. I'm glad it isn't too involved on an issue.

Also, I was looking through the code of that file and is [this](https://github.com/locationtech/geotrellis/blob/master/spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala#L221) an error? Shouldn't it be `"maxTileSize"   -> i.maxTileSize.toJson` instead?

**Comment by lossyrob** [comment]
What you've pointed out is def an error, and my bad @jbouffard

**Comment by lossyrob** [comment]
I don't understand how `tileSize` is not required. This is the output tile size, not the input tile size. This is not an option: https://github.com/locationtech/geotrellis/blob/a00c35b928e96083188d91734252d66574e3b4a7/spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala#L34

Looks like it defaults but is not optional. Does "optional" mean the same thing as "defaults to 256"? Perhaps the docs need updating, not the code.

**Comment by pomadchin** [comment]
@lossyrob means defaults to 256, though it's not a required field indeed.

**Comment by lossyrob** [comment]
Ok, I'd say that the list should specify that it defaults to 256...

@jbouffard original assumption "According to this section of the docs link, tileSize is optional, and leaving it blank is assumed use the whole, original tile" is incorrect, so clarifying it would prevent that misunderstanding elsewhere

**Comment by jbouffard** [comment]
@lossyrob Ah, I was mistaken. I got the input and output confused. I think that it would still be "optional" even if it defaults. Though, I would add that to the docs to make it clear. Also, I think that the `spark-etl-intro` doc should be further updated to include the new fields that were added to both the input and output json like `maxTileSize` and `numPartitions`.

**Comment by lossyrob** [comment]
True, that's a glaring omission from the docs. Can you add those new options?

**Comment by jbouffard** [comment]
@lossyrob Yeah, I'll do that now.
