### ISSUE TITLE
Accumulo update up to 1.8.0

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#1869]
Accumulo 1.8.0 is [out](https://accumulo.apache.org/downloads/).

**Comment by lossyrob** [comment]
Does Accumulo use SemVer? From the changelog (https://issues.apache.org/jira/browse/ACCUMULO/fixforversion/12329879/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel), doesn't seem a lot has changed. If the client API is the same, and will work against 1.7 DBs, this seems like an easy upgrade.

**Comment by pomadchin** [comment]
That's true, but changes are mostly related to our test suite: [MockInstance](https://accumulo.apache.org/1.8/apidocs/org/apache/accumulo/core/client/mock/MockInstance.html) is deprecated, some code refactor with tests should be done.

**Comment by echeipesh** [comment]
Resolved with https://github.com/locationtech/geotrellis/commit/f8691ec59cbec8bd4a581606d055e5072f5dffbd#diff-4c5054c81ab98896d1b6cca11683db18
