### ISSUE TITLE
Reorganize GeoTrellis github org repositories

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#1943]
We should reorganize/cleanup the GeoTrellis org repositories, with the following ruleset:

- Demo repos should be named `geotrellis-XXXX-demo`, where XXXX is the specific name of the demo.
- `climate-grok` needs to be named something different and taken from @echeipesh's location. This repo is the climate work we did a while ago, and needs updating.
- Figure out what repos to cut loose
- Priority Places is a decommissioned application, so it now is a demo.

@rcheetham is there other things I missed here?

**Comment by metasim** [comment]
Is this about `locationtech/geotrellis`, or `azavea/geotrellis`?

**Comment by lossyrob** [comment]
This is about [GeoTrellis](https://github.com/geotrellis) github org repositories - all the demos etc in the original GitHub org. The only thing we moved to `locationtech` is the main `geotrellis` repo, and there's a lot left at the original org
