### ISSUE TITLE
Implement new color ramps based on Carto Colors

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1944]
Carto has developed useful color ramps as per:

https://carto.com/carto-colors

However. As part of this issue, it will be important to consider attribution methods under the Create Commons licensing they employ, as per:
https://github.com/CartoDB/CartoColor

**Comment by lossyrob** [comment]
These are a bit too many and non-descript to include. I've included a link to the carto-colors site in the docs as well as a doc string on our `ColorRamps` object; if people would like to use them (they are a great resource), they can pretty easily new up a color ramp with those values.
