### ISSUE TITLE
Documentation for geotrellis-slick subproject

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#1953]

**Comment by fosskers** [comment]
https://github.com/locationtech/geotrellis/blob/_old/feature/vector-tiles/docs/slick/slick-intro.md

I think these were misplaced during the docs overhaul.

**Comment by fosskers** [comment]
Was this added back somewhere (I couldn't find a PR), or was it decided to not bother with it?

**Comment by rossbernet** [comment]
@echeipesh and I just realized this was probably closed in error - it wasn't worth writing from scratch, but if it already exists, it should be added back.

**Comment by echeipesh** [comment]
We seemed to have settled on using `doobie` over `slick` so this is no longer relevant issue.
