### ISSUE TITLE
renderPng(ColorRamp) does not render double value tiles correctly

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#1957]
https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/render/PngRenderMethods.scala#L54

The logic of the if statement is incorrect - should say `!self.cellType.isFloatingPoint`

Thanks to @prahim for catching this.

**Comment by pomadchin** [comment]
Closed here #2022
