### ISSUE TITLE
Keeping filepath in HadoopGeoTiffRDD

### ISSUE THREAD

**Issue by quertenmont** [locationtech/geotrellis#1958]
Hello,

It's really a pity that the filepath is dropped when reading geotiffs using:
https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala#L108

Is there any chance to update the function so we have a possibility to keep track of the files that we are processing in the rdd.  ?

Can you also add a similar function to read local files to an RDD ?

Thanks,
Loic

**Comment by pomadchin** [comment]
Hi @quertenmont! It is possible to read local files into rdd using this function, as Hadoop allows it, just be sure that you specified path to a folder you want to ingest with protocol specification: `file:///abs/path/to/local/`

What do you mean by keep track? To track possible failures during the load, or what's the use case?

**Comment by quertenmont** [comment]
No, I mean that it would be nice to keep the file path in the RDD,
currently this information is lost using the geotrellis helper function.

Very often (at least in my case), the file name contains some useful
information that are not necessary into the GeoTiff metadata.

Do you see what I mean?

Loic




--------------------------------------------------------------------------------------------
   Loic Quertenmont - Data Scientist at Kensu.io
   Phone: +32 474 831 531       Skype: loic_quertenmont
--------------------------------------------------------------------------------------------

2017-02-22 14:45 GMT+01:00 Grisha <notifications@github.com>:

**Comment by pomadchin** [comment]
@quertenmont good idea, thx for clarification.

**Comment by lossyrob** [comment]
I can imagine an input key type that is the composition of the ProjectedExtent and some file information, which could be read in. This unfortunately is non-trivial, since the `RasterReader` abstraction does not have access to the path (https://github.com/locationtech/geotrellis/blob/e0b98d96ab53d2ee43f9a84f0b584202779dd0ce/spark/src/main/scala/geotrellis/spark/io/RasterReader.scala).

@echeipesh any ideas on how to solve this?

**Comment by pomadchin** [comment]
@lossyrob https://github.com/locationtech/geotrellis/pull/2050 ah, I forgot to link issues. But mb there should be done a stronger change, can you have a quick look?
