### ISSUE TITLE
Bug in PolygonRasterizer

### ISSUE THREAD

**Issue by quertenmont** [locationtech/geotrellis#1962]
Hello,

I am fighting since a couple of hours with a " java.lang.ArrayIndexOutOfBoundsException" exception coming from the PolygonRasterizer.
After some dig out, I notice it is due to the line 
https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala#L386

My rowRuns array as a length of 3  (using PixelIsPoint) method,
so when calling line 386 at the second i-loop iterations, it tries to access the fourth element of a 3 elements array... and crashes...

I understand that the cause of the error is likely coming from the runsPoint function itself,
or possibly because of this polygon being too complex and/or fishy to met the computation assumptions...
(I am not particularly interested in debugging this...)

However, I would still suggest to change line 384 from
` while (i < rowRuns.length) {`
to
` while (i < rowRuns.length-1) {`

which would make me miss a row in this fishy polygon, but would avoid the exception.

Thanks in advance,
Loic

**Comment by jamesmcclain** [comment]
Hello.  Can you provide us with the polygon (or a polygon) that causes this?  Thank you.

**Comment by quertenmont** [comment]
Hello,

I have the problem coming in a few times:

1)
POLYGON ((0.007754 -0.006775, 0.007758 -0.006768, 0.00776 -0.006766, 0.007763 -0.006762, 0.007765 -0.006761, 0.007772 -0.006762, 0.007777 -0.006763, 0.007782 -0.006765, 0.00779 -0.00677, 0.007791 -0.006773, 0.007792 -0.006779, 0.00779 -0.006785, 0.007787 -0.006787, 0.007781 -0.006786, 0.007773 -0.006783, 0.007768 -0.00678, 0.007761 -0.00678, 0.007755 -0.006779, 0.007754 -0.006775))
with
GridExtent(Extent(0.0, -0.00904, 0.009188, 0.0),6.755882352941177E-5,6.746268656716418E-5)

2)
POLYGON ((0.00498 -0.004533, 0.004975 -0.004582, 0.004975 -0.004583, 0.004974 -0.004594, 0.004968 -0.004605, 0.004959 -0.00461, 0.004955 -0.004611, 0.00495 -0.004611, 0.004913 -0.004595, 0.004903 -0.004587, 0.004902 -0.004584, 0.004886 -0.004542, 0.004884 -0.004535, 0.004885 -0.004507, 0.004889 -0.004495, 0.004897 -0.004489, 0.004904 -0.004486, 0.004916 -0.004484, 0.004917 -0.004485, 0.004927 -0.004487, 0.004938 -0.004494, 0.004939 -0.004497, 0.004943 -0.004502, 0.004951 -0.00451, 0.004966 -0.004518, 0.004967 -0.004519, 0.004971 -0.004521, 0.004972 -0.004521, 0.004976 -0.004524, 0.00498 -0.004532, 0.00498 -0.004533))
with
GridExtent(Extent(0.0, -0.009042, 0.009171, 0.0),1.0814858490566039E-5,1.0802867383512545E-5)

3)
POLYGON ((0.003045 -0.004534, 0.003045 -0.004538, 0.003044 -0.004539, 0.003042 -0.004542, 0.003042 -0.004544, 0.003041 -0.004544, 0.003041 -0.004545, 0.00304 -0.004547, 0.003039 -0.004547, 0.003038 -0.004548, 0.003037 -0.004549, 0.003037 -0.00455, 0.003036 -0.00455, 0.003035 -0.004551, 0.003035 -0.004552, 0.003034 -0.004553, 0.003033 -0.004554, 0.003032 -0.004555, 0.003032 -0.004556, 0.00303 -0.004556, 0.003029 -0.004557, 0.003027 -0.004558, 0.003026 -0.004558, 0.003026 -0.004559, 0.003025 -0.004559, 0.003024 -0.004559, 0.003023 -0.00456, 0.003022 -0.00456, 0.00302 -0.004561, 0.00302 -0.004562, 0.003017 -0.004562, 0.003015 -0.004563, 0.003009 -0.004563, 0.003008 -0.00456, 0.003007 -0.004559, 0.003007 -0.004558, 0.003007 -0.004557, 0.003006 -0.004555, 0.003006 -0.004553, 0.003005 -0.004551, 0.003005 -0.004536, 0.003006 -0.004535, 0.003007 -0.004534, 0.003007 -0.004532, 0.003008 -0.004532, 0.003008 -0.004531, 0.003009 -0.00453, 0.003009 -0.004528, 0.00301 -0.004528, 0.00301 -0.004527, 0.003011 -0.004526, 0.003012 -0.004525, 0.003013 -0.004524, 0.003014 -0.004523, 0.003015 -0.004523, 0.003015 -0.004522, 0.003016 -0.004522, 0.003018 -0.004521, 0.003019 -0.004521, 0.00302 -0.00452, 0.00302 -0.004519, 0.003021 -0.004518, 0.003022 -0.004518, 0.003023 -0.004517, 0.003024 -0.004517, 0.003026 -0.004515, 0.003027 -0.004515, 0.003029 -0.004514, 0.00303 -0.004514, 0.003031 -0.004513, 0.003032 -0.004512, 0.003035 -0.004512, 0.003036 -0.004513, 0.003037 -0.004514, 0.003038 -0.004516, 0.003038 -0.004519, 0.003039 -0.00452, 0.00304 -0.004521, 0.00304 -0.004522, 0.003041 -0.004524, 0.003041 -0.004525, 0.003042 -0.004526, 0.003043 -0.004527, 0.003045 -0.004534))
with
GridExtent(Extent(0.0, -0.009042, 0.009156, 0.0),1.0797169811320753E-5,1.0802867383512545E-5)


Happy debugging!
Loic

**Comment by quertenmont** [comment]
By the way, in any case, you should change line 384 to "while (i < rowRuns.length-1) {"
the current line is just prone to such exception.

**Comment by jamesmcclain** [comment]
#1963 contains a fix.  Please give it a try if you have a chance.
