### ISSUE TITLE
Density Map from Polylines

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#1965]
Hello,

to everyone.
I want to develop a procedure to create density maps (like a tile service) from points which have timestamp.
These points can be group by  there id and ordered by timestamp, then I want create lines from these points that don't cross areas that the points can be found (like a mask)

In the final step I will analyze these polyline and get a density map.

The data are around 0.5 TB size.

My question can geotrellis provide these kind procedure?

Thx, in advanced.

X.

**Comment by lossyrob** [comment]
@Charmatzis we've been having discussions in Gitter around these issues; let me know if there's something that still should be covered by an issue and we can open a new issue.
