### ISSUE TITLE
Problem vectorizing complex raster

### ISSUE THREAD

**Issue by quertenmont** [locationtech/geotrellis#1985]
Hello,

The polygons created out of my DoubleConstantNoDataArrayTile thanks to the "toVector" method have much more vertices than I was expected.  Actually, it seems that many of these vertices could be removed with minimal effect on the overall polygon shape. 
So my question is, what's the best way to "smooth" my polygons to make them more lightweight in terms of vertices. 

Thanks for your suggestions,
Loic

**Comment by quertenmont** [comment]
Another type of problem that I have with some calls to "toVector" are:
com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 0.008278639760479043 -0.006530101431980907, 0.008289433293413176 -0.006530101431980907 ) and LINESTRING ( 0.008289433293413175 -0.006530101431980907, 0.008289433293413175 -0.006540894988066826 ) [ (0.008289433293413175, -0.006530101431980907, NaN) ]

There is a nan somewhere in there, which doesn't sounds GOOD :-)
do you have any suggestion for a quick workaround?

Thanks,
Loic

**Comment by lossyrob** [comment]
@quertenmont you could use simplification on the polygon: https://geotrellis.github.io/scaladocs/latest/index.html#geotrellis.vector.simplify.SimplifyMethods@simplify(tolerance:Double):G

We make the polygon around the cells, so I suspect that's why it looks more jagged then you were expecting. We don't have a vectorization that connects cells through their center point, which I imagine would create a smoother polygon. You could add an issue for this as a feature request.

For the exception, can you give the data that is causing it so we can debug?

**Comment by quertenmont** [comment]
Thanks, I'll look into it and save you a tile giving the error (tomorrow likely).

**Comment by quertenmont** [comment]
Here is one of the tile that I have a hard time to vectorize...
(looking at the picture, it makes sense, because as a human I wouldn't know where to start ;-) )
But still, would be nice to have it work.

![bugthevectorizer](https://cloud.githubusercontent.com/assets/4639944/22345485/91599f94-e400-11e6-98f7-254fbecd0956.png)

I am wondering if it would make sense to try building the polygon from an inverted tile,
and then subtract those polygon to the image rectangle --> Would lead to a rectangle with holes.

Thanks for your suggestions,
Loic

**Comment by lossyrob** [comment]
Hi Loic,

Sorry for the delayed response. That does look like a tough one to vectorize...the Topology exceptions have to do with JTS robustness, which unfortunately we can't solve in GeoTrellis. There are workarounds in JTS to deal with this, however getting the vectorizer to use the workarounds in some cases would be some work (and would be a good target for an additional issue). See http://tsusiatsoftware.net/jts/jts-faq/jts-faq.html#D9 for more details.

If you have a GeoTIFF version of the above tile, I can run against it and take a look.

**Comment by quertenmont** [comment]
That's fine,
The workaround I used was to split the tile in 4 quarter and vectorize each
of them separately.  In case of faillure on a sub tile I reiterate the
splitting procedure on it untill all sub tiles succeeded or the size of the
sub tile is small enough to be ignored.

Polygons from subtitles are the joined using a union.

Cheers
Loic

**Comment by lossyrob** [comment]
Clever workaround, it's good to know that works in this situation!
