### ISSUE TITLE
Dana Tomlin Demo of Python Bindings for GeoTrellis

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1987]
Dana Tomlin has expressed interest in using GeoTrellis in his software design course at Penn and Yale.

To do this, we need to work with him first to understand his needs / hopes / expectations for how this could be used in class.

We plan for this to involve python bindings, a jupyter notebook, and the ability to use primative map algebraic methods. With a straight forward way of accessing raster data sets.

**Comment by kotfic** [comment]
Just as an FYI,  we're actively working on integrating Geotrellis into an open source extension to the Jupyter notebook  [OpenGeoscience/geonotebook](https://github.com/OpenGeoscience/geonotebook).  The software is still under active development,  but there may be an opportunity for collaboration

**Comment by jpolchlo** [comment]
I don't know exactly what your plans are, but you may want to check out
geodocker/geodocker-geotrellis-jupyter where we have a docker container
that uses Apache Toree to give you access to a Scala notebook with a
SparkContext and
Geotrellis.  That might fit your needs?

**Comment by dorukozturk** [comment]
Those look very interesting. We will definitely look into them more closely.

**Comment by lossyrob** [comment]
@kotfic this looks like a great project. If there's any help we can give with the extension, let us know. It would be great to find a way to collaborate! We'll be taking a deeper look into the project soon.

**Comment by lossyrob** [comment]
This has to do with projects that were moved outside of core GeoTrellis - should we make issues there and track in a different place? /cc @rossbernet
