### ISSUE TITLE
Hillshade with Python Bindings

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#1988]
This is a sample use case to test the ease with which it will be to open a jupyter notebook and use python bindings to calculate hillshade.

The output should be a step by step demo that is as easy to follow as possible.

**Comment by lossyrob** [comment]
Unclear if we should be tracking this in this repo. @rossbernet thoughts?

**Comment by rossbernet** [comment]
should it be in https://github.com/locationtech-labs/geopyspark ?

**Comment by lossyrob** [comment]
I think so. There won't be a PR that closes this issue, but will be on geopyspark, so I think it should be moved there.
