### ISSUE TITLE
SQLite Backend

### ISSUE THREAD

**Issue by fosskers** [locationtech/geotrellis#1989]
If one ingests a tileset, how do they share the results? Outside of shared permissions on an S3 bucket, the closest answer we currently have is to zip a `catalog/` that was output via our filesystem backend.

 It would be useful to provide an sqlite tile backend for GeoTrellis, as:

- It would be easy to set up its runtime environment (slightly more effort than FS but less than all others)
- The database is a single `.db` file on the FS. Easily shareable.

We often associate SQLite with phones, but people use it outside of mobile environments all the time. It supports concurrent reads/writes and is decently performant on a single machine. 

**Question:** What's the best way to interface to SQLite via Scala?

**Comment by fosskers** [comment]
As a bonus, this could allow us to produce `MBTiles` files, which are collections of VectorTiles stored in a SQlite db file.

**Comment by moradology** [comment]
Looks like SpatiaLite database definitions are one of the ways you can export data from Carto: https://carto.com/docs/carto-engine/sql-api/making-calls#response-formats

**Comment by moradology** [comment]
Another argument for this feature: https://github.com/mapbox/mbtiles-spec
