### ISSUE TITLE
GeoServer integration 

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#1990]
We need to integrate GeoTrellis with GeoServer so that users can more easily interact with the data they ingest. Minimally, such an integration should include:

- [ ] TMS layer viewing
- [ ] Metadata viewing

**Comment by echeipesh** [comment]
This makes sense but should be part of a separate project, perhaps: https://github.com/geotrellis/geotrellis-server

**Comment by echeipesh** [comment]
I think the intent of this issue was that GeoTrellis would serve GeoTrellis layers using OGC protocols such that they could be proxied through GeoServer or consumed through GeoTools. In that case this is now being handled by https://github.com/geotrellis/geotrellis-server project
