### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#2000]
Hi to every one,

Is there a way to compile faster ????

`sbt assembly `

takes more 15 minutes !!!!

**Comment by pomadchin** [comment]
Hi! It is a library, you don't need to compile / build assembly of geotrellis :) How do you use it? Of what subproject assembly do you use / trying to use / trying to build assembly?

**Comment by Charmatzis** [comment]
Well I use 
`sbt assembly` to build a jar file as the tutorials describes...

https://github.com/geotrellis/geotrellis-pointcloud-demo/blob/master/README.md#this-project-build 

that can take over 15 minutes

**Comment by lossyrob** [comment]
Are you running `sbt assembly` in that codebase, or in the GeoTrellis codebase?

**Comment by Charmatzis** [comment]
GeoTrellis codebase

**Comment by lossyrob** [comment]
The instructions you point to were updated, and do not talk about running `assembly` on the geotrellis codebase. My guess is that they mentioned running `assembly` on the codebase you linked to.

That project is under active development; I would recommend looking at https://github.com/geotrellis/geotrellis-landsat-emr-demo for a more stable demo.

**Comment by lossyrob** [comment]
Closing because you should not run `assembly` on the root GeoTrellis SBT aggregate project.
