### ISSUE TITLE
How can I read a CSV file?

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#2002]
Hi, is there a way to read large CSV files with fields Lat, Log  and create them to point?

Examples are accepted...

**Comment by lossyrob** [comment]
Hi,

If you can read in latitudes and longitudes from a CSV file, then it's just a matter of calling the apply method on Point:

```scala
val lat: Double = ??? // From CSV file row
val lng: Double = ??? // From CSV file row

val point: Point = Point(lng, lat) // Notice lng = x and lat = y
```

Closing this issue. If there are general questions, please ask the mailing list or the gitter channel. Issues should be used for specific tasks, e.g. "Improve documentation on geometry creation" with a description of the feature request or bug.
