### ISSUE TITLE
Documentation on creating `TileLayerRDD` from `Tile`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2006]
Per [this conversation](https://gitter.im/geotrellis/geotrellis?at=589c45e91465c46a564088aa), it would be helpful to have a documentation example showing how to create a `TileLayerRDD` from an existing in-memory `Tile`.

Example from @lossyrob 

```scala
val layoutScheme = ZoomedLayoutScheme(crs)
val md = rdd.collectMetadata(layoutScheme)
val result: TileLayerRDD[SpatialKey] = ContextRDD(rdd.tileToLayout[SpatialKey](md), md)
```

**Comment by metasim** [comment]
Also consider making an API that simplifies the process.

**Comment by nandanrao** [comment]
The examples in the gitter and here didn't work for me, needed an implicit for `Boundable[SpatialKey]` that I hunted down for a while, and then also needed to lookup the return of tileToLayout and realize that different signatures have different returns, and because we had a zoomed layer, it was returning a tuple instead of just the metadata... 

```scala
import geotrellis.spark.SpatialKey._
val rdd = sc.parallelize(Seq((ProjectedExtent(extent, crs), tile)))
val layoutScheme = ZoomedLayoutScheme(crs)
val md = rdd.collectMetadata(layoutScheme)
val realRDD = ContextRDD(rdd.tileToLayout[SpatialKey](md._2), md)
```

**Comment by fosskers** [comment]
Formalized as a function:
```scala
  /** Convert an in-memory `Tile` into a GeoTrellis layer. */
  def tileToLayer(raster: ProjectedRaster[Tile])(implicit sc: SparkContext): TileLayerRDD[SpatialKey] = {

    val layer: RDD[(ProjectedExtent, Tile)] =
      sc.parallelize(List((ProjectedExtent(raster.raster.extent, raster.crs), raster.raster.tile)))

    val scheme: LayoutScheme = ZoomedLayoutScheme(raster.crs)

    /* The metadata, plus the zoom level corresponding to the size of the Tile.
     * We don't need the zoom level here, but it deserves a note.
     */
    val meta: (Int, TileLayerMetadata[SpatialKey]) = layer.collectMetadata(scheme)

    ContextRDD(layer.tileToLayout[SpatialKey](meta._2), meta._2)
  }
```

**Comment by fosskers** [comment]
https://github.com/fosskers/playground/blob/master/scala/geotrellis/src/main/scala/playground/TileToLayer.scala
