### ISSUE TITLE
Publish `geotrellis.spark.TestEnvironment`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2012]
When doing Spark tests in my own code it would be nice to use the same test environment setup that GeoTrellis uses for Spark, as defined by `geotrellis.spark.TestEnvironment`. There are at least two ways to do this:

1. Publish the `"org.locationtech.geotrellis" %% "geotrellis-spark" % "1.0.0" % "test"` artifact as a part of the standard release process. This should be as easy as adding `publishArtifact in (Test, packageBin) := true` to the sub-project.
2. Refactor `geotrellis.spark.TestEnvironment` so that it can live in `geotrellis-spark-testkit`, which does get published (I think).

**Comment by metasim** [comment]
Happy to work on this if you tell me which direction you'd like me to take.

**Comment by lossyrob** [comment]
Quick answer, IMO it should be in spark-testkit, that's were we publish generic test code for usage in other projects.

**Comment by metasim** [comment]
@pomadchin Thanks much for doing this!
