### ISSUE TITLE
renderPng(colorMap) treats Int rasters as Double

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2022]
https://github.com/locationtech/geotrellis/blob/a00c35b928e96083188d91734252d66574e3b4a7/raster/src/main/scala/geotrellis/raster/render/PngRenderMethods.scala#L53-L62

**Comment by echeipesh** [comment]
Thanks to @diegonc for reporting this: https://gitter.im/geotrellis/geotrellis?at=58a7439fde50490822df83ad

**Comment by pomadchin** [comment]
https://github.com/locationtech/geotrellis/issues/1957
