### ISSUE TITLE
Clear path from extent + catalog to `tile` for said extent

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2025]
It should be a relatively simple affair to specify some extent for an ingested catalog and pull out a tile which corresponds to the selected area. This is *not* simple or straightforward. There is currently no obvious, "blessed" path to such a tile and it might be unclear to new users that such a thing is even possible.

**Comment by echeipesh** [comment]
https://github.com/locationtech/geotrellis/blob/master/spark/src/test/scala/geotrellis/spark/io/AllOnesTestTileSpec.scala#L69-L75

**Comment by moradology** [comment]
Clearly this is supported, but it still seems as though there's a clumsiness around the discovery of this important feature which we should try to limit with some documentation or massaging of the API

**Comment by echeipesh** [comment]
Went a looking and found a section in the docs that covers this use case:
http://geotrellis.readthedocs.io/en/latest/guide/spark.html?highlight=query

**Comment by lossyrob** [comment]
@moradology does the docs @echeipesh pointed out resolve this, or should additional docs be made?

**Comment by fosskers** [comment]
Ah, there's derpy markup on that page that I need to fix. Thanks for the link @echeipesh .
