### ISSUE TITLE
Consider Switching to Maven/Ivy/Semantic-Versioning Compatible Use of `SNAPSHOT`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2032]
Under [maven](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400) [conventions](http://stackoverflow.com/a/9554758/296509) and [best practices](http://kylelieber.com/2012/06/maven-versioning-strategy/), and the [Semantic Versioning spec](http://semver.org/#spec-item-11), a `SNAPSHOT` version is considered lesser/earlier than a point release version. That is: `1.0.0-SNAPSHOT` < `1.0.0` < `1.0.1-SNAPSHOT`. GeoTrellis has released `1.0.0`, yet continues to update the `1.0.0-SNAPSHOT` artifact. Because of existing Maven/Ivy conventions and the Semantic Versioning spec, this causes end-user confusion as to how one might identify the "bleeding edge" binaries vs the "stable" ones. 

GeoTrellis would benefit from following established conventions in this area, especially given that many people are currently using `SNAPSHOT` releases to test out new features. Under the schemes above, `1.0.0-SNAPSHOT` should be retired, and the current development builds delivered as `1.0.1-SNAPSHOT` or `1.1.0-SNAPSHOT` (or something greater than `1.0.0`). To identify the bleeding edge version, most Maven/Ivy aficionados would first look at the last release version, and then look for a `SNAPSHOT` tagged version which is greater than that in the snapshots repo. I interpreted the lack of such a think existing in GT as an indication that `SNAPSHOT` builds were no longer being published.

**Comment by fosskers** [comment]
We ought to form the habit: whenever a new release is made, immediately commits a version bump on `master` to the next PATH version. In this case, `1.0.1`. If it turns out that the next release would in fact be `1.1.0`, bump as a appropriate for the release, then bump PATCH again immediately after.

**Comment by jamesmcclain** [comment]
+1

**Comment by lossyrob** [comment]
This was supposed to happen, but I forgot to :man_facepalming: #2042

**Comment by metasim** [comment]
Thanks guys.
