### ISSUE TITLE
`java.util.NoSuchElementException: None.get` from `TemporalProjectedExtentCodec.encode`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2033]
The `epsgCode` in trait `CRS` is marked as `Option[Int]`, but `TemporalProjectedExtentCodec` ignores the optionality and unsafely calls `get`.

https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/avro/codecs/TemporalProjectedExtentCodec.scala#L42

Getting this exception after reading in some MODIS data where the embedded CRS doesn't reference an EPSG code (assuming [this branch](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala#L244) was taken). At any rate, it doesn't seem uncommon for [this function](https://github.com/locationtech/geotrellis/blob/master/proj4/src/main/scala/geotrellis/proj4/CRS.scala#L51) to come along a "proj4" string it doesn't recognize.

**Comment by lossyrob** [comment]
Closed by #2034
