### ISSUE TITLE
Bring back SHA-tagged CI builds

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2037]
Before the LocationTech transition there were SHA-tagged builds from the development branch. These are really helpful when you want to have the latest-and-greatest, but have it be a stable version (doesn't change out from under you when you sbt does an update).

[sbt-git](https://github.com/sbt/sbt-git) can be of help here from the build side.  Suspect the infrastructure side is where the effort is.

Depends on #2032.

**Comment by lossyrob** [comment]
This unfortunately can't happen, because Bintray got in touch with us saying - "hey don't do that". Publishing artifacts per merge caused a lot of space to be taken up.

Besides bringing back the old Travis/Bintray process, are there any suggestions on how to solve the problems this brings up?

**Comment by metasim** [comment]
Good to know about Bintray. Let me think on this. If I can find something [like this](http://www.mojohaus.org/versions-maven-plugin/examples/lock-snapshots.html) but for sbt, then it may be we can achieve something similar with the snapshot repository as it already stands. For the time being I'm just [hosting our own](https://bintray.com/s22s/maven/geotrellis-raster) as-needed builds, which is fine for the time being.

**Comment by metasim** [comment]
PS: Close this if it's a distraction in the backlog.
