### ISSUE TITLE
Adopt usage of community Functor in API

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2047]
We have erroneously written our own `Functor` as illustrated by: https://github.com/locationtech/geotrellis/pull/1948

We should pick either Scalaz or cats Functor implementation and use that instead. Since the implicit type class parameter is threaded all the way to user facing API there is no way to make this change without breaking the binary compatibility of user facing API, placing this change at `2.0.0` version.

Some things we may need to consider when making this decision:
 - API friendliness of Scalaz vs cats we are likely to use
 - If it makes sense to depend on both Scalaz and cats (seems doubtful)
 - If not, should stream based collection reading be based on Scalaz?

**Comment by fosskers** [comment]
Cats Functor, please. I have [this project](https://github.com/fosskers/scalaz-vs-cats) as a work-in-progress comparing the two libraries officially.
