### ISSUE TITLE
Find mechanism to move `-test` projects back into parent projects

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2058]
Possibly enabled by #2036.

**Comment by metasim** [comment]
Possibly stalled by sbt/sbt/#3023.

**Comment by fosskers** [comment]
If the testkits were brought back into their parent projects, would their bytecode be included in the assembly jars when published? If so, it would be better to keep them separate.

**Comment by pomadchin** [comment]
@fosskers won't be

**Comment by fosskers** [comment]
The `testkit` subprojects are published, actually.

**Comment by pomadchin** [comment]
@fosskers ah, we are talking about `-test` projects not `-testkit`

**Comment by metasim** [comment]
An update on this: I was [able to move](https://github.com/metasim/geotrellis/commit/40477459e1ea5d13feac8cab86ac8c678c0582ba) `vector-test` into `vector`, but ran into all sorts of problems with both `raster-test` and `s3-test`, including the sbt crash above. Basically, sbt doesn't like circular dependencies. The best plan, long term will be to draw out the dependency graph and rethink some of the organization.
