### ISSUE TITLE
Allow use of proj4 strings in addition to catalog codes in ETL configuration `crs` property.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2072]
Not all satellite data products have CRSs with corresponding EPSG codes in GeoTrellis. The MODIS sinusoidal projection grid is one of these. We would like to ETL MODIS granules in GeoTrellis, but maintain the original CRS. However, the `crs` property in the `output.json` file format only supports using numeric codes prefixed with `EPSG`, `ESRI`, `WORLD`, `NAD83` or `NAD27`. Since these ultimately map to proj4 strings internally, adding a mechanism to accept proj4 strings directly seems like a straightforward and beneficial capability. One approach might be to add `PROJ4` prefix support in `geotrellis.proj4.CRS#fromName` and fall back to `geotrellis.proj4.CRS#fromString`.

**Comment by pomadchin** [comment]
Related to https://github.com/locationtech/geotrellis/issues/1767

**Comment by metasim** [comment]
Related: #2169. I *think* this one has been addressed already.

**Comment by echeipesh** [comment]
Confirm, that looks very much addressed.
