### ISSUE TITLE
Git LFS usage 

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2074]
We can use [Git-LFS](https://git-lfs.github.com/) for test data files, that may improve repository cloning speed / test data versioning / etc.

**Comment by metasim** [comment]
As a part of this, it would be great to get rid of the `.zip`-ing of test data. Makes it a hassle to add new test images, and probably creates massive binary diffs every time you update it, but I'm not sure what the original rationale was.

**Comment by metasim** [comment]
Another idea is to have a separate repo and and artifact containing various test data. Not sure what the technical benefit, but it has aesthetic appeal for some reason.

**Comment by rossbernet** [comment]
related: https://github.com/geotrellis/geotrellis-chatta-demo/issues/42

**Comment by pomadchin** [comment]
Do we still want to keep it open? GIT LFS is very limited in downloads in its free version.

**Comment by echeipesh** [comment]
We should close this. LocationTech is very reluctant in supporting git LFS for their repos and free tier is woefully insufficient.

I think we could use our own version of test utility which downloads test files from s3 and validate checksums such that we can avoid checking any more rasters in.
