### ISSUE TITLE
Polygon Rasterizer not behaving as expected for small RasterExtent

### ISSUE THREAD

**Issue by fosskers** [locationtech/geotrellis#2082]
VectorPipe utilizes the Rasterizer to detect which `SpatialKey`s a given Geometry touches (for some zoom level). The actual example of use is here: https://github.com/geotrellis/vectorpipe/blob/9e0dda4ef99cb1b68b52d19e6a82b3b1932c6155/src/main/scala/vectorpipe/Vectorpipe.scala#L201

We know that most OSM geometries will only appear in one Tile for most zoom levels. This means that the dimensions of the `GridBounds` for these will be 1x1.

**Problem:** at least for 1x1 grids, the Rasterizer doesn't seem to work properly for Polygons. When used in VectorPipe, no Polygons survive to the final output VT.

I created a sample program that does nearly the same thing, except that it draws JPGs instead of returning a set of associated `SpatialKey`s for each geometry. For my sample data, each is totally contained within the tile extent, so the associated grid is drawn as a 1x1 image. If a geom is properly detected, it will be rendered white. Otherwise, black.

Point:
![point](https://cloud.githubusercontent.com/assets/229679/24214435/b7580358-0ef2-11e7-9fb1-e153cabef4d8.jpg)

Line:
![line](https://cloud.githubusercontent.com/assets/229679/24214445/bcab09c2-0ef2-11e7-8848-427ed8d67dad.jpg)

Polygon:
![poly](https://cloud.githubusercontent.com/assets/229679/24214447/c21ec664-0ef2-11e7-9f62-8c99e120fa5e.jpg)

The polygon here draws black, meaning the Rasterizer doesn't think the poly is within the Extent. This is incorrect.

**Comment by fosskers** [comment]
I have a sample program which produces the images. I can upload it if anyone's interested.

**Comment by fosskers** [comment]
This was resolved by giving the proper `Option`s to the Rasterizer: 
```scala
Rasterizer.foreachCellByGeometry(f.geom, re, Rasterizer.Options(true, PixelIsArea))(g)
```

**Comment by jamesmcclain** [comment]
Maybe we should leave this (or some other issue) open for the time-being until there is a resolution for options question.

**Comment by fosskers** [comment]
What is the options question, exactly? That the API isn't as clear as it could be?

**Comment by lossyrob** [comment]
I think a issue for documenting the api would be appropriate

**Comment by jamesmcclain** [comment]
Yes, that is what I was thinking of.
