### ISSUE TITLE
Remove `vectortile` dependency from `spark` sub-project

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2108]
Currently `spark` package depends on `vectortile` to provide Avro codecs, the reverse relationship is not really right either. What this points to is that avro codecs either need to move to either `util` project or a project of their own.

I don't think there is an easy transparent way to do this, so it will have to be queued for next major version.

**Comment by pomadchin** [comment]
It is not a problem any more: both `vectortile` projects and `spark` are independent.
