### ISSUE TITLE
Schema for `intConstantTileCodec` is incorrect.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2109]
The [schema](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/avro/codecs/ConstantTileCodecs.scala#L183) says that the constant should be an array, but [the encoder](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/avro/codecs/ConstantTileCodecs.scala#L183) writes a scalar. Causes unpleasant `Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Collection` error.

**Comment by pomadchin** [comment]
Thx for this report! It's my typo.
