### ISSUE TITLE
ETL: Layer exists returns false for layerIds(0)

### ISSUE THREAD

**Issue by nandanrao** [locationtech/geotrellis#2113]
I'm not entirely clear on the intended behavior here, but based on [these tests](https://github.com/locationtech/geotrellis/blob/ac1a460e7a2c00d1dd9fc12492c1ee18000b6a6d/spark/src/test/scala/geotrellis/spark/io/AttributeStoreSpec.scala#L44), I expected that if an attribute store has an id in its list of id's, then they should exist when queried via "layerExists": 

File structure: 

```
etl
├── backend-profiles.json
├── geotrellis-spark-etl-assembly-1.1.0-SNAPSHOT.jar
├── input.json
├── output.json
└── tiles
    ├── _attributes
    │   └── mobile___8___metadata.json
    └── mobile
        └── 8
            ├── _SUCCESS
            └── part-r-00000-49914
                ├── data
                └── index
```

Code: 

```
val store = HadoopAttributeStore("./etl/tiles")
store.layerExists(store.layerIds(0))
```

Results:

```
res32: Boolean = false
```

It seems to have a layerId: 

```
store.layerIds(0)
res33: geotrellis.spark.LayerId = Layer(name = "mobile", zoom = 8)
```

This also causes the reader to throw, naturally. 

The problem is that HdfsUtils.listFiles will return an absolute path, but when following the ETL tutorial, it was not clear to me that we must first create an absolute path. Not sure if that's what [this comment](https://github.com/locationtech/geotrellis/blob/147c6a230e92f88917a54af130764f9fb2da5bc2/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala#L115) is referring to?

**Comment by lossyrob** [comment]
@nandanrao interesting; I'm actually surprised the `store.layerIds(0)` works...`./etl/tiles` (which is a relative path) is not a Hadoop path, e.g. `file:///home/user/etl/tiles`. I expect that is why the exists part is failing. I'm going to investigate.

**Comment by aklink** [comment]
I have an issue with **Layer exists** using relative paths to local filesystem using HDFS with VM option **-Dspark.master=local[*]** after **upgrading** from Geotrellis **0.10.3** (with Spark 1.6.2) **to** Geotrellis **1.0.0** (with Spark 2.1.0). Previously same code was working well.

Additionally **reading a layer** using HadoopLayerReader(attributeStore) also **fails** with **geotrellis.spark.io.package$LayerNotFoundError**, although it was successfully written with HadoopLayerWriter (files have been created by writer in local filesystem including valid metadata in **_attributes**). 
```
Exception in thread "main" geotrellis.spark.io.package$LayerNotFoundError: Layer Layer(name = "layer_L8_B5_nir", zoom = 13) not found in the catalog
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:57)
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:45)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:57)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:71)
	at geotrellis.spark.io.LayerReader$class.read(LayerReader.scala:48)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:29)
```
To avoid conflict with previous runs from Geotrellis 0.10.3, the Attribute Store have been cleaned before processing. 

https://github.com/biggis-project/biggis-landuse/issues/9

**Comment by pomadchin** [comment]
@aklink makes sense, layerExist function was changed: [old](https://github.com/locationtech/geotrellis/blob/_old/v0.10.3/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala#L99-L105) vs [new](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala#L114-L122]

Can you check your code on https://github.com/locationtech/geotrellis/pull/2123 ?

**Comment by aklink** [comment]
@pomadchin Thank. Is there a simple way to check if #2123 is working with my code? 
Currently Geotrellis is imported in my project using Maven (pom.xml) e.g.
```
  <!-- https://mvnrepository.com/artifact/org.locationtech.geotrellis/geotrellis-spark_2.11 -->
  <dependency>
      <groupId>org.locationtech.geotrellis</groupId>
      <artifactId>geotrellis-spark_2.11</artifactId>
      <version>1.0.0</version>
  </dependency>
```
I am not using the Geotrellis Git repository directly. So I could switch to e.g. 1.1.0-RC2 via Maven, but not to a specific pull request. Or can I override the code somehow to just use the code from pull request?

**Comment by pomadchin** [comment]
@aklink eh, the only way is to pull down #2123 PR, publish it into a local repo (`./scripts/publish-local.sh`), and to use `<version>1.1.0-SNAPSHOT</version>`; 

Or to wait until RC3 would be published (hopefully today).

**Comment by aklink** [comment]
@pomadchin Thanks again. I will try if I can get it run using your description (if the script is hopefully running in Windows10 bash) otherwise I will wait for the RC3 to test it again.

**Comment by aklink** [comment]
@pomadchin Thanks. **1.1.0-RC3** solves HadoopLayerReader.read **geotrellis.spark.io.package$LayerNotFoundError** bug.

**Comment by pomadchin** [comment]
@aklink Great to hear! Thanks for this bug report.
