### ISSUE TITLE
Not all RDDReaders are serializable 

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2114]
For example [this codec](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala#L65) should be wrapped in kryo wrapper.

All Readers / Writers should be double checked.

**Comment by lossyrob** [comment]
@pomadchin I'm confused - there was a commit that specifically removed the Kryo wrappers (https://github.com/locationtech/geotrellis/commit/660e8af691c10b8cb6b434ff5a4c27fd130614a1). @echeipesh any insight?

**Comment by pomadchin** [comment]
@lossyrob i can double check it.

**Comment by pomadchin** [comment]
That was my fault, smth else was causing serialization issue.
