### ISSUE TITLE
MulitbandTiles Cannot Perform Local Operations

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2162]
As it currently stands `MultibandTile`s cannot perform any focal operations in GeoTrellis. Whereas `Tile`s can.

For example:
```scala

// this will not work
val plusOne = multibandTile + 1

// this is the workaround
val plusOne = multibandTile.bands.map { x => x + 1}
```

While the work around isn't difficult, it might be worth implementing these operations for `MultibandTile`s regardless.

**Comment by echeipesh** [comment]
Duplicate of https://github.com/locationtech/geotrellis/issues/1789
