### ISSUE TITLE
Query catalog by projected geometry

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2165]
Current layer query mechanism assumes that any geometry passed in the query filter will be in correct CRS. This may or may not be the case.

Actually during layer query evaluation we have enough information to detect and correct this error.
We don't have a type for projected geometry but it seems safe to capture that in a `(Geometry, CRS)` type.

This will require new instance of `LayerFilter`:
```scala
implicit def forProjectedPolygon[K: SpatialComponent: Boundable, M: GetComponent[?, LayoutDefinition] :GetComponent[?, CRS]]: LayerFilter[K, Intersects.type, (Polygon, CRS), M] = ???

implicit def forProjectedMultiPolygon[K: SpatialComponent: Boundable, M: GetComponent[?, LayoutDefinition] :GetComponent[?, CRS]]: LayerFilter[K, Intersects.type, (MultiPolygon, CRS), M] = ???
```

Note the requirement that the metadata `M` have the `CRS` component.

The call would look like:
```scala
catalog.query(LayerId("name", 3)).where(Intersects(polygon -> CRS.fromEpsgCode(4326))).result
```

Adding this would take care of pretty common and frustrating error.

**Comment by bentito** [comment]
I'm going to see if I can work on this. I will just jump in and try to orient myself from this issue outwards. If I get stuck I might post here with what I'm stuck on, or reach out with questions. I'm completely new to the geotrellis codebase.

**Comment by fosskers** [comment]
It would be nice if CRS were baked into the Geometries / Extents / Tiles as type parameters. Then any attempt to do an operating on things that disagreed on CRS would be caught by the compiler.

**Comment by bentito** [comment]
Sorry. I'll have to give up on trying to take this one on. Summer classes have started for me again. I did get through the introductory material and I'm interested in trying to help out with coding when I have time again in the future.
