### ISSUE TITLE
Rasterize RDD[Geometry] or RDD[Feature[G,D]]

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2168]
Given RDD of vector data we need to be able to turn it to RDD of tiled raster. I imagine API like this:

```scala

RasterizeRDD {
  import geotrellis.raster.rasterize.Options

  /** Rasterize geometries using a constant value */
  def fromGeometry[T: Numeric](
    rdd: RDD[Geometry],
    layout: LayoutDefinition,
    ct: CellType,
    value: T = 1,
    options: Options = Options.DEFAULT
  ): RDD[(SpatialKey, Tile)] with Metadata[LayoutDefinition]

  /** Rasterize features using their property as tuple of cell value and ZOrder */
  def fromFeature[T: Numeric](
    rdd: RDD[Feature[Geometry, (T, Int)]],
    layout: LayoutDefinition,
    ct: CellType,
    options: Options = Options.DEFAULT
  ): RDD[(SpatialKey, Tile)] with Metadata[LayoutDefinition]
}
```

Calling out that in `Feature` case the payload is actually `(T, Int)`, with the in being the ZOrder. IMO it doesn't make sense to rasterize geometries with possible differences in cell values without defining some priority of which needs to go on top. As such there is no allowance for `RDD[Feature[Geometry, T]]` case.

**Comment by aklink** [comment]
I have made a suggestion in https://github.com/locationtech/geotrellis/pull/2266 how to modify RasterizeRDD to Support RDD[Feature[G,D]] called **RasterizeFeaturesRDD**
