### ISSUE TITLE
Partition GeoTiff reading by GeoTiff segment layout

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2173]
Currently in `S3GeoTiffRDD` and `HadoopGeoTiffRDD` when performing a windowed read the windows will be generated from (0,0) pixel offset to [cover the whole geotiff](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala#L159) without the regard for its [layout](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala): 

This will likely result in multiple read requests for the same segments of GeoTiff which is suboptimal. Instead given that we have the GeoTiff header available we should consider the segment layout and plan reads such that windows will be no larger than `maxTileSize` but intersect only single segment.

~Likely this can be carried further to [`GeoTiffTile`](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala#L537) where `.crop(windows: Seq[GridBounds])` would do similar thing.~

Edit: Improvements to crop are happening here https://github.com/locationtech/geotrellis/pull/2115 and should not be considered part of this issue.

- [x] S3GeoTiffRDD: https://github.com/locationtech/geotrellis/pull/2296
- [x] HadoopGeoTiffRDD https://github.com/locationtech/geotrellis/pull/2402

**Comment by jamesmcclain** [comment]
> ... [cover the whole geotiff](https://github.com/locationtech/geotrellis/blob/e50d43d4c90771d2154bb3834ad04be1e11c9e0f/s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala#L159) ...
