### ISSUE TITLE
spark-etl load data into accumulo failure 

### ISSUE THREAD

**Issue by gustao** [locationtech/geotrellis#2184]
When I learded to use this tool to load data into accumulo in
https://github.com/locationtech/geotrellis/blob/master/docs/guide/etl.rst
I met a problem: 

> INFO SpatialAccumuloOutput: Using Accumulo write strategy: HdfsWriteStrategy(/geotrellis-ingest)
> .......
> Caused by: org.apache.accumulo.core.client.AccumuloException: file:/geotrellis-ingest/af71987e-2c5e-452d-a293-ee44a7e1f440-Lu8lhMe7Yc: java.io.IOException: file:/geotrellis-ingest/af71987e-2c5e-452d-a293-ee44a7e1f440-Lu8lhMe7Yc is not in a volume configured for Accumulo
> 

Then I saw：

>  Accumulo Output
> Accumulo output module has two write strategies:
> hdfs strategy uses Accumulo bulk import
> socket strategy uses Accumulo BatchWriter
> When using hdfs strategy ingestPath argument will be used as the temporary directory where records will be written for use by Accumulo bulk import. This directory should ideally be an HDFS path.

So I modified the code 

> accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala:39

form
`def DEFAULT = HdfsWriteStrategy("/geotrellis-ingest")   `
to
`def DEFAULT = HdfsWriteStrategy("hdfs://host1:9000/geotrellis-ingest")`

Then spark-etl run ok .
it`s a bug？ I think you should give user an option in backend-profiles.json or  let program read instance.volumes in $ACCUMULO_HOME/conf/accumulo-site.xml automatically.

**Comment by pomadchin** [comment]
Hi @gustao, thx for your feedback! 

Looks like you're missing a part of your configuration (`$HADOOP_CONF/core-site.xml` and it's not in the `Apache Spark` classpath) or 
an incorrect `instance.volumes` value in `$ACCUMULO_HOME/conf/accumulo-site.xml`; can you throw here example of settings here? (`instance.volumes` and `fs.defaultFS`).

However, it's not a bug (just a small misconfiguration), but you are correct, `HdfsWriteStrategy` volume definitely should be an additional setting.

**Comment by pomadchin** [comment]
Related to https://github.com/locationtech/geotrellis/issues/1767

**Comment by gustao** [comment]
```hadoop/etc
    <name>fs.defaultFS</name>
    <value>hdfs://host1:9000</value>

    <name>instance.volumes</name>
    <value>hdfs://host1:9000/geotrellis-ingest0507_1</value>
```
host1 is 127.0.0.1 ，I use a stand-alone environment instead of a distributed one
I am a student learing this for homework . So I don't know much about this ...

**Comment by pomadchin** [comment]
Ok, looks fine to me. 
Check `$SPARK_HOME/conf/spark-env.sh`, there is a special var `$HADOOP_CONF_DIR`, which is commented out by default. Have a look into it:

```bash
# - HADOOP_CONF_DIR, to point Spark towards Hadoop configuration files
```

It should point into `Hadoop` conf dir, to make the default path `/` available in the `Spark` context.

Let me know if it helped you or not!

**Comment by gustao** [comment]
thx for your help , you are right ,when I installed the spark, I did`t edit the $SPARK_HJOME/conf/spark-env.sh  at all.
I just download jdk,scala,source of spakr and edited /etc/profile ......
I tried to  edit $SPARK_HJOME/conf/spark-env.sh   just now and some new misconfigurations appeared..... 
So I decided to maintain the status quo .......HAHAHA
You are so helpful,thank you very much! 
May you be happy ~
