### ISSUE TITLE
ETL Fails Silently with User-Defined Layout

### ISSUE THREAD

**Issue by nandanrao** [locationtech/geotrellis#2215]
Example repo to replicate: 

https://github.com/nandanrao/etl-example

With a user-defined layout seen in [etl/output.json](https://github.com/nandanrao/etl-example/blob/master/etl/output.json), the job exits without errors, but leaves the following empty folder structure: 

```
├── _attributes
│   ├── nl_2013___0___metadata.json
│   └── pop_2015___0___metadata.json
├── nl_2013
│   └── 0
│       └── _SUCCESS
└── pop_2015
    └── 0
        └── _SUCCESS
```

I expected to either have some data in the folders, or to receive an error.

**Comment by pomadchin** [comment]
Hi @nandanrao, thx for that report!

**Comment by pomadchin** [comment]
This module is deprecated and wontfix: https://github.com/geotrellis/spark-etl
