### ISSUE TITLE
Documentation Site 404s

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2225]
The links highlighted below 404:

<img width="962" alt="screen shot 2017-06-02 at 9 06 12 am" src="https://cloud.githubusercontent.com/assets/131013/26726913/d09d998c-4772-11e7-8bb4-12c17639d36f.png">

**Comment by metasim** [comment]
This appears to be OBE.

**Comment by rossbernet** [comment]
I had to look up OBE. And am quite confident I know what you mean, but came across a few other [alternative definitions](https://en.wiktionary.org/wiki/OBE) in the process that are fun
