### ISSUE TITLE
Rasterize RDD[Geometries] to RDD[Tile]

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#2228]
Rasterize Vectors, e.g. RDD[Geometry] to RDD[Tile] where the cell values will dependent of feature attributes for a specific zoom level e.g. 10. 

A nice work around can be found here for ArcGIS
http://pro.arcgis.com/en/pro-app/tool-reference/conversion/feature-to-raster.htm 

And for GDAL here http://www.gdal.org/gdal_rasterize.html

**Comment by pomadchin** [comment]
Hi @Charmatzis, can you give more information about what are you trying to do and some pseudo-code sample of what you want to achieve? Our [rasterizer](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala) doesn't fit your case?

**Comment by Charmatzis** [comment]
Well, I was thinking as a use case something like that:
Inputs: 1. RDD[Feature[Geometry, SomeClass]]]
            2. Field of SomeClass to be set in cells. 
            3.  CRS (EPSG)
            4. CellSize (in units of CRS
Processing: RDD[Feature[Geometry, SomeClass]]].map{x=>
                         Rasterizer.rasterizeWithValue(x.geom, x.geom.extent, x.data."some_field_for_cells_value")
.....
val result = Tile   
result}

Output: RDD[Tile]

**Comment by echeipesh** [comment]
I wrote up an issue for a possible interface here: https://github.com/locationtech/geotrellis/issues/2168
Would that interface satisfy the requirement?

The one issue that seems to be ambiguous is the z-order of overlapping geometries.
