### ISSUE TITLE
S3 reader doesn't seem to take AWS_DEFAULT_PROFILE into consideration

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2271]
I had an instance where my `AWS_DEFAULT_PROFILE` was set correctly (I could use the aws cli against the account), and I had no environment var keys set (`AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`). I got permission denied when trying to read a layer through the `S3CollectionLayerReader.query` method.

Once I set `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` to the account's keys, it worked.

**Comment by pomadchin** [comment]
`AWS_DEFAULT_PROFILE` is used for AWS CLI and `AWS_PROFILE` is used for `aws-jdk`: https://github.com/aws/aws-sdk-java/issues/451

**Comment by lossyrob** [comment]
Closing this, this was more about me using a deprecated environment var and less a bug.
