### ISSUE TITLE
Consider making appropriate `TilerMethods` functions return a `ContextRDD`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2278]
[`tileToLayout`](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/tiling/TilerMethods.scala#L50) and friends currently return `RDD[(K,V)]`. Because `TileLayerMetadata` is required to call these methods, and because the result is constructed in that metadata context, there's an argument for returning `RDD[(K2, V)] with Metadata[TileLayerMetadata[K]]` instead.

Currently, operations often take this form:
```
val scene: RDD[(ProjectedExtent, Tile)] = ???
val metadata: TileLayerMetadata[SpatialKey] = ???
val tiled: RDD[(SpatialKey, Tile)] = scene.tileToLayout(metadata)
val tileLayerRDD: TileLayerRDD[SpatialKey] = ContextRDD(tiled, metadata)
```

I'm arguing that the last step should happen automatically where appropriate.

---

TODOs:

* [ ] identify candidate functions relating to tiling
* [ ] identify candidate functions relating to reprojecting
* [ ] identify candidate functions relating to pyramiding
* [ ] evaluate impact on API; is it breaking?

**Comment by pomadchin** [comment]
@metasim I agree, we need to return the most complete type, to return a super type is always possible

**Comment by metasim** [comment]
@pomadchin @rossbernet et al: should/could this be something considered for 2.0?

**Comment by echeipesh** [comment]
👍 I think in addition there could be a little ergonomics added to the API for tile/reproject/pyramid set of functions.
