### ISSUE TITLE
Wrong SpatialKeys with Bresenham line drawing algorithm

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#2285]
Hi, I am working in Lines Rasterazation and I have noticed that you use "Bresenham line drawing algorithm" https://github.com/locationtech/geotrellis/blob/c262be5cadd03908d91887d45bc53fcf31ae4a74/raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala#L222 

Working with that, I have noticed that in the results there were missing some SpatialKeys, that was the result of working with "Bresenham line drawing algorithm".
As I have read here (https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm ) and here (https://www.cs.virginia.edu/luther/blog/posts/492.html ) I believe that there should be some thoughts on change the algorithms and not losing SpatialKeys.

**Comment by rossbernet** [comment]
Thanks for pointing this out. Do you have thoughts and/or interest about specifically how to do that?

**Comment by echeipesh** [comment]
This has been resolved with https://github.com/locationtech/geotrellis/pull/2438 and previously https://github.com/locationtech/geotrellis/pull/2336
