### ISSUE TITLE
Time-series Polygonal Summary operation over spatiotemporal raster layers

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2287]
Currently we have a way to take a `TileLayerRDD[SpatialKey]`, do a polygonal summary over it e.g. `layer.polygonalMax(polygon)`, and get a single answer.

This feature would enable a `TileLayerRDD[SpaceTimeKey]` to do a similar polygonal summary _per time period_, and return a `Map[ZonedDateTime, R]` where `R` is the result type.

For example,
```scala
val layer: TileLayerRDD[SpaceTimeKey] = ???
val polygon: Polygon = ??? // or multipolygon, anything the current summaries support
val result: Map[ZonedDateTime, Histogram[Double]] = layer.polygonalHistogram(polygon) // or any other currently supported polygonal summary operation
```

**Comment by jamesmcclain** [comment]
I will start on this.  I can be handed off as appropriate if situation changes.
