### ISSUE TITLE
Remove `.collectMetadata` from TileRDDReproject

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2294]
See the `collectMetadata` calls here:

https://github.com/locationtech/geotrellis/blob/a0280ebd51e3bec1a765c623138684e8a0fcd966/spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala#L123-L138

Ideally we'd like to derive the new, reprojected metadata from the old metadata, instead of having to we create a `TileLayerMetadata[K] => TileLayerMetadata[K]` function that takes in a target CRS and produces the new metadata directly without having to perform a Spark action. This function would probably belong on TileLayerMetadata, or be an implicit method that hangs off of any `M` that has the necessary components (LayoutDefinition, Bounds, Extent).

The source RDD metadata exists here: https://github.com/locationtech/geotrellis/blob/a0280ebd51e3bec1a765c623138684e8a0fcd966/spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala#L60, so we have access to it.

We also have the ability to reproject GridExtents (like the LayoutDefinition of the source metadata): https://github.com/locationtech/geotrellis/blob/a0280ebd51e3bec1a765c623138684e8a0fcd966/raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala#L55

The one concern here is the `cellSize`: If we reproject the grid extent, we get a cell size that is uniform over the entire bounds of the GridExtent. In the `collectMetadata` approach, we are iterating through each individual reprojected RasterExtent for each tile, which is locally reprojected and therefore can have varying cellSizes. The `collectMetadata` will choose the smallest cell size for the new metadata, which is fed into the eventual `tileToLayout` call, so that if there is a portion of the GridExtent that has significantly smaller resolution on reproject than would be calculated for the overall grid extent, that resolution is not degraded by taking some overall cellSize.

**Comment by lossyrob** [comment]
@jamesmcclain

**Comment by lossyrob** [comment]
@echeipesh should we close this?

**Comment by echeipesh** [comment]
Yup, resolved by https://github.com/locationtech/geotrellis/pull/2425
