### ISSUE TITLE
Implement case class-like `toString` for derivations of `CRS`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2295]
Most GT data types are case classes, which have a user friendly `toString` implementation. `CRS` is a trait, and is instantiated as either an anonymous class or an object.  This results in the toString implementations having forms like `geotrellis.proj4.CRS$$anon$1@377bc89f`.

It would be nice to have more user-friendly `toString` implementations.

**Comment by metasim** [comment]
I'm happy to do a PR for this ticket if others are agreeable to it in principle.

**Comment by CloudNiner** [comment]
@echeipesh @metasim It looks like this was added in https://github.com/locationtech/geotrellis/pull/2337. Can this be closed?

**Comment by pomadchin** [comment]
It is closed in #2337 :+1: good catch.
