### ISSUE TITLE
Issue with PipelineConstructor type

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2298]
In some code I had:

```scala
      val pipeline =
        config.crs match {
          case Some(name) =>
            Read("") ~ ReprojectionFilter("EPSG:32615")
          case None => Read("")
        }
```

which would not work in the case that `config.crs` was defined. I would get PDAL read errors, saying it could not find a reader for the file.

Once I specified the type explicitly:

```scala
      val pipeline: PipelineConstructor =
        config.crs match {
          case Some(name) =>
            Read("") ~ ReprojectionFilter("EPSG:32615")
          case None => Read("")
        }
```

The issue went away.

**Comment by pomadchin** [comment]
Well, it's Scala type system thing. There is an implicit evidence that can convert `PipelineExpr` (`Read` in our case) into `PipelineConstructor` which is in fact just a `List[PipelineExpr]`. Without specifying an explicit type it infers `Serializable` type (as an LB for case class and List types). You can wrap Read into List, and it would work.

```scala
      val pipeline: PipelineConstructor =
        config.crs match {
          case Some(name) =>
            Read("") ~ ReprojectionFilter("EPSG:32615")
          case None => Read("") :: Nil
        }
```
