### ISSUE TITLE
AWS SDK 2.0 for Java

### ISSUE THREAD

**Issue by hectcastro** [locationtech/geotrellis#2302]
A developer preview of the AWS SDK for Java has been made available with a number of internal changes that could help improve performance of the GeoTrellis Amazon S3 backend: 

- Non-blocking I/O
- Pluggable HTTP client
- HTTP client sharing

See: https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

**Comment by CloudNiner** [comment]
An upgrade to the AWS V2 SDK would also resolve fallout from https://github.com/aws/aws-sdk-java/issues/1707#issuecomment-409342847
