### ISSUE TITLE
Add ability to disable or override attribute store caching

### ISSUE THREAD

**Issue by hectcastro** [locationtech/geotrellis#2305]
`AttributeStore` currently contains a naive `HashMap` cache that only really gets surfaced when browsing the project source code. If a cache for the `AttributeStore` is maintained within GeoTrellis, then I think it would be better to surface settings for it when an `AttributeStore` is created (toggle on/off, size, TTLs, etc.).

An alternative would be to remove the HashMap cache altogether. An intermediate solution that preserves backwards compatibility would be to add an option to disable it but keep it enabled by default until the next major release.

See: https://github.com/locationtech/geotrellis/blob/v1.1.1/spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala#L24

**Comment by notthatbreezy** [comment]
Raster Foundry is going to be able to dedicate some resources to work on this in the next two weeks

**Comment by hectcastro** [comment]
I haven't seen any indication that this is a desirable contribution from the GeoTrellis perspective. Would be good to see that before any work begins. Also, is the expected approach that internal caching would be removed in its entirety, or that a variety of settings would be surfaced to help manage the internal cache?

**Comment by lossyrob** [comment]
@hectcastro my understanding is that there was some verbal communication around this issue, and there was an indication that we wanted to solve this problem. There's been a number of issues around caching that we've had discussions on, and I think the surface area of this was covered in other pre-existing issues. See discussions in #2223, #2276, #1777.

This is actually solved in https://github.com/locationtech/geotrellis/pull/2390 and will be released with 1.2.

**Comment by hectcastro** [comment]
Some good discussion in https://github.com/locationtech/geotrellis/pull/2223.

I'd like to add that issues around the internal `AttributeStore` cache were surfaced in troubleshooting issues with our attempt to implement a [`PostgresAttributeStore`](https://github.com/raster-foundry/raster-foundry/blob/0.20.2/app-backend/common/src/main/scala/geotrellis/spark/io/postgres/PostgresAttributeStore.scala). As we tried to layer in our own caching layer, we noticed inconsistent return values, which were tied to the internal `AttributeStore` cache behavior.

I realize that Scaffine is an upgrade to `HashMap` in many ways, but still think that it would be valuable to have one flag to enable/disable the internal cache (defaulting it to enabled if that's desired to preserve backwards compatibility) vs. doing something like `expirationMinutes = 0`.

**Comment by lossyrob** [comment]
Sounds reasonable, reopened, let's use this issue to track that change.

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lossyrob** [comment]
Sounds reasonable, reopened, let's use this issue to track that change.

**Comment by echeipesh** [comment]
Thats a good point regarding disabling the cache completely, thats missing from #2390 .
It seems very coarse grained, to disable all attribute store caching on application level, but I can not think about better way to preserve compatibility for 1.2 release.
