### ISSUE TITLE
Rethink how we are increasing partitions based on resampling in reproject

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2315]
https://github.com/locationtech/geotrellis/commit/a0280ebd51e3bec1a765c623138684e8a0fcd966

When I ran an ingest on a reasonable raster, not intentionally upsampling, I got a very large number of partitions and the ingest failed. When I backed out the above changes it succeeded.

<img width="1664" alt="screen shot 2017-08-06 at 4 07 53 am" src="https://user-images.githubusercontent.com/2320142/29001915-fcda198e-7a63-11e7-9cac-4529fcf7a35f.png">

**Comment by pomadchin** [comment]
I think it can be related to RF ingests, where on a small raster ingest can take more than an hour instead of 2 minutes and shuffle 1TB of data.

**Comment by lossyrob** [comment]
Just to note, I had to delete the following lines to make this ingest work:

```diff
-    // Layout change may imply upsampling, creating more tiles. If so compensate by creating more partitions
-    val part: Option[Partitioner] =
-      for {
-        sourceBounds <- metadata.bounds.toOption
-        targetBounds <- newMetadata.bounds.toOption
-        sizeRatio = targetBounds.toGridBounds.size.toDouble / sourceBounds.toGridBounds.size.toDouble
-        if sizeRatio > 1.5
-      } yield {
-        val newPartitionCount = (bufferedTiles.partitions.length * sizeRatio).toInt
-        logger.info(s"Layout change grows potential number of tiles by $sizeRatio times, resizing to $newPartitionCount partitions.")
-        new HashPartitioner(partitions = newPartitionCount )
-      }
-
-    val tiled = reprojectedTiles.tileToLayout(newMetadata,
-      Tiler.Options(resampleMethod = tilerResampleMethod,
-        partitioner = if (part.isDefined) part else bufferedTiles.partitioner ))
```

**Comment by lossyrob** [comment]
I believe this is the Ingest I was using when hitting this issue: https://github.com/lossyrob/foss4g-2017-geopyspark-workshop/blob/master/ingest/src/main/scala/IngestCDL.scala
