### ISSUE TITLE
Add filter capability to GeoTiffRDDs

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2328]
We should be able to filter the GeoTiff(s) by a polygon. Because we can do this from TiffTag metadata that can be read quickly, this would allow narrow ingests of large datasets, e.g. if I only wanted to pull a state-level amount of data from a single large GeoTiff like the Crop Data Layer.

**Comment by jamesmcclain** [comment]
How does this relate to prospective COG layers?  That is, would COG layers automatically provide this functionality?

**Comment by fosskers** [comment]
Solved by #2409
