### ISSUE TITLE
Add overview support to GeoTiff reader and writer

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2340]
This issue will track the progress of overview support in GeoTrellis's GeoTiff support.

Related to #2284

**Comment by lossyrob** [comment]
Overviews in GeoTiffs are really just an “Image File Directory” (IFD) as described in the TIFF6 spec. Currently we only read the first IFD, and ignore any others if they are present.

As described in this diagram from the spec:

<img width="502" alt="screen shot 2017-08-21 at 5 35 24 pm" src="https://user-images.githubusercontent.com/2320142/29539274-2e37e72e-8697-11e7-924e-7fb9d92337a8.png">

The header points to the first IFD; each IFD starts with the number of tags in that IFD. That count of tags (or Directory Entries) are followed by the 4-byte (or in BigTiff 8-byte) offset to the next IFD.

As described [in the COG spec](https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF), the first IFD is of the full resolution image. What follows is not yet any image data; that IFD only contains the byte offsets to the image data, which are at the end of the file. The next IDF represents the overview that is the next highest resolution IFD, etc. After the last IFD, which is the "lowest zoom level" overview, the image data begins. The COG spec suggests that the lowest resolution overview data be read first, so that in one initial object store byte range read we can get not only every IFD but also the first couple overview images; that way if you want to show low resolution versions of the GeoTiff you only have to read once instead of twice (once for the IDF data, and once for the byte range of the image data as described inside the IFD).

**Comment by pomadchin** [comment]
Overviews may contain not all tags. Basically only first IFD contains all tags and overviews may not have some important information like CRS. We need to take it into account and to handle it correct during reads and writes.
