### ISSUE TITLE
JMH for Benchmarking

### ISSUE THREAD

**Issue by fosskers** [locationtech/geotrellis#2348]
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
</head>
<body>

*This is a formalization of a conversation had earlier in the week.*

<div id="content">
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#orgd7732fa">1. Scaliper</a></li>
<li><a href="#org5a40b18">2. JMH w/ SBT Plugin</a>
<ul>
<li><a href="#orgd7cdd08">2.1. Defining Benchmarks</a></li>
<li><a href="#org96eabbc">2.2. Running Benchmarks</a></li>
<li><a href="#org69c02bd">2.3. Project Pulses</a></li>
</ul>
</li>
<li><a href="#orgbad0f43">3. Proposal</a></li>
</ul>
</div>
</div>
<div id="outline-container-orgd7732fa" class="outline-2">
<h2 id="orgd7732fa"><span class="section-number-2">1</span> Scaliper</h2>
<div class="outline-text-2" id="text-1">
<p>
We're a data science library, so benchmarking is obviously very important for us.
Up until now we're been using Rob's <a href="https://github.com/azavea/scaliper">scaliper</a> library for this. It was originally
written to fill a void in Scala benchmarking, since Rob had had bad experiences
with ScalaMetre in the past. Scaliper is a great tool that gives us consistent results.
However, what bars it from continued use is the fact that it has no maintainance cycle.
Given that we are already stretched in many directions as a team, this may be one
aspect of our work that we can "off-shore".
</p>
</div>
</div>

<div id="outline-container-org5a40b18" class="outline-2">
<h2 id="org5a40b18"><span class="section-number-2">2</span> JMH w/ SBT Plugin</h2>
<div class="outline-text-2" id="text-2">
<p>
<a href="http://openjdk.java.net/projects/code-tools/jmh/">JMH</a> is a benchmarking tool from the OpenJDK people. It features:
</p>

<ul class="org-ul">
<li>Good control over JVM forking / thread counts</li>
<li>Warm-up iterations</li>
<li>Ability to control output time units (nano, micro, milli)</li>
<li>Ability to configure iteration counts</li>
<li>Various benchmarking modes: "throughput" for ops-per-second, avg time per op, etc.</li>
<li>"CPU noise" to simulate a real, busy system</li>
<li>Minimal boilerplate for defining benchmarks</li>
</ul>

<p>
With the associated <a href="https://github.com/ktoso/sbt-jmh">SBT plugin</a>, we gain a light-weight way to define entire benchmarking
suites. The recommended approach is to define a subproject that depends on the lib it's
benchmarking:
</p>

```scala
/* The actual library */
lazy val lib = project.in(file(".")).settings(common)

lazy val bench = project.in(file("bench")).settings(common).dependsOn(lib).enablePlugins(JmhPlugin)
```

<p>
This could be moved directly into GeoTrellis, which would save us effort by avoiding the
local publishing / git dance required to use <code>geotrellis-benchmark</code>. The advantage of
a separate <code>geotrellis-benchmark</code> repository is the ability to save older implementations
in order to more reliably detect performance regressions.
</p>
</div>

<div id="outline-container-orgd7cdd08" class="outline-3">
<h3 id="orgd7cdd08"><span class="section-number-3">2.1</span> Defining Benchmarks</h3>
<div class="outline-text-3" id="text-2-1">
<p>
In a separate subproject, in some <code>Bench</code> class, you write a method containing the code
you want to benchmark. This can also just call out to a real method you've written
elsewhere:
</p>

```scala
  import java.util.concurrent.TimeUnit
  import org.openjdk.jmh.annotations._

  @BenchmarkMode(Array(Mode.AverageTime))
  @OutputTimeUnit(TimeUnit.NANOSECONDS)
  class Bench {
    /* A single call to `get`, which fetches the current "stateful" value */
    @Benchmark
    def oneGetCats: (Int, Int) = Kitties.oneGet

    @Benchmark
    def oneGetScalaz: (Int, Int) = Zed.oneGet
  }
```

<p>
The annotations are for Java code-gen that occurs at benchmark runtime.
</p>
</div>
</div>

<div id="outline-container-org96eabbc" class="outline-3">
<h3 id="org96eabbc"><span class="section-number-3">2.2</span> Running Benchmarks</h3>
<div class="outline-text-3" id="text-2-2">
<p>
From sbt:
</p>

<div class="org-src-container">
<pre class="src src-shell">&gt; project bench
&gt; jmh:run -t <span style="color: #a45bad;">1</span> -f <span style="color: #a45bad;">1</span> -wi <span style="color: #a45bad;">10</span> -i <span style="color: #a45bad;">10</span> .*Bench.*
</pre>
</div>

<p>
which means: 1 thread, 1 forked JVM, 10 warm-up iterations, 10 real iterations.
</p>
</div>
</div>

<div id="outline-container-org69c02bd" class="outline-3">
<h3 id="org69c02bd"><span class="section-number-3">2.3</span> Project Pulses</h3>
<div class="outline-text-3" id="text-2-3">
<p>
JMH sees <a href="http://hg.openjdk.java.net/code-tools/jmh/">monthly commits</a>, and the maintainer of the sbt plugin is Konrad Malawski,
who works on Akka for Lightbend. The project is available for the latest versions
of both JMH and SBT (even 1.0). It was recommended to us by <a href="http://degoes.net/">John De Goes</a>
(CTO at SlamData, FP guy, organizer of LambdaConf), and is also used by Lightbend
to benchmark the Scala compiler.
</p>

<p>
Scaliper's last commit was in late 2015, has no published Scala 2.11 jar,
and does not compile with Scala 2.12.
</p>
</div>
</div>
</div>

<div id="outline-container-orgbad0f43" class="outline-2">
<h2 id="orgbad0f43"><span class="section-number-2">3</span> Proposal</h2>
<div class="outline-text-2" id="text-3">
<p>
There may or may not be value in porting our old benchmarking code to use <code>jmh-sbt</code>.
I propose a new <code>bench</code> subproject within the GeoTrellis repo that depends on
the other subprojects that do meaningful calculation work (yes <code>vector</code>, yes <code>raster</code>, no <code>s3</code>, etc.).
Any new benchmark can be written into <code>bench</code> in the manner described above. This should allow
for fast turnaround when benchmarking minor changes. The <code>bench</code> subproject shouldn't be published
to maven, etc.
</p>

<ul class="org-ul">
<li><a href="https://github.com/fosskers/scalaz-vs-cats/blob/master/scala/build.sbt">Config Example</a></li>
<li><a href="https://github.com/fosskers/scalaz-vs-cats/blob/master/scala/bench/src/main/scala/svc/Bench.scala">Benchmark Examples</a></li>
</ul>
</div>
</div>
</div>
</div>
</body>
</html>

**Comment by pomadchin** [comment]
A good idea would be to test it by rewriting https://github.com/geotrellis/geotrellis-benchmark and by comparing results to scaliper

**Comment by fosskers** [comment]
I've gotten a bit more practice writing the JMH benchmarks, and porting the existing ones from `geotrellis-benchmark` seems like less work than I thought. 

If we did port them and compare, how do we know which one is "right"? One could argue it doesn't matter, because:

- we always take JVM benchmark results with a grain of salt
- relative timings are more important than absolute ones

In my experience, both scaliper and JMH give consistent results, with scaliper occasionally "staying warm" from run to run, which affects results.

**Comment by lossyrob** [comment]
If all things are equal or slightly in JMH's favor, I would say we shift to the community supported thing. I wrote scaliper with the hopes that it would become a useful tool, and it did to some regard - I hadn't found something that did what it did. But that was years ago; if there's something that is a more widely supported and maintained thing, we should just move off scaliper and move to that.

**Comment by metasim** [comment]
I'd be interested in prototyping a potential integration into the build, using JMH + sbt plugin. But don't want to take the fun away from anyone :-)

**Comment by fosskers** [comment]
@metasim A first exploratory step would be to port some of the [benchmarks found here](https://github.com/geotrellis/geotrellis-benchmark/tree/master/geotrellis/src/test/scala/geotrellis). Questions to answer could be:

- Do the reported numbers differ between JMH and scaliper?
- What's the blessed way to setup Tile data, etc., that's used during each run of the benchmarks? Or should the resource creation time be included in the benchmark itself?

**Comment by metasim** [comment]
@fosskers Fulfilling the goals above will take some time, and I'm very much a novice in the art of benchmarking. My immediate goal is to provide some simple ability to test the `MergeQueue` behavior.

I have an initial build support defined here:

https://github.com/metasim/geotrellis/tree/jmh-prototype-2348/bench

**Comment by metasim** [comment]
@fosskers Are you satisfied with #2365 enough to close this?

**Comment by fosskers** [comment]
Yes!
