### ISSUE TITLE
Mask RDD should drop NoData tiles

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2361]
When masking an RDD of tiles, if a tile does not intersect geometry in any way it should be dropped from RDD rather than turning into NoData tile.

**Comment by metasim** [comment]
Is this simply a matter of automatically adding a `filter` for the user (or doing so implicitly through `flatMap`)? If so, I could help with this one.

**Comment by mteldridge** [comment]
I recently tested this as a workaround for #2358 and I think the filtering already happens.  See here:
 https://github.com/locationtech/geotrellis/blob/76032e3d6589114752c0a47bde9d750baae8c88e/spark/src/main/scala/geotrellis/spark/mask/Mask.scala#L109-L123

Notice that `None` is returned if the tile extent does not overlap the geom.

**Comment by echeipesh** [comment]
Thats clearly doing the thing. This was report from workshop prep IIRC. 
@lossyrob what was the context there, did something fall through the intersection logic or was it result of something else?

**Comment by lossyrob** [comment]
I can't recall an issue I was having with this. Seems like something that's already fixed, so closing.
