### ISSUE TITLE
Provide version of `ToSpatial` that blindly drops the temporal component.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2368]
The current version of `ToSpatial.apply` requires an `instant` parameter to specify which tiles in the temporal dimension should be selected before converting to a spatieal-only key.

https://github.com/locationtech/geotrellis/blob/f4fa8860cd96acbe5068330d7e4a6673c69cec68/spark/src/main/scala/geotrellis/spark/filter/ToSpatial.scala#L57

There are cases where the temporal component has either been filtered already, or one doesn't care about overlaps, and the the temporal component should be blindly dropped. Without this capability you might have to do a RDD scan to find the valid temporal values and then select one.

Related: #2367

**Comment by mteldridge** [comment]
I find myself following this pattern often:

```scala
val predicate = geotrellis.raster.mapalgebra.local.Mean
val spatial = rdd.map { case (stk, tile) => (stk.spatialKey, tile)  }
val merged = ContextRDD(spatial.groupByKey().mapValues(predicate(_)), 
                                             rdd.metadata.map[SpatialKey](_.spatialKey))
```
Where I map the key to `SpatialKey` and then apply a predicate function (e.g. `Mean`) to the resulting RDD and then stitch it up with (re-mapped) metadata into a new `ContextRDD`.  It would be nice if there were a

```scala
toSpatial(predicate: Traversable[Tile] => Tile) : RDD[K,V] with Metadata[M]
```
function that did all this transparently.
