### ISSUE TITLE
[Docs] List more versions of ScalaDocs on our site

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2377]
Right now we only have versions up to `0.10` listed, and then `latest`. We're missing `1.0` and `1.1`. Might be confusing to users as far as what versions are available.

https://geotrellis.io/documentation.html

**Comment by metasim** [comment]
I toyed with renaming "Latest" to "1.1", but since "1.1" doesn't explicitly exist in the scaladocs repo (only a `latest` directory), I thought that might lead to confusion at some point.

**Comment by echeipesh** [comment]
Pushed this forward by manually building and publishing 1.1: https://github.com/geotrellis/scaladocs/tree/gh-pages/1.1
http://geotrellis.github.io/scaladocs/1.1/index.html

**Comment by fosskers** [comment]
https://github.com/geotrellis/geotrellis-site/commit/9be9833cedb056c8e4e1e58dc7693d2b2a54f6b1

**Comment by fosskers** [comment]
I'm assuming we wait a few minutes for the docker containers to swap out via CI, then we'll see the changes live?
