### ISSUE TITLE
Fix Amazon S3 client deprecation warning

### ISSUE THREAD

**Issue by hectcastro** [locationtech/geotrellis#2399]
The `com.amazonaws.services.s3.AmazonS3Client` is deprecated, which leaves its suggested replacement, `AmazonS3ClientBuilder` (since SDK 1.11.84), incompatible with the `geotrellis.spark.io.s3.AmazonS3Client` constructor.

A suggestion for the desired outcome is to alter the type of the `s3client` argument so that it is compatible with the return value of `AmazonS3ClientBuilder`:

```scala
class AmazonS3Client(s3client: AWSAmazonS3Client) extends S3Client {
```

**Comment by echeipesh** [comment]
@hectcastro is `1.11.84` preferred version to bump to or just incidentally mentioned?

**Comment by hectcastro** [comment]
It was mentioned to help surface when `AmazonS3ClientBuilder` was introduced relative to the version we're using (1.11.143). It looks like 1.11.313 is the most current release for the 1.x branch of the SDK. 2.x of the SDK is still a developer preview.

**Comment by pomadchin** [comment]
@hectcastro can you take a look into the #2649?

**Comment by hectcastro** [comment]
Thanks for working on this. My goal is to review #2649 within the context of https://github.com/raster-foundry/raster-foundry/pull/2565.

Worried I won't be able to get to it this week though. I'll try to assign it to someone else if it looks like that is the case.

**Comment by hectcastro** [comment]
Thanks for the `GEOTRELLIS_VERSION_SUFFIX` tip. That was helpful.
