### ISSUE TITLE
Transitive dependency load of `geotrellis-spark-etl` is significant.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2406]
While this may be made irrelevant by #1767, I wanted to record the impact and results of a problem we just had to address relating to the transitive dependency load of `geotrellis-spark-etl`. 

We were running into a large number of evictions and assembly/shading problems causing bugs in our Zeppelin integration (e.g. Spark UI missing executors tab). It became clear that shading wasn't enough, and marking `geotrellis-spark-etl` as `intransitive()` caused problems in other code. Part of the problem is our fault, having some ETL dependent stuff mixed in with a bunch of non-ETL features. But after trying several things, the easiest fix was to add the following to our build:

```scala
excludeDependencies ++= Seq(
  "org.slf4j" % "slf4j-log4j12",
  "org.apache.hbase" % "hbase-server",
  "org.apache.hbase" % "hbase-client",
  "org.apache.hbase" % "hbase-common",
  "org.apache.hbase" % "hbase-hadoop-compat",
  "org.apache.accumulo" % "accumulo-core",
  "com.datastax.cassandra" % "cassandra-driver-core"
)
```
As result, our dependency load reduced in half:

**Before** &rarr; **After**

![img_3294](https://user-images.githubusercontent.com/131013/31176333-82901f42-a8e0-11e7-9c7d-aa0fce80b601.png)

`hbase-server` was about a third of that half.

So, if the "pipeline" code ends up being delayed for one reason or another, I suggest we investigate fixing the `geotrellis-spark-etl` architecture to not have such extensive runtime dependencies, either through the recent SPI feature @echeipesh wrote, or hack a solution using reflection that only instantiates drivers if they are available in the classpath (currently the ETL module instantiates entry-points to all the backends at startup). We plan to separate out our own ETL code at some point soon so this problem isn't an issue, but thought bringing it up here was important in case it affects other users.

**Comment by pomadchin** [comment]
Well my opinion is to stop etl project maintaining and either to mark it as deprecated or to do nothing with it, just not to include it into `2.0`.

**Comment by pomadchin** [comment]
It was partially addressed via `pipeline` project, though until we don't have SPI for Writers we can't exclude S3 dep. Closing it for now.
