### ISSUE TITLE
Switch direction of symlinks in top level of repo

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2428]
I thought that symlinking the CHANGELOG and CONTRIBUTING docs to the top level will increase visibility. However, GitHub doesn't render the documents that are symlinked. We should switch the direction of the symlink so the actual file lives in the top level, and the `docs/` versions are the links.

**Comment by jamesmcclain** [comment]
Resolved by https://github.com/locationtech/geotrellis/pull/2447

**Comment by fosskers** [comment]
Switching the direction of the symlinks breaks docs building. As an alternative I propose huge links (possibly badges) at the top of our README for the CHANGELOG and CONTRIBUTING doc.

**Comment by echeipesh** [comment]
The button and the spruced up `CHANGELOG` are both awesome, considering the spirit of this resolved.
