### ISSUE TITLE
Move to JTS 1.15

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2497]
JTS is now at [1.15 and published under locationtech](http://search.maven.org/#artifactdetails%7Corg.locationtech.jts%7Cjts%7C1.15.0%7Cpom)

This issue is for upgrading to the new version, changing all imports to the correct packages, and fixing up any API changes. Also hunting down any version conflicts that may cause binary compatibility issues with dependencies.

**Comment by echeipesh** [comment]
Looks like GeoWave, GeoTrellis, and GeoMesa will have to update to this version in lockstep at a later time. I'm wondering if there is a clever solution this this problem for connector projects like we have in GeoTrellis? @jnh5y @rfecher

**Comment by rfecher** [comment]
we're tied to geotools, and don't find the need to roll the dice with updating jts out of sync with geotools.  So we're on 1.14.0 - is there anything particular in 1.15 tha's driving this, or is it more just generally trying to keep up with the latest releases?

**Comment by rossbernet** [comment]
Thanks. Good to know. 
I think it's more of the latter - so, no urgency.

**Comment by jnh5y** [comment]
From my point of view, I'm hopeful that we can get the ball rolling on improvements where everyone'll be excited to move to a newer version of JTS.  For the cloud projects, I'm hoping that (even minor) performance enhancements will be worth it at scale.  For other projects, I get there's a desire to do geometric and topological operations on curves and 3D geometries.  As either of those move forward, it might be worth chatting about what'd need to be in JTS 2.0.

Other than that, there might be some room for an API shim layer if things every get totally outta whack:).

**Comment by pomadchin** [comment]
Resolved via https://github.com/locationtech/geotrellis/pull/2813
