### ISSUE TITLE
Move TestEnvironment from providing a SparkContext to providing a SparkSession

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2498]
In geotrellis.spark.testkit.TestEnvironment, we provide a SparkContext. We should provide a SparkSession; you can get a spark context from a spark session, but can't start a spark session after the spark context is already created, without some deprecated code.

**Comment by metasim** [comment]
This is how I handle it in a subclass to `TestEnvironment`. As you state, causes a deprecation warning, which I'd love to get rid of:

```scala
  override implicit def sc: SparkContext = { _sc.setLogLevel("ERROR"); _sc }

  lazy val sqlContext: SQLContext = {
    val ctx = SQLContext.getOrCreate(_sc).withRasterFrames
    ctx
  }

  implicit lazy val spark = sqlContext.sparkSession
```
