### ISSUE TITLE
Support  GeoTiff with 2 bits per sample

### ISSUE THREAD

**Issue by thedarkcder** [locationtech/geotrellis#2499]
When i try and process my GeoTiff I get an java.lang.UnsupportedOperationException: Unsupported band type (2, 1)

This is more than likely an issue with my GeoTiff and how it was created.  

Would love a feature where I can read a GeoTiff with any number of bits per sample.

**Comment by pomadchin** [comment]
Hi @thedarkcder i think it was still a useful issue, we don’t support TIFFs with bits per sample >1 & < 8 but it is indeed a nice feature. I’m wondering would our new GDAL support handle such tiffs? (in theory it can)
