### ISSUE TITLE
Layer Update mergeFunc does not guarantee order of params

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2524]
For a LayerWriter.update method, the mergeFunc does not specify the parameter order. This is because the parameter order is not guaranteed, for instance [this union and groupBy](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/file/FileRDDWriter.scala#L63-L64) doesn't  guarantee that for instance the incoming tile is the first param and the existing tile in is the second param. This makes the update merge method less useful, because having the context of what one is merging in, and what one is merging into, could very well be important.

**Comment by echeipesh** [comment]
Had a look at this while preparing: https://github.com/locationtech/geotrellis/pull/2663

The `++` scaladoc is:
> Returns a new vector containing the elements from the left hand operand followed by the elements from the right hand operand.

This ensures that the vector of existing `(K, V)` is going to be on the left, with `foldLeft` ensuring that they're merged in right order with expected argument position of lhs = existing, rhs = updating.
