### ISSUE TITLE
Overzooming has performance issues for many catalogs with many layers

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2529]
For Overzooming, https://github.com/locationtech/geotrellis/blob/9881296a667667c8a6a44758c012b4e985b1b574/spark/src/main/scala/geotrellis/spark/io/OverzoomingValueReader.scala#L36 will be very slow for catalogs with many, many layers. We should optimize this.

**Comment by echeipesh** [comment]
Not sure what could be done here without extending the `AttributeStore` interface, something along the lines of a set of functions that work only on layer name and expose zoom level information as a result. 

That actually sounds alright, common versions of AttributeStore can have prefix based implementations. Can't really make it into 1.2 though.
