### ISSUE TITLE
NPE in `FileLayerProvider` when scheme is missing from URI

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2551]
Happens here:

https://github.com/locationtech/geotrellis/blob/ec10694349c0e06fdf0af789579b966ed2af1f08/spark/src/main/scala/geotrellis/spark/io/file/FileLayerProvider.scala#L33

According to [this](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getScheme()), returning `null` is acceptable. 

Should probably check the other `LayerProvider`s for proper null handling. 

I'd argue that in the case of a missing scheme, `FileLayerProvider` should be the fallback selection.

**Comment by jbouffard** [comment]
I don't think that `FileLayerProvider` should be the fallback if the `scheme` is missing. Rather, I think it should just throw an exception saying it can't process the given `URI` since that's where the user wanted the data to be saved to.
