### ISSUE TITLE
Break `Projected` out of Slick

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2557]
`Projected` is currently the only way we have to associate a geometry with a projection. This lives in the Slick package and requires us to bring in all those dependencies. We should move `Projected` to vector so that using a library like, say, Doobie doesn't require bringing in Slick dependencies.

As evidence that this is a fine way of representing the relationship, note that JTS and `org.postgis` store projections *on* their geometries...

**Comment by fosskers** [comment]
> note that JTS and org.postgis store projections on their geometries

Binary ops on geoms/tiles/layers in incompatible projections should be a compile error, yeah.

**Comment by metasim** [comment]
An aside opinion: the closer we can stick to the JTS model of geometry, the easier it is to support interop with GeoMesa, RasterFrames, and other LocationTech projects. Having Scala wrappers ariound JTS like GT does is fine as long as the JTS semantics are maintained. @jnh5y particularly has been working hard to keep JTS moving ahead and evolving, so definitely reach out to him if you want the LocationTech perspective.

**Comment by metasim** [comment]
PS: The above is mostly a tangential comment; not insinuating that JTS semantics are in play here.
