### ISSUE TITLE
1.2 S3LayerUpdater prevents usage of custom AttributeStore

### ISSUE THREAD

**Issue by kthompson** [locationtech/geotrellis#2559]
While attempting to upgrade to geotrellis 1.2 we found that this line of code is preventing us from using the builtin S3LayerUpdater:
https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3LayerUpdater.scala#L51

**Comment by metasim** [comment]
@echeipesh Is there an architectural decision why generic AttributeStore isn't supported here? Any reason we can't rely only on the attribute store instance passed in by the user?

**Comment by pomadchin** [comment]
@metasim There were reasons before refactoring `LayerWriter` to support updates, it's possible just to use LayerWriter and to use `update` function out of it, but definitely `LayerUpdater` should be _updated_ too, to have a better interface.

**Comment by metasim** [comment]
@pomadchin Just to make sure we're following each other, the issue as I see it is that the [`S3LayerUpdater` constructor](https://github.com/locationtech/geotrellis/blob/4a718f2b64e02d2f05f0be6627fd76ec3b9b8d14/s3/src/main/scala/geotrellis/spark/io/s3/S3LayerUpdater.scala#L36) accepts an `AttributeStore` as a parameter, and then [immediately down casts it](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3LayerUpdater.scala#L51) to an `S3AttributeStore`. At its worst it's horrible API design; more likely it's cruft left over from the pre-refactor days. A fix would start with just deleting line 51.

**Comment by echeipesh** [comment]
Its a horrible API design and part of the reason that we moved the [`update`](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/LayerWriter.scala#L95-L99) function into `LayerWriter` with 1.2. 

As a result `LayerUpdater` is now [deprecated](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/LayerUpdater.scala#L55) with 1.2. I don't remember the context of changes that lead to this, seems like an oversight honestly.

@kthompson I expect that changing to use of `LayerWriter.update` would be a direct change on your end. Please let us know if that not true.

**Comment by kthompson** [comment]
I am not sure I completely understand the question but we have several customizations that make use of the existing APIs. We could just convert to using newer APIs but this will take us some time and we were hoping to be able to make some of these changes overtime. 

We were not expecting a minor version increment to cause breaking changes like this. For the moment we will probably need to put off upgrading until this is resolved or we have more time to put into upgrading.

**Comment by echeipesh** [comment]
Sorry, I'm with you now and see what you're saying now.

This change was in attempt to bring the new update functionality, which does the update on per-record bases rather than per RDD basis, to `LayerUpdater`.  I see how thats problem for you case though. Going to poke at this for a second to see if we can resolve that.

**Comment by echeipesh** [comment]
@kthompson @metasim It might have been the lack of imagination at the time that was the problem: 
https://github.com/echeipesh/geotrellis/commit/f3d44274c83b20bb1e8bade519c0563655807cf8

This replicates a bit of code from `S3LayerWriter` but overall not a big deal.

**Comment by echeipesh** [comment]
Back-ported to `1.2` branch with https://github.com/locationtech/geotrellis/commit/36ddc31c0eb7ec26993601843f72522e4d07b6fd 
 - SNAPSHOT will be updated to https://repo.locationtech.org/content/groups/snapshots/org/locationtech/geotrellis/geotrellis-s3_2.11/1.2.1-SNAPSHOT
