### ISSUE TITLE
GeoTools SimpleFeature ID handling

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2575]
Working with GeoTools is important for all kinds of library interop on the JVM. Unfortunately, we seem to be mishandling the conversion of GT features/geometries to GeoTools' `SimpleFeature`. The argument to `buildFeature` should almost certainly be exposed (rather than simply set to `"SimpleFeature"`) to allow users to set unique identifiers where necessary: https://github.com/locationtech/geotrellis/blob/a00c35b928e96083188d91734252d66574e3b4a7/geotools/src/main/scala/geotrellis/geotools/GeometryToSimpleFeature.scala#L77

As is evident from the relevant section of the GeoTools API, the `buildFeature` is supposed to take a feature ID: http://docs.geotools.org/latest/javadocs/org/geotools/feature/simple/SimpleFeatureBuilder.html#buildFeature-java.lang.String-

**Comment by moradology** [comment]
Another solution brought up by @Lknechtli which would obviate any need to deprecate the API here would be to automatically use the feature's data `id` key, if it has one.

**Comment by Lknechtli** [comment]
another related bug: the geometry field needs to be named "the_geom" instead of "geometry" in order for writing the feature to a shapefile to work

**Comment by metasim** [comment]
FWIW, `SimpleFeature`s are that bread-and-butter of GeoMesa. Perhaps there's an opportunity for collaboration/reuse?

http://www.geomesa.org/documentation/current/user/cli/sfts.html

**Comment by echeipesh** [comment]
Thats partly why this was written, there is even skinny wrapper project for GeoMesa that we have: https://github.com/locationtech/geotrellis/tree/master/geomesa/src/main/scala/geotrellis

It would be good to work out the integration story more.
