### ISSUE TITLE
HdfsUtils calls println

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2588]
Logger should be used instead of `println`:

https://github.com/locationtech/geotrellis/blob/0b904994239fa45e258ca9cbe10267a8b623e439/spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala#L272

https://github.com/locationtech/geotrellis/blob/0b904994239fa45e258ca9cbe10267a8b623e439/spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala#L246

**Comment by pomadchin** [comment]
Fixed in https://github.com/locationtech/geotrellis/commit/d762b5229f742446d31a1db676a0524b498780c9#diff-c4af457ee72db4e5d07b0de45b9f69b1
