### ISSUE TITLE
Resampling artifact when building pyramid

### ISSUE THREAD

**Issue by jfbourgon** [locationtech/geotrellis#2600]
Recent migration to GeoTrellis 1.2 introduced linear artifacts in some levels when building pyramid,

Here is example of hillshade output generated from resample DEM data  with bilinear method at level 15.

GeoTrellis 1.1 output
![GeoTrellis 1.1 output](http://ftp.maps.canada.ca/pub/nrcan_rncan/data_access/geotrellis/23341-bilinear-with-geotrellis-1.1.1.png)
GeoTrellis 1.2 output
![GeoTrellis 1.2 output](http://ftp.maps.canada.ca/pub/nrcan_rncan/data_access/geotrellis/23341-bilinear-with-geotrellis-1.2.1.png)

Here is also links to the [data workflow](http://ftp.maps.canada.ca/pub/nrcan_rncan/data_access/geotrellis/IngestRaster.scala) and [source data](http://ftp.maps.canada.ca/pub/nrcan_rncan/data_access/geotrellis/) used to build the pyramid.

The issue may be related to the work done under #2505

**Comment by jpolchlo** [comment]
@jfbourgon Can you test #2638 to see if it resolves your problem?

**Comment by jpolchlo** [comment]
I believe that you might not have tested the change that I made.  Check out this branch: https://github.com/jpolchlo/geotrellis/tree/fix/pyramid-artifacts
The commit number is f1b6a40

**Comment by jfbourgon** [comment]
My bad. I was obviously not testing with the right source code. It is now looking better, here are the sample I'm now getting where the resampling artifact are no longer visible. Thanks. 
![Level 16](https://user-images.githubusercontent.com/1030226/39320398-f175519a-4951-11e8-8109-45f8117662e4.png) Level 16
![Level 15](https://user-images.githubusercontent.com/1030226/39320405-f3da5c82-4951-11e8-80c0-1420b3f22135.png) Level 15
