### ISSUE TITLE
maxTileSize not able to be set in COGLayerWriter

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2606]
Suggesting an API change: we should allow options to be passed into the COGLayerWriter methods. This would avoid users having to learn another type (COGLayer), and pass any necessary options like maxTileSize (which cannot currently be set from a `.write` method) and resample method.

What I want to do:

```scala
    val writer = FileCOGLayerWriter(attributeStore)

    val layerName = "landsat"
  
    val options = 
      COGLayerWriter.Options(
        resampleMethod = Bilinear,
        maxTileSize = 1024,
        compression = Deflate
      )

    writer.write(layerName, reprojected, zoom, options)
```

what I currently have to do:

```scala
    val writer = FileCOGLayerWriter(attributeStore)

    val layerName = "landsat"

    val cogLayer =
      COGLayer.fromLayerRDD(reprojected, zoom, compression = Deflate, maxTileSize = 1024)

    val keyIndexes =
      cogLayer.metadata.zoomRangeInfos.
        map { case (zr, bounds) => zr -> ZCurveKeyIndexMethod.createIndex(bounds) }.
        toMap

    writer.writeCOGLayer(layerName, cogLayer, keyIndexes)
````

**Comment by jbouffard** [comment]
@lossyrob Do we want to encapsulate `maxTileSize`, `resampleMethod`, etc. in `COGLayerWriter.Options`? I thought we were trying to move away from that since it obfuscates the options available to the user.
