### ISSUE TITLE
Produced attribute metadata with wrong name

### ISSUE THREAD

**Issue by brunifrancesco** [locationtech/geotrellis#2611]
I noticed that during the ingestion of multiband tifs, the metadata attribute folder is named as *_attributes* and zoom level metadata files have been named as *<layer_name><sep><zoom_level><sep>metadata.json*. 

Reading this attributes with geopyspark api (which in turns call geotrellis API) metadata file cannot be found since it looks for a folder named *attribute* and metadata file names with a different separator than one used by spark-etl.

IE: _attributes/test___1___metadata.json (wrong) => attributes/test__.__1__.__metadata.json (correct)

**Comment by pomadchin** [comment]
Hi! What backend do you experience this issue with? 
@jbouffard mb it's a geopyspark issue?

**Comment by Frophie** [comment]
In my experience, `attributes\test__.__1__.__metadata.json` is writen by `FileLayerWriter`, and `_attributes/test___1___metadata.json` is writen by `HadoopLayerWriter`.

**Comment by jbouffard** [comment]
@pomadchin I actually think this is a GeoTrellis issue since GeoPySpark doesn't doesn't deal with file naming at all

**Comment by pomadchin** [comment]
@Frophie ah thanks for explanation, yes indeed, but still looks like a typo in the codebase.

**Comment by brunifrancesco** [comment]
After @Frophie suggestion, I figured the issue out. I ingested images using the *hadoop* backend and tried to read ingested geotrellis layers with a FileLayerReader. So seems there's no bug at all.
