### ISSUE TITLE
Create a tag for the 1.2.0 release

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2612]
It's helpful to be able to have a reference to specific releases here:

https://github.com/locationtech/geotrellis/tags

**Comment by lossyrob** [comment]
Would you like to do the honors? You could find the final commit of that version on the 1.2 branch and push a tag!

**Comment by metasim** [comment]
Going with 14a328543da9002da96288f80ce4be8005e02533.

**Comment by metasim** [comment]
Scratch that.... going with 15dbae6cdededfb682a6c7bf38ce559acbc741f2.
