### ISSUE TITLE
Add version tag creation to release process

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2615]
_Offshoot of #2612_

Not sure where this goes, or if the current process would allow this to be automated (e.g. `sbt-release`), but we should have something that ensures that each binary release gets a specific git tag assigned to it.

**Comment by pomadchin** [comment]
Resolved via https://github.com/locationtech/geotrellis/pull/3440

Snapshots are published to sonatype with the commit hash in the version, releases are published per tag push.
