### ISSUE TITLE
RDD readed by `HadoopCOGLayerReader` is incorrect

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#2635]
[COG.zip](https://github.com/locationtech/geotrellis/files/1934243/COG.zip)
Read this COG catalog by `HadoopCOGLayerReader` and wtite the stitched result, like this:
```
    val reader = HadoopCOGLayerReader(path)(sc)

    val layer = reader.read[SpatialKey, MultibandTile](LayerId("crop_COG", 11))

    val pathHadoop = new Path(path + "stitched.tif")
    val raster = layer.stitch()
    val geoTiff = GeoTiff(raster, layer.metadata.crs)
    geoTiff.write(pathHadoop, sc.hadoopConfiguration)
```
got a result with some tiles not in the right position.
This is the tiffs in "7_11" level:
![cog](https://user-images.githubusercontent.com/9249196/39081598-d0fbabbe-4576-11e8-952b-b00a1d310e04.png)
And this is the stitched result:
![stitched](https://user-images.githubusercontent.com/9249196/39081602-e5491980-4576-11e8-9c1a-573d321a78dc.png)
The offset is one tile wide(256 cell), so I suspect the SpatailKey in RDD is miscalculated.

Note: to use the COG catalog, need to change the `path` value in "crop_COG___0___header.json".
This COG catalog is created by 2.0.0-M2.

**Comment by pomadchin** [comment]
Thanks for your report! We'll have a closer look at least on Monday.
