### ISSUE TITLE
`crop` behaviors on geotiff are difficult to reason about

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2666]
It seems like we've allowed our overloads to go a little bit too far. In general, I think we should accept syntactic overloads and try very hard to avoid semantic overloads. For example, I'd argue that cropping by a bounding box or by gridbounds is semantically the same: we give some kind of boundary and we get back the stuff within said boundary. Contrast that case with this overload:
`def crop(subExtent: Extent, cellSize: CellSize, resampleMethod: ResampleMethod, strategy: OverviewStrategy): MultibandRaster`
What, exactly, is it trying to do? This is entirely unclear without reading source. As it turns out, it's going to use the cell size to get the closest overview which it will *then* crop. 

Why not expose the ability to get nearest overview directly and treat of these things in a combinatorial fashion? GeoTrellis nouns should have consistent, predictable verbs.

**Comment by pomadchin** [comment]
Resolved via https://github.com/locationtech/geotrellis/commit/c4053c7b34cdb48206ec7205939ec20078f031b8
