### ISSUE TITLE
Investigate and benchmark imageio-ext

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2697]
We are currently hampered by ability to easily read non-GeoTiff files. [geotrellis-gdal](https://github.com/geotrellis/geotrellis-gdal) exists and can be used to read other file formats through GDAL JNI bindings but supports only the basic use cases. 

Before we commit the effort to extend that project to support efficient windowed reads in `geotrellis-gdal` and build-up the required API we should check out existing work in [`imageio-ext`](https://github.com/geosolutions-it/imageio-ext) which already wraps GDAL through `javax.imageio` API.  Number of [plugins](https://github.com/geosolutions-it/imageio-ext/tree/master/plugin/gdal) are already supported.

- [x] Benchmark reading LC8 GeoTiff into set of windows vs GeoTrellis GeoTiff reader.
- [x] See what it would take to read [`SRTMHGT`](http://www.gdal.org/frmt_various.html#SRTMHGT) files using `imageio-ext`

On concern is that [`javax.imageio.ImageReader`](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageReader.html) produces [`java.awt.image.Raster`](https://docs.oracle.com/javase/8/docs/api/java/awt/image/Raster.html), so at the moment we would incur re-encoding cost to produces `Tile` or `MultibandTile`. However we can hope that efforts towards GeoTrellis raster type class started [here](https://github.com/locationtech/geotrellis/pull/2520) will eventually allow us to use `java.awt.image.Raster` without re-encoding it.

**Comment by jamesmcclain** [comment]
> See what it would take to read SRTMHGT files using `imageio-ext`

This can be answered in the negative.  There does not appear to be a wrapper for the GDAL `SRTMHGT` driver.

**Comment by pomadchin** [comment]
Closed. At his point we decided to improve our own GDAL support: https://github.com/geotrellis/geotrellis-gdal
