### ISSUE TITLE
Implement Our Own AWSCredentialsProvider

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2708]
Right now, when ones creates an instance of the default `AmazonS3Client`, the `DefaultAWSCredentialsProviderChain` is used to find the required AWS credentials (see [here](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3Client.scala#L150-L151)). This is an issue, though, as the `DefaultAWSCredentialsProviderChain` is unable to pick up credentials set in neither the `SparkConf` nor in the `HadoopConfiguration`. Therefore, it would be useful if we either implemented our own `AWSCredentialsProvider`, or extended the `DefaultAWSCredentialsProviderChain`.

There is a slight challenge in that GeoTrellis' `s3` package does depend on Spark. Thus, we will need to find a way to obtain the values set in the `SparkConf` and `HadoopConfiguration` from the environment.

**Comment by pomadchin** [comment]
We have a way for users to set their own configured AWS S3 Clients, closed via https://github.com/locationtech/geotrellis/pull/2911
