### ISSUE TITLE
IllegalArgumentException: Negative size while reading Big GeoTiff

### ISSUE THREAD

**Issue by mmkrystek** [locationtech/geotrellis#2711]
Hello,
I'm trying to read 24GB large GeoTiff file. 
gdalinfo reports that it is georeferenced tiff: 
```
$ gdalinfo file.tif 
Driver: GTiff/GeoTIFF
Files: file.tif
Size is 43200, 18000
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["unknown",
        SPHEROID["WGS84",6378137,298.257223563]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
Origin = (-180.000000000000000,90.000000000000000)
Pixel Size = (0.008333333333333,-0.008333333333333)
```
In the file header (offset 2) I have found: 0x002B (43 dec) value which determines BigTiff file format. 

When I try to read this file using GeoTiffReader I get following exceptions:
```
-------------------
readSingleband
-------------------
file size long: 25021170758
file size int:  -748633018
[error] (run-main-3) java.lang.IllegalArgumentException: Negative size
[error] java.lang.IllegalArgumentException: Negative size
[error] 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:865)
[error] 	at geotrellis.util.Filesystem$.toMappedByteBuffer(Filesystem.scala:43)
[error] 	at geotrellis.util.Filesystem$.slurp(Filesystem.scala:58)
[error] 	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:77)
[error] 	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:46)
```

```
-------------------
readMultiband
-------------------
file size long: 25021170758
file size int:  -748633018
[error] (run-main-2) java.lang.IllegalArgumentException: Negative size
[error] java.lang.IllegalArgumentException: Negative size
[error] 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:865)
[error] 	at geotrellis.util.Filesystem$.toMappedByteBuffer(Filesystem.scala:43)
[error] 	at geotrellis.util.Filesystem$.slurp(Filesystem.scala:58)
[error] 	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:179)
[error] 	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:151)
```
I have already figured out that it is caused by https://github.com/locationtech/geotrellis/blob/9abbe5b89c75d7303916ab65260f6d5ad0b6b15a/util/src/main/scala/geotrellis/util/Filesystem.scala#L41
where casting file length from long to int will produce negative integer due to integer size overflow. File size (25021170758) is larger then Integer.MAX_VALUE (2147483647)

Is there any other way of reading large geotiff files?

**Comment by pomadchin** [comment]
Hey @mmkrystek! can you post here some code example and geotrellis version you use? 
But if you're trying to load into memory the entire 24G tiff it's not the best idea in any case (: Try to load it into a cluster memory and to do a distributed map algebra, or read only necessary area of interest out of such a tiff to work with.

**Comment by mmkrystek** [comment]
I'm using:  2.0.0-RC1
`"org.locationtech.geotrellis" %% "geotrellis-raster" % "2.0.0-RC1"`

the code fails at these simple calls:
`val geoTiff: SinglebandGeoTiff = GeoTiffReader.readSingleband(path);`
or
`val geoTiff: MultibandGeoTiff = GeoTiffReader.readMultiband(path);`

Well, I have also bad feelings about loading 24GB file into memory ;) gdalinfo reports that the file has 43 Bands and I need to access and proceed each band one by one. I thought that using:
`val geoTiff: MultibandGeoTiff = GeoTiffReader.readMultiband(path);` is a good starting point

**Comment by pomadchin** [comment]
yea, not sure that there are good ways to solve it, but you can use streaming read: 

```
read{Multiband|Singleband}(path: String, streaming: Boolean)
```

**Comment by mmkrystek** [comment]
I have already tried streaming version. This only slightly change the stacktrace:
```
[error] (run-main-6) java.lang.IllegalArgumentException: Negative size
[error] java.lang.IllegalArgumentException: Negative size
[error] 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:865)
[error] 	at geotrellis.util.Filesystem$.toMappedByteBuffer(Filesystem.scala:43)
[error] 	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:173)
```
In all cases Filesystem.toMappedByteBuffer method is used, so the problem remains.
