### ISSUE TITLE
Request: make `TileMergeMethods` change non-breaking.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2722]
The `TileMergeMethods` trait changed in 2.0.0-RC1 with the addition of `merge(other: T, col: Int, row: Int): T`, breaking existing code.

https://github.com/locationtech/geotrellis/blame/2.0/raster/src/main/scala/geotrellis/raster/merge/TileMergeMethods.scala#L40-L52

Would it be possible for the need for this method to be fulfilled in a non-breaking way? I'm attempting to upgrade RasterFrames to work with both 2.0.0 and 1.2.1, and this is blocking that effort. Otherwise we'll have to figure out some sort of cross-build approach, adding complexity to deployment.

**Comment by pomadchin** [comment]
Hey @metasim why does it break the code? https://github.com/jpolchlo/geotrellis/blob/3b799a6b3774243a3608c4ae70a56af74db33f57/raster/src/main/scala/geotrellis/raster/merge/TileMergeMethods.scala#L38 this won't work for you?

**Comment by pomadchin** [comment]
Nvm figured it out!

**Comment by metasim** [comment]
I think I figured out a reflections-based approach to this, so closing for the time being.
