### ISSUE TITLE
Implicit conversions from Raster to Tile create confusing semantics

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2768]
The existence of this automatic conversion unknowingly sent me down a rabbit hole:

https://github.com/locationtech/geotrellis/blob/0af8404c3cdb22ee98102c4d18963b08567833c8/raster/src/main/scala/geotrellis/raster/Raster.scala#L49

One result of this is that you can call `(_: ProjectedRaster[Tile]).interpretAs(someCellType)`, but what is returned is a `Tile` and not a `ProjectedRaster[Tile]`. Implied in the name `interpretAs` (at least to me), is that you're going to get back the same type as the method receiver, as you would with a case class `copy` method. I think there are many other methods that end up being like this (e.g. `mapTiles`).

I'm in the camp that considers implicit type conversions like this to be bad practice. I know it will break code, but I personally think it should be removed (along with as many other implicit conversions you can purge).

**Comment by echeipesh** [comment]
I agree actually. I've been surprised by this conversion myself, its good to have confirmation.
I think the resulting code impact would actually be very limited and changes are actually clearer and I'd argue for releasing this with 2.0 to save other people sanity.

Similar concern is [`Feature[G, D]` to `G`](https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/Feature.scala#L45) conversion that gives a `Feature` all the methods of a geometry. However in that case the code impact would be much larger.

**Comment by echeipesh** [comment]
Spoke about code impact before compiling the tests on that one.
