### ISSUE TITLE
Remove References to geotrellis.raster.op in the Docs

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2786]
While we have since removed the `op` sub-package from the `raster` package, there are still [references](https://github.com/locationtech/geotrellis/search?q=%22geotrellis.raster.op%22&unscoped_q=%22geotrellis.raster.op%22) to it in the documentation. These should be removed in order to avoid any confusion someone might have when reading these documents.

**Comment by CloudNiner** [comment]
Superseded by #3306 as these examples won't compile via mdoc if/when they're moved over.
