### ISSUE TITLE
Incorrect Extent Created From Transform

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2787]
In the following code, a `sourceRasterExtent` is reprojected to the `targetCRS` using `Transform`. The resulting `footprint` is then turned into a `RasterExtent`, and it is then reprojected back to its original `sourceCRS` via `backTransform`. I would expect then that `backFootprint` to be the same as the `Extent` in the `sourceRasterExtent`. However, this is not the case. Running that equality check of the two areas will result in `false`. This can be confirmed by looking at the two `Extent`s:

```
scala> sourceRasterExtent.extent
res10: geotrellis.vector.Extent = Extent(634185.0, 1962885.0, 860715.0, 2193915.0)

scala> backFootprint
res11: geotrellis.vector.Extent = Extent(632540.8176618286, 1960074.92103874, 865184.2997484582, 2197085.5334588015)
```

I'm not really sure what the cause of this incorrect result could be, or if it's actually a bug. We should take some time to investigate it, though, to understand what's happening.

```scala
val sourceCRS = CRS.fromEpsgCode(32619)
val sourceExtent = Extent(634185.0, 1962885.0, 860715.0, 2193915.0)
val sourceRasterExtent = RasterExtent(sourceExtent, 7551, 7701)

val targetCRS = CRS.fromEpsgCode(3857)

val transform = Transform(sourceCRS, targetCRS)
val backTransform = Transform(targetCRS, sourceCRS)

val footprint = ReprojectRasterExtent.reprojectExtent(sourceRasterExtent, transform)

val backFootprint = ReprojectRasterExtent.reprojectExtent(RasterExtent(footprint, sourceRasterExtent.cols, sourceRasterExtent.rows), backTransform)

sourceRasterExtent.area == backFootprint.area
```

**Comment by jpolchlo** [comment]
Extent reprojection isn't invertible.  Consider that an extent, when projected, is actually bounded by curvilinear edges, and not at all guaranteed to be axis aligned.  To turn the polygonal region that represents the reprojected extent into an actual, axis-aligned extent, we must expand (or at the very least preserve) the area covered by the projected source extent.  The back projection can similarly only expand the area.  In general, I would not expect this test to succeed.

**Comment by jpolchlo** [comment]
Worth mentioning that if you do this as ProjectedExtent.reprojectAsPolygon, and then back project the result, you should get reasonably close to the same area which is what I imagine you were thinking about.

**Comment by jpolchlo** [comment]
Sorry to spam, but I realized that my initial point is captured by the statement `backFootprint.contains(sourceExtent)`

**Comment by jbouffard** [comment]
@jpolchlo I see. I was unaware that that reprojection isn't reversible. Though, now that makes sense once you've explained it. I'll try using `ProjectedExtent.reprojectAsPolygon` for the back transforms and see how they do. Thanks for your help!
