### ISSUE TITLE
ArrayTile combine methods perform non-exhaustive matching

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2792]
The following methods make incorrect assumptions about the `Tile` type-space. Because `Tile` inheritance is not restricted to the `geotrellis` namespace, type matching without a default handler should be considered a violation of the type contract.

https://github.com/locationtech/geotrellis/blob/bdc0ce22f657d87ef3f4ae9bdb953e7c9abd2564/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L224-L234

https://github.com/locationtech/geotrellis/blob/bdc0ce22f657d87ef3f4ae9bdb953e7c9abd2564/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L269-L278

I'm not sure I understand the purpose of these special cases (performance related?), but a default `case t: Tile => ???` should be implemented if possible.

**Comment by metasim** [comment]
FWIW, this complicates being able to [implement delayed read tile semantics](https://github.com/locationtech/rasterframes/blob/f6f2cb69ce3aa39e8b1b4a77461a14238e418263/core/src/main/scala/astraea/spark/rasterframes/tiles/DelayedReadTile.scala#L33).

**Comment by pomadchin** [comment]
hey @metasim it's definitely was an optimisation thing, however i think that virtual dispatch should work here as expected.

For instance for a `ConstantTile` it would be smth like 

```scala
def combine(other: Tile)(f: (Int, Int) => Int): Tile = other.map(z => f(iVal, z))
```

and for other types it would be smth different, we can take into account specifics of a `composite tile (taking into account its layout)`.

I am not sure that it's possible to implement it just for a `Tile` interface. 
It's implementations are `CompositeTile`, `ConstantTile`, `ArrayTile`, `GeoTiffTile`, `CroppedTile`, `DelayedConversionTile`.

I'm wondering would not it just dynamically dispatch to a correct implementation? From my experience it should.

**Comment by metasim** [comment]
This is the backtrace I'm getting:

```scala
scala.MatchError: astraea.spark.rasterframes.tiles.InternalRowTile@2f75ac5 (of class astraea.spark.rasterframes.tiles.InternalRowTile)
	at geotrellis.raster.ArrayTile$class.combineDouble(ArrayTile.scala:270)
	at geotrellis.raster.FloatArrayTile.combineDouble(FloatArrayTile.scala:24)
	at astraea.spark.rasterframes.tiles.DelegatingTile$class.combineDouble(DelegatingTile.scala:89)
	at astraea.spark.rasterframes.tiles.InternalRowTile.combineDouble(InternalRowTile.scala:44)
	at geotrellis.raster.Tile$class.dualCombine(Tile.scala:101)
	at astraea.spark.rasterframes.tiles.InternalRowTile.dualCombine(InternalRowTile.scala:44)
	at geotrellis.raster.mapalgebra.local.LocalTileBinaryOp$class.apply(LocalTileBinaryOp.scala:56)
```

**Comment by metasim** [comment]
@pomadchin I not clear on how virtual dispatch would work in the case where `other` in 

https://github.com/locationtech/geotrellis/blob/bdc0ce22f657d87ef3f4ae9bdb953e7c9abd2564/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L269

is not a subclass of `ArrayTile`, `ConstantTile`, etc.? You'll get a `MatchError` no matter what.

**Comment by pomadchin** [comment]
@metasim i haven't answered to that part of your issue ;)
