### ISSUE TITLE
RasterRegionReproject is broken for TileFeature (and possibly all immutable Tile types)

### ISSUE THREAD

**Issue by mteldridge** [locationtech/geotrellis#2799]
It looks like `RasterRegionReproject` is not implemented for `TileFeature`.  I have attempted to implement this in my own code, but I think there is a design flaw in the trait.  
In particular, I don't think there is any way to correctly implement `mutableRegionReproject` because there is no way to mutate the feature data value of the `TileFeature`.
Here is my implementation:
```scala
type WithMergeMethods[V] = V ⇒ TileMergeMethods[V]
implicit def TileFeatureRasterRegionReproject[
  T <: CellGrid : RasterRegionReproject : WithMergeMethods,
  D: Monoid]: RasterRegionReproject[TileFeature[T, D]] = new RasterRegionReproject[TileFeature[T, D]] {
    override def regionReproject(raster: Raster[TileFeature[T, D]],
                                 src: CRS,
                                 dest: CRS,
                                 rasterExtent: RasterExtent,
                                 region: Polygon,
                                 resampleMethod: ResampleMethod): Raster[TileFeature[T, D]] = {

      val mapped = raster.mapTile(_.tile)
      val reprojected = implicitly[RasterRegionReproject[T]].regionReproject(mapped, src, dest, rasterExtent, region, resampleMethod)
      
      // delegate to tile and add the feature data from raster
      new Raster[TileFeature[T, D]](TileFeature(reprojected.tile, raster.tile.data), raster.extent)
    }
    // THIS IS BROKEN
    override def mutableRegionReproject(target: TileFeature[T, D],
                                        raster: Raster[TileFeature[T, D]],
                                        src: CRS,
                                        dest: CRS,
                                        rasterExtent: RasterExtent,
                                        region: Polygon,
                                        resampleMethod: ResampleMethod): Unit = {
      val mapped = raster.mapTile(_.tile)
      // Here, delegate to the tile.  WHAT ABOUT THE DATA PART? 
      //(I need to merge and/or copy  raster.tile.data into target.data, but I can't!)
      implicitly[RasterRegionReproject[T]].mutableRegionReproject(target.tile, mapped, src, dest, rasterExtent, region, resampleMethod)
    }
  }
```
Notice the tile feature data can't be copied into `target` from the source `raster` in `mutableRegionReproject`.  

Along the same lines, what are the repercussions of this if you have an immutable `Tile` type?  

Also, for what its worth, the implementation of `mutableRegionReproject` for SinglebandTile seems to rely on a broken contract for `Tile.mutable` in that` mutable` is supposed to return a mutable *copy* of the `Tile`.  The geotrellis implementation (shown below) relies on the fact that `Tile.mutable` is returning a mutable version of the `Tile` itself and thus can do its job via a side-effect of the method call.
https://github.com/locationtech/geotrellis/blob/829b4faf0a4323de90a732f9cb2e3516bb9dc14c/raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala#L117-L120

**Comment by jpolchlo** [comment]
Yeah, we often forget to consider feature types when we design interfaces.  If you had a suggestion for how to fix this interface to be more amenable to your use case, please list it below.

I was quite aware that GT's handing of mutable is _sooo_ broken.  All Tiles are mutable, as it turns out.  But the broken mutability is a feature at this point, since I believe that fixing it would break other things.  Not 100% sure on that, but I have a feeling that I looked into it and then made a shruggy face when the implications started to resolve.  Not sure what the current imperative is to make Tile truly immutable anyway.  Particularly since all the in-use realizable instances are already MutableTile subclasses.  Our intent is to introduce a new typeclass system to replace the tile infrastructure anyway, so we're currently good with duct tape and bubblegum patches.  We should for sure be mindful of the mutable/immutable distinction in the process.

**Comment by mteldridge** [comment]
My main concern is to find a way to make this work with `TileFeature`.  The problem is that any time I `reproject` an `RDD` of `TileFeatures`, I will lose data in the `TileFeatures` that are accumulated in the `mergeValues` method of TileRDDReproject:
https://github.com/locationtech/geotrellis/blob/829b4faf0a4323de90a732f9cb2e3516bb9dc14c/spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala#L195-L199
As the code stands, it only preserves the first data feature when the createCombiner is called, but subsequent calls to mergeValues can't combine data fields, so all other feature data is lost. 

As for a solution, I would strive for one that doesn't rely on modifying the Tile as a side-effect or extend the interface of the TileFeature[T, D] such that D has some kind of mutability.

**Comment by metasim** [comment]
@jpolchlo  Couldn't resist adding my 2¢ :-)

> ... All Tiles are mutable, as it turns out...

This is not correct.  If you look at the type hierarchy, there are lots of `Tile` types that would break under the mutability assumption:

<img width="382" alt="screen shot 2018-09-07 at 2 49 15 pm" src="https://user-images.githubusercontent.com/131013/45237631-3e5a6d00-b2ad-11e8-98ab-680da9763549.png">

Furthermore, the API documentation is pretty explicit that a tile **copy** will be returned:

https://github.com/locationtech/geotrellis/blob/829b4faf0a4323de90a732f9cb2e3516bb9dc14c/raster/src/main/scala/geotrellis/raster/Tile.scala#L103-L106

The algorithmic assumption that `mutable` returns something that points to the same memory as the given tile is only true for subclasses of `MutableArrayTile`, which is a bit of a performance hack anyway:

https://github.com/locationtech/geotrellis/blob/829b4faf0a4323de90a732f9cb2e3516bb9dc14c/raster/src/main/scala/geotrellis/raster/MutableArrayTile.scala#L28-L29

> But the broken mutability is a feature at this point, since I believe that fixing it would break other things. 

I don't think you need to change anything about the behavior of the tiles. You just need to update the algorithms that make assumptions about editing in-place a tile (which I don't think you should ever do with a client-provided Tile). In this case my recommendation is to: 

1. Make the mutable form of reprojection `private`
  
 https://github.com/locationtech/geotrellis/blob/829b4faf0a4323de90a732f9cb2e3516bb9dc14c/raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala#L41

2. Either make sure all calls to `mutableRegionReproject` first make a copy of the client provided tile, or have the method make its own copy.

Another consideration is to do the reprojection work in Array space (outside of tiles) to make it clear that you are poking at memory in an unconstrained way.
