### ISSUE TITLE
Geotrellis haz cats (leakage)

### ISSUE THREAD

**Issue by mteldridge** [locationtech/geotrellis#2800]
As I have upgraded to GT 2.0, I find that the internal usage of `cats` is leaking out to the users of geotrellis.  

The big offender is in `TileLayerMetadata`.  In order to call `map`, I have to `import cats.syntax.functor._`.  This extremely non-obvious.  

The other place I have encountered this is in usage of `TileFeature[T,D]`, where `D` is constrained to be either a `cats.Monoid` or a `cats.Semigroup` so I tend to have to import these and possibly `cats.syntax.Monoid._`, `cats syntax.Semigroup._`, and `cats.instances.all_`.

I think this complexity can be hidden via type alias.

**Comment by metasim** [comment]
Best issue title ever 😆

**Comment by pomadchin** [comment]
Closing it as "won't fix" issue.
