### ISSUE TITLE
Add support for Feature and FeatureCollection bounding box (bbox)

### ISSUE THREAD

**Issue by philvarner** [locationtech/geotrellis#2809]
An optional bbox attribute is defined in the geojson spec: http://geojson.org/geojson-spec.html#bounding-boxes

This would be useful to clients using the geotrellis-vector Feature and FeatureCollection functionality to marshall and unmarshall JSON.

**Comment by pomadchin** [comment]
@metasim the current `Feature` is defined as 

```scala
case class Feature[+G <: Geometry, +D](geom: G, data: D)
```

wondering, would it be enough just to add this `bbox` print into all JsonWriters?
