### ISSUE TITLE
Cassandra Tile Indexing Primary Key Read Optimization

### ISSUE THREAD

**Issue by ALPSMAC** [locationtech/geotrellis#2831]
Today the layer API currently creates a table in Cassandra for tiles that looks like this: 

```
CREATE TABLE terrain.tiles_256x256 (
    key varint,
    name text,
    zoom int,
    value blob,
    PRIMARY KEY (key, name, zoom)
) WITH CLUSTERING ORDER BY (name ASC, zoom ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```

In Cassandra the Primary Key consists of 2 parts, the _partition key_ and the optional _clustering keys_.  The _partition key_ is always the first entry in a composite primary key, and the _clustering keys_ follow.  Hence, in the above table the _partition key_ is _key_ and the _clustering keys_ are _name_ and _zoom_.  

Cassandra hashes the _partition key_ to determine which Cassandra instance within the cluster to store the row.  It then orders the data within a common _partition key_ on a single instance by the _clustering keys_ associated with it.  So for instance: 

```
Node 1: 
  ( key = 1, name = "a", zoom = 0 )
  ( key = 1, name = "a", zoom = 1 )
  ( key = 1, name = "b", zoom = 0 )
  ( key = 1, name = "b", zoom = 1 )
Node 2: 
  ( key = 2, name = "a", zoom = 0 )
  ( key = 2, name = "a", zoom = 1 )
  ( key = 2, name = "b", zoom = 0 )
  ( key = 2, name = "b", zoom = 1 )
```

By ordering and partitioning the keys in this manner, Cassandra is trying to provide a way to optimize read performance since we would like to have to go to 1 node and read as contiguously as possible from that node per read query for optimal performance. 

Okay - maybe you knew all of that already... maybe not... 

My question is: 

To the best of my understanding the `key` field in this table layout is the result of the SFC indexing operation used to compute the integral spatial index of the tile at a particular zoom level.  The point of SFC is to preserve multidimensional locality in a single dimensional index in order to optimize for reading data that is "close together".  Better SFCs provide more predictable and closer mappings from input dimensions to the singular output scalar.

Now - the default partitioner for Cassandra these days I believe is based on the Murmer3 Hash.  It's used specifically to achieve a good even spread of non-equal _partition keys_ across the cluster, thus breaking the assumption that a well-behaved SFC will aid in read performance for queries in the same neighborhood, right? 

If we wanted to redefine this table to take advantage of SFC at each zoom level we might reorder the `PRIMARY KEY` so that the main table definition looked more like this: 

```
CREATE TABLE terrain.tiles_256x256 (
    key varint,
    name text,
    zoom int,
    value blob,
    PRIMARY KEY (name, zoom, key)
) WITH CLUSTERING ORDER BY (name ASC, zoom ASC)
```

This would have the result (I believe... if I'm not missing something or totally bonkers) of partitioning based on layer name and ordering the layer by zoom and key within the zoom level, thus preserving the locality assumptions of the SFC.  

So - was there a reason for declaring the primary key as `(key, name, zoom)` over `(name, zoom key)` or is this a performance enhancement that ought to be made to the Cassandra indexing?

**Comment by ALPSMAC** [comment]
On some further reflection, I suppose the disadvantage to `(name, zoom, key)` is that it maps the entirety of a layer to a single Cassandra instance, thus you'd want enough space on each instance in the cluster to support an entire layer's worth of tiles through all possible zoom levels.  

In a multi-layer application, this could lead to read "hot spots" too in your Cassandra cluster if your clients are interested more in certain layers rather than others.

Typically the go-to way to solve this in Cassandra data modeling (from my understanding anyway) is to  "bin" the _partition key_ by grouping it as a tuple which has the effect of more evenly distributing the data.  In our example, `zoom` is not the best way to bin up a partition, since higher zoom levels have exponentially more data than lower ones, but it is at least a good start...

Keeping that in mind we might improve upon our index and declare it instead as: `((name, zoom), key)` to spread the partitioning more evenly. 

We could potentially improve our spread further by creating a secondary index over global spatiotemporal regions that groups tiles from a similar region together... one might accomplish this with perhaps modulus division of the SFC key?  I'd have to think about that one a little more to convince myself that makes sense (because we don't want to go back to completely breaking the assumption that SFC provides data locality)... but `((name, zoom, mod_key), key)` *might* be one way to bin up the partitions and better balance read performance (where `mod_key = key % numBins`)... `numBins` might be a property we wish to allow clients to configure as well to determine the amount of spread in a given partition...

I think roughly (provided we haven't completely obliterated any advantages from the SFC indexing by having chosen the modulus function to stratify our binning... not convinced... needs more thought...) that might correlate to something like:

`numBins` high => better space utilization (spreading) but at the cost of read performance
`numBins` low => worse space utilization (spreading) with increased read performance 

I'm also not clear on how intrusive a change adding such a binning function may be into the layer management since there's some pretty type-constructor heavy stuff in there if I recall... could be difficult to inject additional assumptions without breaking the API.

**Comment by pomadchin** [comment]
Hey @ALPSMAC yes, you're right. My thought was as in your second comment, the intention was to distribute keys across the cluster. I think your first comment makes a lot of sense, i think we need can make the Cassandra schema definition configurable (as much as it's possible). 

You're welcome to suggest API breaking features btw, I'm happy about your thoughts and about bining in your second comment (sounds like a winner for me or at least as an interesting suggestion). If you have some time to create at least a `WIP` PR that would be amazing. We plan to release `GT 3.0` soon, and if you need to introduce some breaking changes into Cassandra API I'll try to assist you as much as it's possible / will try to push it forward myself as it's important for you.

**Comment by ALPSMAC** [comment]
Hey @pomadchin - thanks for the feedback... glad I'm not totally out to lunch on this :-) 

I'm actually heading out on vacation next week, but would be happy to take a swing at updating the Cassandra layer API when I get back the following week... 

I won't promise I'll be able to wrap my head around how the internals of the layer API work all that quickly though... your scala-type-implicit-evidence-foo is much more impressive than my own ;-)

**Comment by ALPSMAC** [comment]
Hi @pomadchin - I'm back in town from vacation and am hoping to have some spare cycles in the next week or two to poke at this more.  Just wanted to provide you a status update.

**Comment by pomadchin** [comment]
hey @ALPSMAC great news! Thanks for the update, hope you had a great vacation btw.

**Comment by ALPSMAC** [comment]
Hey @pomadchin - so I'm finally digging into this a bit more and I've got a strawman setup I think we can play with.  I'm hoping to have a _very_ WIP PR up for you to provide feedback on later today.  It'll be rough for now... lots of duplicative code that should be pulled into a common trait somewhere and I did have to modify the `delete` API both in the `LayerManager` and `LayerDeleter` spark.io stuff in order to pass the `K` type parameter through to have access to the `KeyIndex` inside the deleter code.

I'll also be on vacation (again) starting next week (I know - two in a row... gotta love "use or lose" leave time :-) ).  Hopefully when I'm back after the 1st of the year I can take a look at your feedback and see if there's any value to pursuing this further.

**Comment by pomadchin** [comment]
Hey @ALPSMAC that's awesome! Will take a closer look into it hopefully to help you. Wondering is it possible to avoid deleter declaration change. We'll see; thanks again!

**Comment by ALPSMAC** [comment]
Yeah - would love to avoid the deleter API change.  Suspect it's possible,
just not sure where to look for the right index range information
otherwise.

**Comment by ALPSMAC** [comment]
Hey @pomadchin.  Happy New Year - hope you had a happy holiday season.  I'm back in the office now and will start working on a little bit of code cleanup as well as looking to implement some reasonable benchmarking somewhere to validate the approach in the WIP PR I put up before the holidays.

**Comment by pomadchin** [comment]
Hi @ALPSMAC! I'll be back tomorrow and will review everything and leave some comments :D I'm on vacation until tomorrow.

**Comment by ALPSMAC** [comment]
Hi @pomadchin - hope you had a great vacation :-) 

I'm looking primarily for thoughts about the implementation approach to see if you think it's valid to continue down this path.  There's a lot that can be done to reduce the code duplication in the PR as it sits... I've been trying to clean that up a bit but haven't had the time to dedicate to working on it that I'd like to as of late. 

I'd also really like to figure out a way to provide a reasonable benchmark - both to quantify the sorts of read/write loads that benefit from the updated indexing strategy and to prove to myself that the updated strategy actually *does* save time when you're doing a lot of location-cache-sympathetic reads.  I don't want to contribute something that just makes performance worse! 

I'll be out of the office until Friday supporting some engineering meetings offsite but will try to get back to this on Friday or sometime next week.

**Comment by ALPSMAC** [comment]
Hey @pomadchin - no rush - I've been consumed by meetings here on my end all week... probably won't have a chance to lay hands on code until sometime next week.

**Comment by pomadchin** [comment]
@ALPSMAC no worries! we have a sprint planning today, will assign some time to take a look into this issue during the upcoming sprint :+1:

**Comment by pomadchin** [comment]
Full results of this PR were merged into [this](https://github.com/locationtech/geotrellis/tree/rnd/cassandra-indexing) branch.

The documentation (this experiment description) was merged into the master branch and is placed [here](https://github.com/locationtech/geotrellis/tree/rnd/cassandra-indexing/docs/cassandra).

Thanks @ALPSMAC for such a complicated work!
