### ISSUE TITLE
Spire versions hell

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2832]
We depend on a new spire version 0.16.0 and spire algebra depends on cats 1.0.1. Our main cats dep is cats 1.4.0. It makes impossible [BreakMap](https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/raster/src/main/scala/geotrellis/raster/render/BreakMap.scala) class usage.

```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o108.map.
E                   : java.lang.NoSuchMethodError: spire.std.package$any$.OrderProduct2(Lcats/kernel/Order;Lcats/kernel/Order;)Lcats/kernel/Order;
E                   	at geotrellis.raster.render.BreakMap.geotrellis$raster$render$BreakMap$$vmTree$lzycompute(BreakMap.scala:83)
E                   	at geotrellis.raster.render.BreakMap.geotrellis$raster$render$BreakMap$$vmTree(BreakMap.scala:80)
E                   	at geotrellis.raster.render.BreakMap$mcII$sp.apply$mcII$sp(BreakMap.scala:127)
E                   	at geotrellis.raster.render.IntColorMap.map(ColorMap.scala:212)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metasim** [comment]
We've had this problem too. This primary pain is that they changed to group name of the `spire` library but the package names stayed the same. This means that normal library resolution/eviction can't control what's happening.... both libraries get pulled in.

**Comment by metasim** [comment]
I re-read your post, and I'm not sure a) we have exactly the same issue, and b) our fix will address yours. In our case we actually downgraded spire, and then used shading, but had first tried this:

```
    // Group name changed to "org.typelevel"
    excludeDependencies ++= Seq(
      ExclusionRule("org.spire-math", "spire_2.11"),
      ExclusionRule("org.spire-math", "spire-macros_2.11")
    )
```

**Comment by metasim** [comment]
@pomadchin What's the dependency chain look like?

GT -> Spire 0.16 -> Cats 1.0.1
GT -> Cats 1.4.0

?

**Comment by pomadchin** [comment]
Yes, that was the original idea. But, i think there is just an API change in spire. It was originally discovered by @jbouffard , I'm checking the spire code at the moment. Probably it's just a mess in the code that for some reason worked and didnt break the compilation.

**Comment by metasim** [comment]
It's indeed a mess. We've been fighting this and a very similar one with `spray-json` all through our platform because some dummy (ahem) decided that our libraries should be kept up to date.

**Comment by pomadchin** [comment]
Raster project deps graph.

![image](https://user-images.githubusercontent.com/4929546/49308248-c9cc4e80-f4e8-11e8-8e0b-249ae30ebee1.png)

**Comment by metasim** [comment]
Just to confirm (not that I have ready solution), is this the issue?

<img width="484" alt="screen shot 2018-11-30 at 1 55 56 pm" src="https://user-images.githubusercontent.com/131013/49308983-cd8bb100-f4a7-11e8-98bd-6aa7000410ea.png">

**Comment by pomadchin** [comment]
_i can't confirm it_ it's already 10 p.m. :/ we need to investigate it a bit more.

I've posted a question in a spire gitter channel and mainter answered that in theory cats kernel should be cross version compatible. also it looks like for some reason it can't find spire generated package

**Comment by pomadchin** [comment]
I think we have two spire versions in our project. Or in @jbouffard 's project. It sounds very much like we'll downgrade spire dep.

**Comment by pomadchin** [comment]
@metasim 

```
$ ls $SPARK_HOME/jars | grep spire
spire-macros_2.11-0.13.0.jar
spire_2.11-0.13.0.jar
```

Solution should be to downgrade or to shade our spire dep.

**Comment by echeipesh** [comment]
I'd like to suggest we just downgrade spire to 0.13:
- We are not heavy users of spire, mostly we just use the `cfor` macros
- Shading rules are not shipped with the artifacts, so every user would have to enable them for their build
- Spark is a pretty important dependency so tracking their version of spire-0.13 is a large incentive
- Breeze is an upcoming dependency so tracking that similarly is important
- We didn't have a concrete reason to bump to 0.16 so its not clear we're really giving anything up
