### ISSUE TITLE
Histogram methods should be sensitive to implied variance

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2845]
The methods on `Histogram`s should be written to take into account the variance implied by the histogram hierarchy. Otherwise, `asInstanceOf` calls become necessary (not nice)
```scala
// StreamingHistogram *is* Histogram[Double], and should be treated like it
val someTile: Tile = ???
val otherTile: Tile = ???
val h1 = StreamingHistogram.fromTile(someTile)
val h2 = StreamingHistogram.fromTile(otherTile)
```

The compiler is not satisfied that h1 and h2 (Histogram[Double] subtypes) can be merged
```scala
val mergeFail = h1 merge h2
```

This works, is ugly:
```scala
val mergeSucc = h1 merge h2.asInstanceOf[Histogram[Double]]
```

**Comment by pomadchin** [comment]
I've checked it an everything works; are you sure that there is a problem in this API? 

```scala
    val sourceHistogram = {
      val h = StreamingHistogram(42)
      h.countItem(1, 1)
      h.countItem(2, 2)
      h.countItem(4, 3)
      h.countItem(8, 4)
      h.countItem(16, 5)
      h
    }

    val targetHistogram = {
      val h = StreamingHistogram(42)
      h.countItem(1, 1)
      h.countItem(2, 2)
      h.countItem(3, 3)
      h.countItem(4, 4)
      h.countItem(5, 5)
      h
    }

    sourceHistogram merge targetHistogram
```

Works good to me.

**Comment by moradology** [comment]
You're right, in the single case (which I foolishly provided without further investigation) this is not a problem but by not keeping type information around (i.e. without handling the implied variance) folds will be problematic (this is the context I encountered it in):
```scala
val t: Tile = ???
val s1 = StreamingHistogram.fromTile(t)
val s2 = StreamingHistogram.fromTile(t)
val s3 = StreamingHistogram.fromTile(t)
val s4 = StreamingHistogram.fromTile(t)
List(s1, s2, s3).foldLeft(s4)(_ merge _)
```

The above won't compile without this change:
```scala
List(s1, s2, s3).foldLeft(s4.asInstanceOf[Histogram[Double]])(_ merge _)
```

Happy to close if this is desirable behavior

**Comment by pomadchin** [comment]
Talked a lil bit in private about it, so it makes sense to walk through all the `Histogram[Double]` functions and to check that all functions return the most specific types. This would resolve the signature of the fold above from being verbose:

```scala
List(s1, s2, s3).foldLeft[Histogram[Double]](s4)(_ merge _)
```

To just 

```scala
List(s1, s2, s3).foldLeft(s4)(_ merge _)
```
