### ISSUE TITLE
Help with triangulation of 3D point cloud

### ISSUE THREAD

**Issue by RobertoMinelli** [locationtech/geotrellis#2862]
Dear all,

I have a point cloud (in .xyz format) representing the coordinates (longitude, latitude, altitude) of a terrain. I need to perform a surface reconstruction from these points to generate a terrain that I can potentially 3D print.

I am new to both 3D modeling and 3D printing. Do you think that I can use geotrellis to do so? If so, how?

Thank you very much for your time and support,
Roberto

[terrain-1548687116-20m.xyz.txt](https://github.com/locationtech/geotrellis/files/2803789/terrain-1548687116-20m.xyz.txt)

**Comment by RobertoMinelli** [comment]
Hi, yes it is an entire dataset. It is made of two set of points: half of them have the same z-coordinate (i.e., base) and the others have different z-coordinate, representing the real altitude.

On 28 Jan 2019, at 22:29, Ross Bernet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey - is that the entire dataset?

**Comment by RobertoMinelli** [comment]
Attached is a .stl file with the final result I'd like to reach: A 3D mesh/surface reconstructed from the .xyz points.

To do so, I used [CloudCompare](https://www.danielgm.net/cc/) as follows:
1. Import the .xyz point cloud
2. Compute normals
3. Apply Poisson surface reconstruction
4. Create a cross-section removing the lower part of the surface reconstruction
5. Export in .stl format

What I'd love to have is all the functionalities 1-5 implemented in my Scala application. I am wondering whether geotrellis can help me in achieving that, at least in part.

Hope this helps to better formulate my problem.

Cheers,
Roberto

[Lugano-terrain-1548753214-20x10-cut-bin.stl.zip](https://github.com/locationtech/geotrellis/files/2807600/Lugano-terrain-1548753214-20x10-cut-bin.stl.zip)

**Comment by rossbernet** [comment]
That looks like a fairly small dataset.

Have you tried to run this demo?
https://github.com/geotrellis/geotrellis-pointcloud-demo

Our focus has been the distributed case, which is more complex to set up to handle larger datasets. You may be well serviced by a lighter weight tool. I know [pdal](https://pdal.io/) is not a scala library, but could that work for you?

We haven't been actively developing point cloud support for a couple of years now, so unfortunately we won't be able to provide a ton of help... but I'd start with that demo if you haven't.

**Comment by pomadchin** [comment]
That's closed for now, but I'm happy to answer more questions.
