### ISSUE TITLE
Deprecate custom LazyLogging

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2868]
`geotrellis.util.LazyLogging` was originally necessary mark the logger as `@transient`, to ensure that the logger didn't get serialized as a part of a Spark `RDD` closure. Modern versions of `com.typesafe.scalalogging.LazyLogging` properly use the `@transient` annotation. Library users should be encouraged to use the official `LazyLogging` over the GeoTrellis one.

The migration path (across major GT release) should be:

1. Mark the `trait` as `@deprecated` and update all of GeoTrellis to use the standard version
3. Remove `geotrellis.util.LazyLogging` from GeoTrellis.

**Comment by pomadchin** [comment]
@metasim oops we've removed it already (: I don't think that it was so popular that everybody used it.

**Comment by pomadchin** [comment]
https://github.com/locationtech/geotrellis/pull/2813

**Comment by metasim** [comment]
Cool. I keep accidentally using it, but I'm on 2.1.0.

**Comment by pomadchin** [comment]
If you're on 2.1.0 you should use it. In the 2.1.0 typesafe LazyLogging doesnt mark logger inside as transient, that's why we had our own version of the same thing.

**Comment by metasim** [comment]
I meant I was on Geotrellis 2.1.0. I'm on ScalaLogging 3.9.0, which properly handles `@transient`.
