### ISSUE TITLE
ArrayTile equality is invalid

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2869]
Equals test between `ArrayTile`s doesn't consider `CellType`, and only compares integral representation.

Not sure if this extends beyond `ArrayTile`s.

```scala
scala> val t1 = ArrayTile(Array(1, 2, 3, 4), 2, 2)
t1: geotrellis.raster.IntConstantNoDataArrayTile = IntConstantNoDataArrayTile([I@1b69f8dd,2,2)

scala> val t2 = ArrayTile(Array(1.1, 2.2, 3.3, 4.4), 2, 2)
t2: geotrellis.raster.DoubleConstantNoDataArrayTile = DoubleConstantNoDataArrayTile([D@43fb8901,2,2)

scala> t1 == t2
res0: Boolean = true
```

Tested against GT 2.1.0.

**Comment by metasim** [comment]
```scala
scala> val t3 = UByteConstantTile(3, 2, 2)
t3: geotrellis.raster.UByteConstantTile = UByteConstantTile(3,2,2,uint8)

scala> val t4 = ArrayTile(Array(3.1, 3.2, 3.3, 3.4), 2, 2)
t4: geotrellis.raster.DoubleConstantNoDataArrayTile = DoubleConstantNoDataArrayTile([D@7b194456,2,2)

scala> t3 == t4
<console>:36: warning: comparing case class values of types geotrellis.raster.UByteConstantTile and geotrellis.raster.DoubleConstantNoDataArrayTile using `==' will always yield false
       t3 == t4
          ^
res1: Boolean = false

scala> t3.toArrayTile == t4
res2: Boolean = true
```

**Comment by pomadchin** [comment]
A note for the history: probably we always had this behavior; the equals function definition for ArrayTile: 
https://github.com/locationtech/geotrellis/blob/a89ce9f73f1493262587db91a3ad1f1f8709d745/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L291

**Comment by metasim** [comment]
Cell comparison is broken here:

https://github.com/locationtech/geotrellis/blob/a89ce9f73f1493262587db91a3ad1f1f8709d745/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L298

If `cellType.isFloatingPoint` were used, then could have a separate loop for double.

`cellType` should also be part of the comparison, as well as the actual number of `cols` and `rows` (not just `size`), IMO.
