### ISSUE TITLE
`WKT.fromEpsgCode` makes unsafe call to `Option.get`

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2870]
Exceptions are thrown when provided WKT doesn't have an EPSG code in it (something that's not a requirement). These methods should return `Option[String]` instead.

https://github.com/locationtech/geotrellis/blob/d83fd66db9ed1276b6b82ff4adce8e362ac56cef/proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala#L65

https://github.com/locationtech/geotrellis/blob/d83fd66db9ed1276b6b82ff4adce8e362ac56cef/proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala#L72

**Comment by CloudNiner** [comment]
@metasim It looks like there are already methods that perform these two conversions you've called out:

https://github.com/locationtech/geotrellis/blob/d83fd66db9ed1276b6b82ff4adce8e362ac56cef/proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala#L48

and 

https://github.com/locationtech/geotrellis/blob/d83fd66db9ed1276b6b82ff4adce8e362ac56cef/proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala#L55

such that if I just change the return types of the methods in the issue description to return `Option` of whatever thing they currently are, then they basically become method aliases.

Given that, @echeipesh and I discussed a change of the conversion methods in WKT to the following:
https://github.com/locationtech/geotrellis/compare/master...CloudNiner:feature/awf/from-epsg-code-unsafe-get%232870?expand=1

This removes the unsafe methods, which gives better type safety and a "watch out!" moment to client code. It also gives the available options more consistent names and unique type signatures. We also clean up the issue in the old code where one method returning EPSG strings didn't return a code prefixed with `"EPSG:`. And the docstrings make more sense!

With that, the test fixup begins. Let us know if you have any qualms about the changes described above.
