### ISSUE TITLE
geotrellis-slick for scala 2.12 is missing

### ISSUE THREAD

**Issue by kwark** [locationtech/geotrellis#2873]

**Comment by pomadchin** [comment]
Hey @kwark we don't plan to maintain `geotrellis-slick` any more (Look into [this PR](https://github.com/locationtech/geotrellis/pull/2823) for details about Scala 2.12 missing packages). We plan to move this code into https://github.com/geotrellis/geotrellis-contrib. 

If you really need `geotrellis-slick` for Scala 2.12 you're welcome to contributt and we'll be happy to assist you to get it merged!
