### ISSUE TITLE
Optimize CRS reading

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2890]
According to a recent profile I generated, the processing of CRSs from a GeoTiff header accounts for half of the read time, including network overhead. Needs further investigation, but I thought there was code that was supposed to cache the proj4 database, and I'm wondering if something's wrong with it; `org.locationtech.proj4j.io.Proj4FileReader#readFile` shouldn't be called every single time a CRS decoded.

<img width="1448" alt="Screen Shot 2019-04-02 at 11 09 28 AM" src="https://user-images.githubusercontent.com/131013/55413734-eed4da80-5537-11e9-937f-1b2b3cc702ee.png">

**Comment by pomadchin** [comment]
Looks like not a geotrellis bug? We depend on https://github.com/locationtech/proj4j now.

**Comment by metasim** [comment]
@pomadchin Who did the work of extracting Proj4j into a separate project? I want to ask if any caching that was there previously has been removed due to library dependencies, etc . One of our tests went from 2 minutes to 10 minutes after upgrading GT and I'm trying to track it down.

**Comment by metasim** [comment]
@pomadchin Whether or not it's a GT bug is debatable over who should be responsible for caching the EPSG->Proj4j database. Probably Proj4j, but not entirely convinced.

**Comment by pomadchin** [comment]
I think it was Eugene, but it was just removing code thing. If you have a small unit test just throw it here. I think in proj4j itself there are some differences, so the unit test is required

**Comment by pomadchin** [comment]
@metasim so you remember what test went from 2 minutes to 10 minutes?

**Comment by metasim** [comment]
@pomadchin Unfortunately it was in some internal integration test that really isn't reproducible without a bunch of infrastructure. That said [this benchmark](https://github.com/s22s/rasterframes/blob/develop/bench/src/main/scala/org/locationtech/rasterframes/bench/CRSBench.scala) reproduces the various call paths that I was having problems with. If you replace `LazyCRS` with just `CRS` you should trigger them all.
