### ISSUE TITLE
AccumuloAttributeStore has really poor performance

### ISSUE THREAD

**Issue by jmt-vanderlee** [locationtech/geotrellis#2897]
Calling `availableZoomLevels(layerName: String)` on the `AccumuloAttributeStore` results in it reading all layers from Accumulo and performing a reduce in memory.

This happens per call without any sort of caching or filtering on Accumulo's side. This makes this function completely useless in a production system.

Execution path:
```
// level 1
def availableZoomLevels(layerName: String): Seq[Int] = layersWithZoomLevels(layerName)

// level 2
def layersWithZoomLevels: Map[String, Seq[Int]] = layerIds.groupBy(_.name).mapValues(_.map(_.zoom))

// level 3
def layerIds: Seq[LayerId] = {
  val scanner = connector.createScanner(attributeTable, new Authorizations())
  try {
    scanner.iterator.asScala.map { kv =>
      val Array(name, zoomStr) = kv.getKey.getRow.toString.split(SEP)
      LayerId(name, zoomStr.toInt)
    }
    .toSeq
    .distinct
  } finally {
    scanner.close()
  }
}
```

In our test environment this results in a download of 100Mb to produce a list of `[0, 1, ..., 22]`

**Comment by pomadchin** [comment]
Thanks for reporting! If you want to contribute, we would be happy to navigate you throw the process. If not - we'll try to fix it in our next release. Would you also like this to be released as a part of `2.x` minor release?
