### ISSUE TITLE
CassandraAttributeStore availableZoomLevels poor performance

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2900]
The problem described in https://github.com/locationtech/geotrellis/issues/2897 also exists for our Cassandra backend. 

We probably need to think a little bit about the attributeStore table, since partition key columns are not yet supported by SASI and layerId is a partition key in our case: https://github.com/apache/cassandra/blob/094689acf10bf133637c53aeebd3e8157832a279/src/java/org/apache/cassandra/index/sasi/SASIIndex.java#L148-L149

Mb @ALPSMAC has his opinion about Cassandra LIKE queries.

Related to https://github.com/locationtech/geotrellis/pull/2899

**Comment by ALPSMAC** [comment]
@pomadchin apologies for the delay in getting back to you... been swamped here!  

The related PR ( https://github.com/locationtech/geotrellis/pull/2901 ) seems entirely reasonable to me.

When last I checked I don't believe the SASI indexing in Cassandra was believed to be really ready for "prime time" yet anyway.

**Comment by pomadchin** [comment]
@ALPSMAC thanks! tbh I was excited by the SASI index :D also, FYI: https://github.com/locationtech/geotrellis/releases/tag/v2.3.0
