### ISSUE TITLE
TileLayoutStitcher.stitch sparseness assumption

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2903]
The current stitch function is a 'dense' stitch function. If some keys are missing it will stitch things as close as is possible (it stitches based on key order rather than the value/true extent of keys). It assumes that every possible key in some region will exist in the iterator being stitched into a single tile.

We need to add a stitch function that will work correctly even with missing / skipped keys - a 'sparse' stitch

**Comment by pomadchin** [comment]
The implementation is [here](https://github.com/geotrellis/geotrellis-contrib/blob/3a87d1db243d1a2ac8252e44471a1622c45fc730/vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisRasterSource.scala#L203) it would be good to come up with the idea how to move it into GT core.
