### ISSUE TITLE
VectorTile should support option for allowing the user to choose ring winding order

### ISSUE THREAD

**Issue by CloudNiner** [locationtech/geotrellis#2909]
From [Mapbox specification](https://docs.mapbox.com/vector-tiles/specification/#winding-order):

> Any polygon interior ring must be oriented with the winding order opposite that of their parent exterior ring and all interior rings must directly follow the exterior ring to which they belong. Exterior rings must be oriented clockwise and interior rings must be oriented counter-clockwise (when viewed in screen coordinates).

Vector tiles exported that don't provide spec compliant winding can break Mapbox GL JS rendering in subtle ways, such as by incorrectly rendering fill-extrusions: https://github.com/geotrellis/geotrellis-usbuildings/issues/4

**Comment by pomadchin** [comment]
Will, VectorTiles can be generated from whatever you'll pass into it, since VectorTile part is mostly about encoding / decoding protobuf messages. Is not it a client side logic? It looks like we need to have overloads to change polygons orientation / etc inside a vector package. Correct if I'm wrong.

Also leaving here a note about JTS polygons: 

```
B6. Why does JTS use clockwise as the canonical polygon exterior ring orientation?
The first version of the OGC Simple Features for SQL specification did not define a canonical orientation for polygon rings. JTS was designed to meet this specification, and it was necessary to choose a canonical orientation. For historical reasons the choice was to have the canonical orientations be CW for exterior rings and CCW for interior rings. (This was not arbitrary - it followed the convention used in the ESRI SDE, one of the leading spatial database systems at the time). Note that as per the OGC SFS spec, JTS operations do not assume any particular orientation for the rings of input polygons.

Subsequent versions of the OGC specifications have chosen to specify an orientation convention, and unfortunately they chose the opposite one to JTS.

A future version of JTS might make the canonical orientation selectable by the user (on a library-wide basis). JTS never assumes any particular orientation for input, so this is mostly a matter of reversing output rings where required. Of course, the user can do this themselves if necessary.
```

**Comment by jpolchlo** [comment]
This is functionality to meet the vectortile spec.  It's expected that a valid JTS poly should turn into valid vector tile geometry.  There's no reason at all to make clients have to deal with this themselves.  It's non-trivial to do, and there will be (presumably) many clients with the exact same need, which starts to sound like we should provide this functionality.

But it's interesting this thing you dug up about JTS polygons winding order having a standard orientation.  I wondered why we haven't been seeing polygons rendering properly, and so went digging.  To wit:
```scala
scala> val polyCCW = Polygon(Point(0,0), Point(1,0), Point(1,1), Point(0,1), Point(0,0)).jtsGeom
polyCCW: org.locationtech.jts.geom.Polygon = POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))

scala> polyCCW.normalize

scala> polyCCW
res18: org.locationtech.jts.geom.Polygon = POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))

scala> val polyCW = Polygon(Point(0,0), Point(0,1), Point(1,1), Point(1,0), Point(0,0)).jtsGeom
polyCW: org.locationtech.jts.geom.Polygon = POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))

scala> polyCW.normalize

scala> polyCW
res20: org.locationtech.jts.geom.Polygon = POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))
```
It may be sufficient to call `normalize` prior to serializing polygons.

**Comment by pomadchin** [comment]
@jpolclo sounds good to me! We can give it a try

**Comment by pomadchin** [comment]
@CloudNiner can you guys prepare a failing dataset?

**Comment by pomadchin** [comment]
I think it is possible to do it in terms of https://github.com/locationtech/geotrellis/pull/2898 since it is still awaiting `ip_team`

**Comment by CloudNiner** [comment]
Nice. Do you have a preference for dataset format/size? 

Any of the Microsoft US buildings GeoJson files exhibit the issue. I can reduce one of those geojson files to a few polygons if you're looking for a test case.

**Comment by pomadchin** [comment]
@CloudNiner the perfect would be some code how do you produce VectorTiles :D just to know at what point do I need to try to normalize them and would it work at all

**Comment by CloudNiner** [comment]
Here's some demo code that generates vector tiles from an `RDD[(SpatialKey, Iterable[VectorTileFeature[Geometry]])]` after loading a GeoJson and OSM orc source and performing some operations on the join of the two sources: https://github.com/geotrellis/geotrellis-osm-diff-demo/blob/feature/awf/osm-buildings-diff/src/main/scala/BuildingsDiff.scala#L34-L122

Once the joined `RDD[(SpatialKey, Iterable[VectorTileFeature[Geometry]])]` is constructed, it is flatted back to an `RDD[Row]` and converted to a `DataFrame` so that VectorPipe can construct the tiles from JTS Geometry objects. In this case, since I'm using VectorPipe, it seems that any winding order adjustments should happen implicitly in VectorPipe after I've handed the DataFrame over to the library for VT generation. 

To test the normalize call, let me add that call to the code above and run a small job on a tiny state today. That shouldn't take long.

If calling normalize is sufficient, the normalize call probably belongs somewhere in the VectorPipe pipeline and thus the issue bounces back to that library and/or we can talk about whether there's still some wrapper method that makes sense in `geotrellis.vectortile` to make intent more clear.

**Comment by jpolchlo** [comment]
Still think it belongs in GT.  Otherwise, other apps don't get the benefit.  We could make the call optional for sake of speed if the requester knows that the geometry is good.

**Comment by CloudNiner** [comment]
Calling normalize solved the issue:

![Screen Shot 2019-04-25 at 10 27 15 AM](https://user-images.githubusercontent.com/1818302/56743536-bc885880-6744-11e9-9c20-e5129410348a.png)

And whoops, I think I misunderstood the role of vectortile here somehow. Yeah an option when the geoms are serialized to protobuf(?) still makes the most sense.

**Comment by CloudNiner** [comment]
Versus older tileset without the normalize calls:
![Screen Shot 2019-04-25 at 10 35 45 AM](https://user-images.githubusercontent.com/1818302/56744143-f017b280-6745-11e9-8ea0-43bd24fbe6a8.png)

**Comment by CloudNiner** [comment]
And here's the diff that solves the issue in the osm diff demo: https://github.com/geotrellis/geotrellis-osm-diff-demo/commit/91cc8f47f5d87db5e7d2315c64cc9ddb52712fcf
