### ISSUE TITLE
Mirror 2.3.0 to Maven/Sonatype Central

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2915]
Due to an outage at repo.locationtech.org, noted that there's not a mirror of version 2.3.0 on Maven Central:

https://search.maven.org/search?q=g:org.locationtech.geotrellis

**Comment by pomadchin** [comment]
GeoTrellis 2.3.1 is in the [Maven Central repo](https://repo1.maven.org/maven2/org/locationtech/geotrellis/geotrellis-spark_2.11/2.3.1/) now.
