### ISSUE TITLE
Breaking the Collections API From the Spark Package

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2916]
# Breaking the API Out of the Spark Package

One of the goals of GeoTrellis 3.0 is to break out non-Spark specific code in `geotrellis.spark` and put it elsewhere. This issue seeks to go over breaking out the Collections API from `geotrellis.spark`.

## Background

The `geotrellis.spark` package is currently the main place for I/O code in GeoTrellis. This includes both code that uses Spark and code that does not. Organizing the code like has lead to two main issues:

  1. Having to depend on Spark even though Spark is not needed (ie Collections API/ValueReader)
  2. Complications with dependency management/package hierarchy

The first problem can lead to unnecessary work, as one needs to ensure that Spark is provided even when not needed. This can make using GeoTrellis more aggravating/confusing for users. While the latter point can make understanding the GeoTrellis environment more difficult, and can cause problems when trying to refactor/add code.

## Solution

The solution to this issue would be to break out the Collections API into a new package. However, because of the spread out/diverse nature of the Collections API code, multiple packages will need to be created.

### geotrellis.layers

The `geotrellis.layers` package will be the base I/O package that does not deal with Spark. As such, the following code will be placed into this package:

  - `Metadata` and `TileLayerMetadata`
  - All base layer I/O actions (ie `LayerReader`, `LayerCopier`, `LayerMover`, etc)
  - Collections API
  - `ValueReader` API
  - index API
  - Avro Encoders/Decoders and codecs

By having the above API live in `geotrellis.layers`, much of the I/O logic will be separated from Spark.

### geotrellis.layers.accumulo, geotrellis.layers.cassandra, goetrellis.layers.hbase, and geotrellis.layers.s3

While creating `geotrellis.layers` has separated some of the Spark and non-Spark logic, additional packages will have to be made. These being: `geotrellis.layers.accumulo`, `geotrellsi.layers.cassandra`, `geotrellis.layers.hbase`, and `geotrellis.layers.s3`. All of these packages will contain the Collections API for their specific backend. These additional packages provide the following benefits:

  - Clean break between Spark and Collections API for each backend
  - The ability to choose exactly what's needed without any unnecessary imports/dependencies

### Package Hierarchy

With the new packages being created, the GeoTrellis package hierarchy will need to be changed. For this task, we've decided that the packages using Spark should depend on those using Collections. Thus, the new package hierarchy for GeoTrellis would look something like this:

![Untitled Diagram(2)](https://user-images.githubusercontent.com/11041248/57241071-34386c00-6ffe-11e9-87dc-a8510f59f96c.png)

## Demo

```scala

import geotrellis.tiling.SpatialKey
import geotrellis.layers.io._

import java.net.URI


val uri: URI = ???
val attributeStore: AttributeStore = AttributeStore(uri)
val layerReader: CollectionLayerReader = CollectionLayerReader(attributeStore)

val layer: TileLayerCollection = layerReader.read[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](LayerId("test-layer", 0))
```

**Comment by jbouffard** [comment]
@metasim What are your thoughts/concerns about this split?

**Comment by jpolchlo** [comment]
@jbouffard Are there some typos here?  Your write-up mentions nothing about `geotrellis.layers` and yet, it's in the dep graph and example.

**Comment by jbouffard** [comment]
@jpolchlo Whoops. Yeah, that's a typo. Will fix that now

**Comment by jbouffard** [comment]
@jpolchlo Just resolved the typos. Should make more sense now.

**Comment by jpolchlo** [comment]
Nice work, @jbouffard.  This looks pretty good.

**Comment by pomadchin** [comment]
I'm worrying a little that there would be tons of separate packages; however it looks good to me :+1:

**Comment by metasim** [comment]
@jbouffard Thanks for asking! Super supportive of this! Lots of package is OK in my mind as long as the dependency graph looks as clean as the one above (i.e. no cyclic references). Means the abstractions are directionally correct.

A couple of points of consideration: 

1. Is the name `geotrellis.layers` the right one? Is it useful for cases where you don't care about Geotrellis Layers? What is the intersection of _Geotrellis Collections_ and image processing pipelines that don't involve actually writing layers (e.g. CNN chipping pipelines)? Or is this something that might sit between `raster` and `tiling`?
2. Does this set the stage appropriately for the folding in `RasterSource`, VLM, et al., or is that orthogonal?

**Comment by moradology** [comment]
Something I've seen in terms of organizing third party packages that extend some core functionality is stashing all that third party code into a directory. An example: https://github.com/pureconfig/pureconfig/tree/master/modules

It seems to me that we might sensibly do that for `spark` and `layers`. I.e. `geotrellis/spark/hdfs` and `geotrellis/layers/hdfs`

**Comment by echeipesh** [comment]
@moradology How does that comment reconcile with discussion here: https://github.com/locationtech/geotrellis/pull/2944

**Comment by pomadchin** [comment]
Just a note about fixing the tests: all scripts from `.locationtech`, `.travis` and `scripts` dirs should be fixed, since we have more projects now and all the names were changed.
