### ISSUE TITLE
Raster project compilation fails due to missing io.json.Implicits error

### ISSUE THREAD

**Issue by CloudNiner** [locationtech/geotrellis#2919]
The error thrown is:
```
[error] Symbol 'type geotrellis.raster.io.json.Implicits' is missing from the classpath.
```

This only happens occasionally. Sometimes I can compile and test a few times before the error is triggered again while working within the `raster` subproject in SBT. I'm able to workaround by calling `clean` and then re-compiling. But it always comes back...

Full trace:
```
[IJ]raster > testOnly geotrellis.raster.summary.polygonal.MaxSpec
[info] Compiling 5 Scala sources to /Users/andrew/src/geotrellis/raster/target/scala-2.11/classes ...
[info] Done compiling.
[info] Compiling 216 Scala sources to /Users/andrew/src/geotrellis/raster/target/scala-2.11/classes ...
[error] Symbol 'type geotrellis.raster.io.json.Implicits' is missing from the classpath.
[error] This symbol is required by 'package geotrellis.raster.io.package'.
[error] Make sure that type Implicits is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of geotrellis.raster.io.json.
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by pomadchin** [comment]
@CloudNiner every time we have some significant package renamings / movements you can experience this issue. It is actually not our issue, but SBT / Scala caches issues. Also probably because you're using IntelijIDEA it can break caches sometimes (?) though it is a guess only.

**Comment by echeipesh** [comment]
I've seen this triggered consistently by minor, non-interface, changes to unrelated files. My setup is running Metals with SBT console, so the conflicts in cache still somehow be related.

**Comment by pomadchin** [comment]
We can't do too much about it (trying another build tool?). Hopefully with the new SBT releases and after switching to coursier in terms of this PR https://github.com/locationtech/geotrellis/pull/3279 the problem would be less often.

Let's reopen it once it will become a problem again.
