### ISSUE TITLE
Replace `Mergeable` with Cats' `Semigroup`

### ISSUE THREAD

**Issue by jpolchlo** [locationtech/geotrellis#2925]
For historical reasons, we were shy about using standard functional typeclass libraries.  We therefore have some vestigial typeclasses kicking about in the codebase.  One such example is https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/merge/Mergable.scala.  This should be replaced by Cats' [Semigroup](https://typelevel.org/cats/typeclasses/semigroup.html).

**Comment by moradology** [comment]
The work for this task is now done (and lives at `feature/semigroup-merge`: https://github.com/locationtech/geotrellis/tree/feature/semigroup-merge) but merging it in will be a pain until we merge the `spark-split` changes.
