### ISSUE TITLE
Override S3RDDWriter s3Client creates a non serializable task

### ISSUE THREAD

**Issue by kitchdev** [locationtech/geotrellis#2929]
Referencing an issue I was recently helped with:
[Issue #2928](https://github.com/locationtech/geotrellis/issues/2928)

Attempting to overide the default s3Client config for both S3RDDWriter and S3AttributeStore:
```scala
  // from solution of Issue #2928
  @transient lazy val amazonS3 = AmazonS3ClientBuilder
    .standard()
    .withCredentials(credentialsProvider)
    .withRegion(region)
    .build()

  // Creating a geotrellis s3Client
  var specialS3Client = new AmazonS3Client(amazonS3)

  // Create the attributes store that will tell us information about our catalog.
  val attributeStore = new S3AttributeStore(bucketName, prefix) {
    override def s3Client = specialS3Client
  }

  // Create the writer that we will use to store the tiles in the local catalog.
  // from solution of Issue #2928
  val writer = new S3LayerWriter(attributeStore, bucketName, prefix) {
    override def rddWriter = new S3RDDWriter {
      def getS3Client = () => specialS3Client
    }
  }
```

results in this error: [Spark output](https://pastebin.com/siMy66F7)

It seems somehow overidding the `def s3Client` in the `S3RDDWriter` creates a non serializable issue.

I've created a public repo with the necessary code in order to reproduce the problem:
https://github.com/kitchdev/geotiff-s3-tiler

I'd appreciate any help/guidance you guys can give on the matter

**Comment by pomadchin** [comment]
Hey @kitchdev try to replace `var specialS3Client` with `def specialS3Client`

**Comment by kitchdev** [comment]
Hey @pomadchin, 
tried that and the output seems to be the same as what i posted above^
noteably:
```[error] Caused by: java.io.NotSerializableException: com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3
[error] Serialization stack:
[error] 	- object not serializable (class: com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3, value: com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3@39a31f47)
[error] 	- field (class: com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3$$anonfun$getS3Client$1, name: $outer, type: class com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3)
[error] 	- object (class com.olameter.sdi.geotifftos3.LocalTileSlicer$$anon$2$$anon$3$$anonfun$getS3Client$1, <function0>)
[error] 	- field (class: geotrellis.spark.io.s3.S3RDDWriter$$anonfun$update$1, name: _getS3Client$1, type: interface scala.Function0)
[error] 	- object (class geotrellis.spark.io.s3.S3RDDWriter$$anonfun$update$1, <function1>)
```

**Comment by pomadchin** [comment]
Probably it requires to be more strcit about how you create an s3 client: 

```scala
def getS3Client = () => {
  new AmazonS3Client(AmazonS3ClientBuilder
    .standard()
    .withCredentials(credentialsProvider)
    .withRegion(region)
    .build())
}
```

**Comment by pomadchin** [comment]
The idea is to track down the reason why this function became non serializable by checking all the fields inside all classes that would be serialized.

**Comment by kitchdev** [comment]
Hmm I think I understand, I tried your suggestion and made sure my variables are properly typed but honestly I can't see anything else in the class creating an issue with serialization.

```scala 
  val AWS_ACCESS_KEY = sys.env("AWS_ACCESS_KEY")
  val AWS_SECRET_KEY = sys.env("AWS_SECRET_KEY")
  val prefix = "geotiff_tiles"
  val region: Regions = Regions.US_EAST_2
  val awsCredentials: BasicAWSCredentials =
    new BasicAWSCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY)
  val credentialsProvider: AWSStaticCredentialsProvider =
    new AWSStaticCredentialsProvider(awsCredentials)

  @transient lazy val amazonS3: AmazonS3 = AmazonS3ClientBuilder
    .standard()
    .withCredentials(credentialsProvider)
    .withRegion(region)
    .build()

  // Creating a geotrellis s3Client
  def specialS3Client: AmazonS3Client = new AmazonS3Client(amazonS3)
  // Create the attributes store that will tell us information about our catalog.
  val attributeStore: S3AttributeStore =
    new S3AttributeStore(bucketName, prefix) {
      override def s3Client = specialS3Client
    }
  // Create the writer that we will use to store the tiles in the local catalog.
  val writer: S3LayerWriter =
    new S3LayerWriter(attributeStore, bucketName, prefix) {
      override def rddWriter = new S3RDDWriter {
        def getS3Client = () => {
          new AmazonS3Client(
            AmazonS3ClientBuilder
              .standard()
              .withCredentials(credentialsProvider)
              .withRegion(region)
              .build()
          )
        }
      }
    }
```

**Comment by pomadchin** [comment]
@kitchdev you can try to make writer lazy and transient: `@transient lazy val writer`
Since i don't thing you need it anywhere

**Comment by kitchdev** [comment]
@pomadchin hmm still no dice. How frusterating.

**Comment by eraigosa** [comment]
Please read [this article](https://blog.xebia.fr/2017/09/27/spark-comprendre-et-corriger-lexception-task-not-serializable/). It is in French, but you can automatically translate it and I strongly recommend reading it. 
I don’t know what is the best solution to this issue is, but to #2928 I gave an answer, so you don’t have to face this problem. 
For the posterity…. If someone faces this problem, I recommend avoiding using the decorator @transient lazy because it impacts the performance, and again, look to the article, it’ll give you some insight for your particular problem.

**Comment by atararaksin** [comment]
@kitchdev Hey, I faced a similar issue a few month ago. I had to adopt `S3AttributeStore` for use with `Minio` - a file storage with S3-compatible API. What I did was put a reference to an `S3Producer`  into the attribute store. This doesn't break serializability because `S3Producer` just stores a few String parameters like credentials, etc. You serialize just the producer. And when `s3Client()` of the newly deserialized `MinioAttributeStore` is invoked for the first time, an instance of `S3Client` will be constructed. Something like this: 
```scala
class MinioAttributeStore(override val bucket: String,
                          val s3Producer: S3Producer) extends S3AttributeStore(bucket, "raster-layers") {
  @transient lazy val amazonS3Client: S3Client = s3Producer.produce()
  override def s3Client: S3Client = amazonS3Client
}

class S3Producer(s3AccessKey: String,
                       s3SecretKey: String,
                       s3Url: String) extends Serializable  {

  def produce(): AmazonS3Client = {...}
}
```
And I think that `AmazonS3Producer` needs to be a top-level class to avoid serialization issue. Not sure if I hadn't any other reasons to use a producer class, and it has been a long time already, but thought you might try.

**Comment by jdenisgiguere** [comment]
Greetings all!

Thank you @atararaksin for  your insights.

Based on your comment, I also overrride the `rddWriter` of a `MinioLayerWriter` that extends the `S3LayerWriter`.

@kitchdev , would you accept to close the issue?

**Comment by pomadchin** [comment]
Actually we refactored the way we handle `S3Client` and `ExecutionContext` usages across the entire codebase, so it will be helpful to get familiar with it: https://github.com/locationtech/geotrellis/pull/3007

Closing this issue for now as resolved, feel free to reopen it / to create a new one.
