### ISSUE TITLE
Fix SaveToS3 thread pool usage

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#2936]
Problem Description:
`object SaveToS3` does not behave well when it is being used from more than one partition. The thread pool can get into a state where it is unable to schedule work causing the Spark job to fail with mysteries errors.

Jake is the person that ran into this problem most of all, he might have more detail.

This story is about a working `SaveToS3`

**Comment by echeipesh** [comment]
Addressed by: https://github.com/locationtech/geotrellis/issues/2945
