### ISSUE TITLE
RangeReader SPI

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2940]
We keep writing functions like this:

```scala
    val rr =  javaURI.getScheme match {
      case null =>
        FileRangeReader(Paths.get(javaURI.toString).toFile)      
      
      case "file" =>
        FileRangeReader(Paths.get(javaURI).toFile)


      case "http" | "https" if noQueryParams =>
        HttpRangeReader(new URL(uri))


      case "http" | "https" =>
        new HttpRangeReader(new URL(uri), false)


      case "s3" =>
        val s3Uri = new AmazonS3URI(java.net.URLDecoder.decode(uri, "UTF-8"))
        val s3Client = new AmazonS3Client(AmazonS3ClientBuilder.defaultClient())
        S3RangeReader(s3Uri.getBucket, s3Uri.getKey, s3Client)
```

No one project can depend on all possible implementations of `RangeReader` so this requires an SPI that goes from `URI` to instance of `StreamingByteReader`

This is also going to be required to provide a nice abstraction for `RasterSource` API where can dispatch on `URI` to produce reader of desired type and method.

- [ ] Make SPI interface
- [ ] Implement `hdfs://`
- [ ] Implement `file://` and `/`
- [ ] Implement `s3://`
- [ ] Tests
- [ ] Changelog

Note that the SPI should be able to deal with the usual overload that `file://` could mean use HDFS FileSystem to read the file or to use `FileRangeReader`. The answer here should be considered consistent with the choice elsewhere, whatever that may be.

**Comment by jbouffard** [comment]
@echeipesh Is this an SPI more for `RangeReader` than for `StreamingByteReader`? `RangeReader`s are the ones that take the `URI`. Though, there is an [implicit method](https://github.com/locationtech/geotrellis/blob/master/util/src/main/scala/geotrellis/util/RangeReader.scala#L46) that goes from `RangeReader` to `StreamingByteReader`; but that doesn't let you control the `chunkSize`.

Would it be better to just hide the `RangeReader` and have people just work with `StreamingByteReader`s? Something like this:

```scala
object StreamingByteReader {
  def apply(uri: URI): StreamingByteReader = ???
  def apply(uri: URI, chunkSize: Int): StreamingByteReader = ???
}
```

**Comment by jbouffard** [comment]
This diagram shows my plan for the `StreamingByteReader` SPI. My idea here was to centralize the `canProcess` method via the `Provider` trait, since that logic will be the same regardless of what type of service you want to load. Therefore, that logic will reside in one location depending on the backend (`FileProvider`, `S3Provider`, etc). These can be accessed by the different SPIs.

![streaming-byte-reader-spi](https://user-images.githubusercontent.com/11041248/58889667-4f5ad200-86b7-11e9-815d-63df2f6d6d6e.png)
