### ISSUE TITLE
Add getPixelValue feature

### ISSUE THREAD

**Issue by thomas-maschler** [locationtech/geotrellis#2942]
We have a use case for which we have a bunch of point geometries and we would like to enrich point attributes based on different raster bands. We would like to add pixel values for a given point location as attributes to our points.

We are missing a feature in Geotrellis which would allow to extract a value from a raster source based on a single lat/lon location.

Something like this could do
```
val myPoint = Point(1,1)
val source: RasterSource = ???
val pixelValue = source.getPixelValue(myPoint)
```

**Comment by moradology** [comment]
@echeipesh I'm wondering if the best solution here wouldn't be to promote `get` and `getDouble` (not the most descriptive names...) from `Tile` up to `CellGrid` which is already guaranteed to have a grid of things belonging to some `CellType`.

This would force us to satisfy the requirements here and potentially gets at a fairly deep representational failure.

**Comment by moradology** [comment]
After digging into this for a few hours, it became clear that the API we currently have doesn't have the kind of caching we'd really need to take advantage of (on the GeoTrellis side, at least - GDAL has its own story to tell about caching) for this feature to shine. The alternative would be somewhat wasteful as we'd need to read far more data than we'd report and none of that data would be freely available for future operations

This looks like a feature we'll want to revisit as we continue to sophisticated `RasterSource`s but not one we're likely to implement as of now
