### ISSUE TITLE
EMR maximizeResourceAllocation flag usage

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2943]
There was noticed a behavior change in running a simple ingest on the same EMR cluster but with the different `maximizeResourceAllocation` setting. We need to show what is the difference and to describe its behavior.

**Comment by pomadchin** [comment]
https://github.com/pomadchin/vlm-performance#emr-maximizeresourceallocation-flag-usage-tip

**Comment by CloudNiner** [comment]
This is useful information. Should we write a separate issue to develop a small "Spark tips and tricks" section in the GT docs for 3.0+ release that includes this information? Otherwise it's going to get lost here.

**Comment by pomadchin** [comment]
@CloudNiner :+1: here, we need also to mention our ADR about thread pool usages, since it looks like we’re abusing this setting without thinking too hard about it :d
