### ISSUE TITLE
Separate runtime tiled layer from tiled layer storage

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2948]
Connects: https://github.com/locationtech/geotrellis/issues/2916

As result of discussion above the idea is to separate the classes that define the idea of tiled raster layer from classes that support storing and querying GeoTrellis indexed layers. The main benefit is separation of concerns and opening the ability to create such layers in other ways.

The proposed package separation is as follows:
![image](https://user-images.githubusercontent.com/1158084/58565957-b41cb500-81fd-11e9-9588-ae33c3c6d897.png)
* Edit: Remove FileAttributeStore from `geotrellis.store`

It includes the names of key classes and where they belong.
Helpful feedback would be to point out classes that don't have a clear home in this hierarchy so we can refine it.

- `geotrellis.layer` - Runtime representation of tiled layer and method extensions for working with them on single JVM as collection of `(K,V)`
- `geotrellis.store` - Interfaces and codecs for writing GeoTrellis indexed layers.
- `geotrellis.store.<name>` - Back-end specific store
- `geotrellis.spark.store.<name>` - Back-end specific store classes that require spark  (mostly `LayerWriter` and `LayerReader` that produces `RDD[(K, V)]`

**Comment by jbouffard** [comment]
One small thing that I noticed is that you have `FileAttributeStore` under `geotrellis.store` when I think you meant `AttributeStore`.

**Comment by jbouffard** [comment]
Right now, we're having all of the collections logic be tested in spark, but I image we're going to want that to change. Are we going to have a `geotrellis.store.testkit` for the `store` logic that's a dependency of `geotrellis.spark.test.kit`?

**Comment by echeipesh** [comment]
I'm not sure the testing situation is going to change right away, so all the tests for `geotrellis.store.s3` would be under `geotrellis.spark.store.s3` because they require spark writers to generate the test layers.

In the future it would be nice to cleanup the testkit we currently use by combining `vector` and `raster` into a single `testkit`. It would require creating of non-spark layer writers for the tests to be written without spark. I don't think that should block the spark-split story though.

**Comment by moradology** [comment]
One thing we're going to have to think about as we move towards this proposed structure is the organization - not in API space but rather in the directory structure of the project. It seems to me we've acknowledged that the wall of text that greets users at root of the library is undesirable and that the library should be trimmed down and organized to avoid incidentals like `slick` sitting at the same level as `raster`, e.g.

One option that I've come to like is the organizational strategy of pureconfig: https://github.com/pureconfig/pureconfig

Their approach is:
`core`/ 
`modules/cats`
`modules/other-third-party-support`

An alternative approach that might better fit our case:
`raster/`
`vector/`
`store/` (generic store management)
`stores/hbase` (hbase store management)
`stores/hbase-spark` (hbase store management in the context of a distributed program)

Thoughts? We don't get many chances to move things around so I'd love to get some feedback on these options

**Comment by moradology** [comment]
@echeipesh It might be that the logical organization and the dependency organization we're imagining are in a bit of tension.

For example, it seems as though `LayerDeleter` for a given backend could live on either side of the divide between `geotrellis.store.myBackend` and `geotrellis.store.spark.myBackend`. Logically, it seems like `LayerWriter` and `LayerDeleter` belong together. In practice, though, `LayerDeleter` implementations don't really depend on spark because deletion of even massive amounts of data is rarely something that requires a massive amount of work even when writing to the same backends requires multiple nodes rapidly processing and sending data

**Comment by echeipesh** [comment]
@moradology @pomadchin @jbouffard @jpolchlo Is `LayerId` in `geotrellis.store` or `geotrellis.layer`? It seems to only matter when we store the layers, which leads me to believe the former, but gets imported with `Metadata` an awful lot. And it is, in theory, part of layer identity even if we didn't write it yet or ever (although I haven't written code that uses id like that yet)

**Comment by moradology** [comment]
It seems to me that it is only part of the layer's identity as that layer participates in a *given* storage backend. The same `LayerId` can be used without problem on both S3 and FS, if desired. This makes me think that it is properly a `Store` concept, though this hadn't occurred to me until you brought it up

**Comment by jbouffard** [comment]
I agree that `geotrellis.store` seems to be the best location. As @moradology said, `LayerId` is used to associate a layer with something in storage, so it makes sense to me that be with the IO logic.

**Comment by pomadchin** [comment]
I do agree with @jbouffard and @moradology that `LayerId` is required only for reading / writing things. 

However, I'm trying to compare the current state of the split here: https://github.com/locationtech/geotrellis/tree/feature/spark-split-1/layer/src/main/scala/geotrellis/layer vs https://github.com/locationtech/geotrellis/tree/feature/spark-split-1/store/src/main/scala/geotrellis/store 

It looks like the split is not completely done / done incorrectly. However, it looks like in `layer` we have lots of metadata information: `TileLayer` metadata etc, etc. So definitely the question is in semantics. Is the `LayerID` is a part of the "metadata" that only belongs to storage. 

If it is correct, then `LayerType` should also live in storage? 

Both should live in `storage` according to the definition `storage - Interfaces and codecs for writing GeoTrellis indexed layers`.
