### ISSUE TITLE
Look Into Proposed Package Layout for 3.0

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2950]
#2948 suggests a new API/naming scheme for the 3.0 release. However, before we commit to renaming/moving things, we should make sure that there isn't anything that won't fit into the the target project structure. This [branch](https://github.com/locationtech/geotrellis/tree/feature/collections-split), which contains the current spark split work, should be reviewed against the diagram in the mentioned issue to see if there are types that aren't correctly placed. If everything looks okay, we can implement the required changes. Otherwise, we may have to rethink the project structure for 3.0.

**Comment by moradology** [comment]
I've gone through the relevant packages a few times and aside from the peculiarity of S3's `LayerCopier` being something we should just mark as `unsafe` and `terribly inadvisable` the layer/store distinction seems to hold water, as does the collections/values vs RDDs distinction.

I think we can safely close this issue and conduct discussions about minor tweaks/modifications in #2948

**Comment by jbouffard** [comment]
I agree with @moradology, the distinction between store/spark and collections/RDDs is strong enough that we can structure our library around the differences. In addition, this package layout will allow a user to utilize different backends using the tools that they need (store vs spark), which is something that we can't do right now.

This issue can also be closed.
