### ISSUE TITLE
Get Rid of Compiler Warningings in the vector Package

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2965]
When implementing the easy imports for the `vector` package, there was an oversight, and `WKT` and `WKB` were imported twice in the same file. This leads to the following warning when compiling:

```
[warn] /home/jake/Documents/projects/geotrellis/vector/src/main/scala/geotrellis/vector/io/package.scala:19:33: imported `WKB' is permanently hidden by definition of value WKB in package vector
[warn] import geotrellis.vector.io.wkb.WKB
[warn]                                 ^
[warn] /home/jake/Documents/projects/geotrellis/vector/src/main/scala/geotrellis/vector/io/package.scala:20:33: imported `WKT' is permanently hidden by definition of value WKT in package vector
[warn] import geotrellis.vector.io.wkt.WKT
```

We should should get remove the double import so those warnings will go away.

**Comment by jbouffard** [comment]
We're probably going to want to get this resolved before the 3.0 release.

**Comment by jpolchlo** [comment]
This will be handled by #2932

**Comment by pomadchin** [comment]
Closed via https://github.com/locationtech/geotrellis/pull/2932
