### ISSUE TITLE
Two tiles merge

### ISSUE THREAD

**Issue by Silence-Soul** [locationtech/geotrellis#2978]
I just contacted Geotrellis
I have a simple question.
I have two tiff files A and B. I have already stored the A file in the Accumulo according to the [example.](https://github.com/geotrellis/geotrellis-landsat-tutorial)
Part of the B file is coincident with A, and I now want to merge the coincident parts. How do I operate? Or provide a complete example。

thanks very much

**Comment by pomadchin** [comment]
Adding [some context here](https://gitter.im/geotrellis/geotrellis?at=5d03c80ebc56c731f8ba7e40). The question was about the `AccumuloLayerWriter.update` function usage. The merge function in the `update` function arguments should look like this: `(ltile, rtile) => ltile.merge(rtile)` or in short `_ merge _`
