### ISSUE TITLE
Find a handful of core/introductory topics and spill extra ink for them

### ISSUE THREAD

**Issue by moradology** [locationtech/geotrellis#2985]
Our documentation has a lot of content but we've found that new users consistently have a difficult time getting started. Though there *is* a lot of content about GeoTrellis out there, the documentation doesn't properly link between topics to reinforce important concepts.

We should find a few highly important/salient topics and ensure that they are repeatedly brought up and linked to throughout all the documentation

**Comment by CloudNiner** [comment]
superseded by #3304
