### ISSUE TITLE
Extent.reproject is unsafe

### ISSUE THREAD

**Issue by rossbernet** [locationtech/geotrellis#2990]
https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/reproject/Reproject.scala#L64-L65

This is the safe way to do it.
val wgs84extent: Extent = ReprojectRasterExtent(self.nativeRE, self.nativeCrs.head, LatLng).extent

This is only possible on `RasterExtents` the docs for `Extent.reproject` should at least mention this as a concern.

**Comment by moradology** [comment]
`RasterExtent`, a concept that only exists in `raster`, is not available within the `vector` module. As such, I'll make note of the issue rather than reimplement behavior in terms of what we'd expect in the case of a gridded extent.
