### ISSUE TITLE
CRS comparison is extremely expensive

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#3022]
On RasterFrames we are having major performance issues with comparisons between `CRS`s, and are almost [out of hacks to work around it](https://github.com/locationtech/rasterframes/blob/develop/core/src/main/scala/org/locationtech/rasterframes/model/LazyCRS.scala).  I suspect our usage patterns have broken past assumptions on this. Here's some more context, including some profiling results: https://github.com/locationtech/rasterframes/issues/134. 

In RasterFrames we use a type called [`ProjectedRasterTile`](https://github.com/locationtech/rasterframes/blob/develop/core/src/main/scala/org/locationtech/rasterframes/tiles/ProjectedRasterTile.scala) which is what is pushed around the most through the API. This results in one or more CRSs being implicitly included in every row. When `join`s happen, invariably CRSs are involved, where `CRS.equals` is usually called, which is **extremely** expensive. Hence the use of `LazyCRS`. But determining `!=` between CRSs is still very expensive.

I've thought about hitting the GT codebase to construct a fix, but that's pretty delicate code and I'm wary about doing it on my own. Interested in discussion on this.

**Comment by pomadchin** [comment]
@metasim is it related to https://github.com/locationtech/geotrellis/issues/2890? Do you also have some benchmarks somewhere? They could really help to make it done by the 3.0 release as it sounds very critical.

**Comment by metasim** [comment]
@pomadchin #2890 is a separate use case.... indeed slow to read, but this ticket is about `equals`, something done after reading. #2890 is ameliorated somewhat by the caching that goes on.

Here are the benchmarks from RasterFrames:

## Standard GeoTrellis
![](https://user-images.githubusercontent.com/131013/59033648-25c8b480-8837-11e9-92cd-d17d5ef65a87.png)

## With RasterFrame Hacks

![](https://user-images.githubusercontent.com/131013/59038605-47c73480-8841-11e9-86e1-bedd7ec2319b.png) Sorry, added

**Comment by metasim** [comment]
Benchmark code:

https://github.com/locationtech/rasterframes/blob/develop/bench/src/main/scala/org/locationtech/rasterframes/bench/CRSBench.scala

**Comment by pomadchin** [comment]
@metasim appreciate it! do you know it was in the codebase forever or it was some sort of regression?

**Comment by metasim** [comment]
@pomadchin In the codebase forever.... we broke it with DataFrames containing a million CRSs 😈 .

**Comment by metasim** [comment]
Again, see here for the hacks we've been using:

https://github.com/locationtech/rasterframes/blob/develop/core/src/main/scala/org/locationtech/rasterframes/model/LazyCRS.scala
