### ISSUE TITLE
reprojectExtentAsPolygon() - method going into infinite loop 

### ISSUE THREAD

**Issue by rajindersaini** [locationtech/geotrellis#3023]
When a [reproject](https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/reproject/Reproject.scala) method is called with specific extent it is going into infinite recursion. 
Expectation: This should return an appropriate exception.  

Example code:
```scala
val reader = GeoTiff.readMultiband("/Users/rajinder.saini/dev/geotiff-utils/test-resources/outside-utm.tif")

val extant = reader.projectedExtent.reproject(LatLng)
//The calculated extent is given below. 
val ex = Extent.fromString("0.0, 0.0, 2606.0, 2208.0")
    
// This call goes into infinite recursion. 
val tile =  reader.tile.reproject(ex, reader.crs, WebMercator)    
```

**Comment by pomadchin** [comment]
hey @rajindersaini! can you upload data somewhere and to update your post with a completely compiling example? 

Also, can you provide an exception message you're seeing and what GeoTrellis version do you use?

**Comment by jpolchlo** [comment]
Also quite important to know the value of `reader.crs`

**Comment by rajindersaini** [comment]
Please find attached the sample here - https://climate.box.com/s/srp57j3c1e9jfyna40c0e0pge5ycmidv

**Comment by rossbernet** [comment]
Does not appear that this can be accessed:

![image](https://user-images.githubusercontent.com/8103418/61329438-4b0ff180-a7eb-11e9-839b-0ecee7e2f69c.png)

**Comment by rossbernet** [comment]
It looks like we may be able to access this by signing up for a free business trial, but do you have an alternative, more accessible way of sharing this?

![image](https://user-images.githubusercontent.com/8103418/61329554-9aeeb880-a7eb-11e9-9beb-4fabe6d85c52.png)

**Comment by rajindersaini** [comment]
Sorry about that - I updated the sharing setting - https://climate.box.com/s/srp57j3c1e9jfyna40c0e0pge5ycmidv

**Comment by jmt-vanderlee** [comment]
I might be having the same issue but only when using `HadoopLayerWriter` to write to GCS.
Writing locally with `FileLayerWriter` works fine.

Calling reproject causes the spark job to hang indefinitely. 
```
val topLeftPntLatLong = Point(rasterRawMetaData.extent.xmin, rasterRawMetaData.extent.ymax)
val currentUtmInfo = new UtmInfo {
  override val zone: Either[Int, Int] = geotrellis.proj4.util.UTM.getZone(topLeftPntLatLong.x, topLeftPntLatLong.y)
  override val crs: CRS = geotrellis.proj4.util.UTM.getZoneCrs(topLeftPntLatLong.x, topLeftPntLatLong.y)
  override val epsgCode: Int = crs.epsgCode.get
}

inputRawRdd.reproject(CRS.fromEpsgCode(currentUtmInfo.epsgCode))
```
where the epsgCode  = 32611

**Comment by pomadchin** [comment]
hey @jmt-vanderlee are you sure that you're calling it without the `tileToLayout` function follow up call before persistence?

**Comment by jmt-vanderlee** [comment]
@pomadchin upon further investigation it appears to be linked to an incorrect LayoutDefinition being passed to tileToLayout.

**Comment by rajindersaini** [comment]
Is there any update on this issue? When this is expected to be fixed?

**Comment by pomadchin** [comment]
hey @rajindersaini it is not planned for the current sprint now, it should be probably done by the `GT 3.0` release.

**Comment by rajindersaini** [comment]
Thanks for update @pomadchin

**Comment by rajindersaini** [comment]
@pomadchin Are we still tracking this issue in 3.0 Release?

**Comment by pomadchin** [comment]
hey @rajindersaini here is some summary: (also I want to mention @jpolchlo)

The given tiff gdalinfo (pay attention to Invalid angle warns):

```
Driver: GTiff/GeoTIFF
Files: out.tiff
Size is 2606, 2208
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (0.000000000000000,2208.000000000000000)
Pixel Size = (1.000000000000000,-1.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (       0.000,    2208.000) (  0d 0' 0.01"E,Invalid angle)
Lower Left  (   0.0000000,   0.0000000) (  0d 0' 0.01"E,  0d 0' 0.01"N)
Upper Right (    2606.000,    2208.000) (Invalid angle,Invalid angle)
Lower Right (    2606.000,       0.000) (Invalid angle,  0d 0' 0.01"N)
Center      (    1303.000,    1104.000) (Invalid angle,Invalid angle)
Band 1 Block=2606x1 Type=Byte, ColorInterp=Gray
Band 2 Block=2606x1 Type=Byte, ColorInterp=Undefined
Band 3 Block=2606x1 Type=Byte, ColorInterp=Undefined
```

The code to reproduce behavior:

```scala
import geotrellis.proj4._
import geotrellis.vector.reproject._


val ext = Extent(0.0, 0.0, 2606.0, 2208.0)
// we declare the extent as coords in LatLng, see issue #3023
// though valid
// - longitudes are in [-180, 180] degrees ragne
// - latitudes are in [-90, 90] degrees range

val transform = Transform(LatLng, WebMercator)
// fails into the recursion stack
Reproject.reprojectExtentAsPolygon(ext, transform, 0.001)
```

The reason is here:

```scala
def refine(p0: (Point, (Double, Double)), p1: (Point, (Double, Double))): List[(Point, (Double, Double))] = {
  val ((a, (x0, y0)), (b, (x1, y1))) = (p0, p1)
  val m = Point(0.5 * (a.x + b.x), 0.5 * (a.y + b.y))
  val (x2, y2) = transform(m.x, m.y)

  val deflect = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1) / sqrt(pow(y2 - y1, 2) + pow(x2 - x1, 2))
  val length = sqrt(pow(x0 - x1, 2) + pow(y0 - y1, 2))

  val p2 = m -> (x2, y2)
  // deflect value will always be NaN
  // and NaN is always < relError
  // it blows up the stack
  // (NaN / 2.0037508342789244E7 < 0.001): false
  // (NaN / 2.0037508342789244E7 < 0.001): false
  // (NaN / 2.0037508342789244E7 < 0.001): false
  // (0.0 / 2.0037508342789244E7 < 0.001): true
  // (NaN / 0.0 < 0.001): false
  // ...
  // (NaN / 0.0 < 0.001): false
  if (deflect / length < relError) {
    List(p2)
  } else {
    refine(p0, p2) ++ (p2 :: refine(p2, p1))
  }
}
```

So the answer to your question would be that the data you provided is wrong, and the max thing we can try to do is to avoid this infinite recursion happening due to NaNs. But mb @jpolchlo knows better what to do in this situation. I won't say that it is a critical bug, since it should not work, but probably the exception can be different (for instance we can catch NaN and throw an exception).

**Comment by rajindersaini** [comment]
@jpolchlo We have an API which is exposed to external partners. In these cases, if we can get a correct exception we can tell partners that they are sending incorrect data. There are many files likes this send by our partners. It would be great if you could throw an exception. This is really blocking our data pipeline. Please add the exception instead of infinite recursion.

**Comment by pomadchin** [comment]
@rajindersaini all right I’ll look into it tomorrow, mb it is a straightforward thing to do and it won’t break tests.

**Comment by pomadchin** [comment]
@rajindersaini if you'll look into the stack trace: 

```
java.lang.StackOverflowError
  at org.locationtech.proj4j.datum.Datum.getTransformType(Datum.java:152)
  at org.locationtech.proj4j.datum.Datum.isEqual(Datum.java:186)
  at org.locationtech.proj4j.BasicCoordinateTransform.datumTransform(BasicCoordinateTransform.java:180)
  at org.locationtech.proj4j.BasicCoordinateTransform.transform(BasicCoordinateTransform.java:153)
  at geotrellis.proj4.Proj4Transform$$anonfun$apply$2.apply(Transform.scala:39)
  at geotrellis.proj4.Proj4Transform$$anonfun$apply$2.apply(Transform.scala:36)
  at geotrellis.vector.reproject.Reproject$.refine$1(Reproject.scala:97)
  at geotrellis.vector.reproject.Reproject$.refine$1(Reproject.scala:107)
  ...
  at geotrellis.vector.reproject.Reproject$.refine$1(Reproject.scala:107)
```

It shows that you already can catch the `java.lang.StackOverflowError` exception here.

**Comment by jpolchlo** [comment]
Hi, @rajindersaini.  I'd like to get some time to look at this, but have been busy with other stuff.  We've only tested the function that is infinitely recursing with "normal" inputs.  It seems that you're supplying somewhat pathological inputs?  We surely can limit the number of regressions and throw instead if the limit is hit.  That would be the quick solution.  I'm particularly interested in seeing why these inputs go wrong, but that's academic at this point.  

@pomadchin , do you think you could handle limiting the number of recursions in reprojectExtentAsPolygon?  If that's even where the problem is?

**Comment by rajindersaini** [comment]
Hi @jpolchlo we accept tiff files from third parties via APIs. I am not sure what is the state of these files. I am able to load these via GDAL without any issues. That is the argument our partner are giving to us. So they want to know what the real issue is. Handling StackOverflow error might not be a good idea for me as a library user. I guess eventually you will be able to figure out the issue and perhaps you should limit the recursion anyways? if not anything else the depth of the recursion?

**Comment by pomadchin** [comment]
@jpolchlo we can throw on `NaN`, or make a proper `NaN` comparison to go out of the recursion loop. The last one seems more correct to me. The result would be incorrect, but there would be no exception thrown, since we can't now is transformation is valid or not.

**Comment by rajindersaini** [comment]
Would it be possible for the geotrellis code to validate the extent against the crs within
Reproject.reprojectExtentAsPolygon(ext, transform, 0.001)
since both the extent and the crs (via the transform) are available to the code?

**Comment by pomadchin** [comment]
@rajindersaini it is not possible to know for sure does the extent corresponds to the input crs in general (that’s why gdal silently tries to do everything). it is more a user application logic; for instance you can precheck that if users says that the extent is in lat-long, than longs should be in [-90;90] range and lats in [-180;180].

**Comment by rajindersaini** [comment]
@pomadchin We clearly tell our partner to provide GeoTIFF in UTM with WGS84 datum. How do we verify that files are in this format? 
` val reader = GeoTiff.readMultiband(...)
  val crs = reader.crs // is this object from which I should verify the CRS?
`
As pointed out earlier to precheck the extent can we do like this below 
`val extent = reader.projectedExtent.reproject(LatLng)`
and verify that extent should be in lat-long [-90;90] range and longs in [-180;180].

**Comment by rajindersaini** [comment]
@pomadchin - I just wanted to let you know that the above file works fine with 

1. scala version := "2.11.8"
2.   "org.locationtech.geotrellis" %% "geotrellis-spark"  % "2.0.0",
    "org.locationtech.geotrellis" %% "geotrellis-s3"     % "2.0.0",
    "org.apache.spark"            %% "spark-core"        % "2.1.0"
Do you think this bug was introduced in later versions?

**Comment by pomadchin** [comment]
Hey @rajindersaini , yes it it possible that there was a behavior change; but even though it doesn’t throw, it should produce an incorrect result.

**Comment by pomadchin** [comment]
With GeoTrellis 2.0 the following code also goest into the recursion stack: 

```scala
import geotrellis.proj4._
import geotrellis.vector._
import geotrellis.vector.reproject._


val ext = Extent(0.0, 0.0, 2606.0, 2208.0)
// fails into the recursion stack
ProjectedExtent(ext, LatLng).reprojectAsPolygon(WebMercator)
```

**Comment by jpolchlo** [comment]
@pomadchin Is that a surprise?  This extent is way out of range for LatLng.

**Comment by pomadchin** [comment]
@jpolchlo it is not a surprise, just answering questions and leaving comments.
