### ISSUE TITLE
RangeReader cannot handle file:/// URI

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#3031]
Works:
```scala
import geotrellis.util.RangeReader
val reader = RangeReader(new java.net.URI("/tmp/test.json"))
reader.readAll
```

Fails:
```scala
import geotrellis.util.RangeReader
val reader = RangeReader(new java.net.URI("file:///tmp/test.json"))
reader.readAll
```

```
java.io.FileNotFoundException: file:/tmp/test.json (No such file or directory)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at geotrellis.util.FileRangeReader.readClippedRange(FileRangeReader.scala:35)
  at geotrellis.util.RangeReader$class.readAll(RangeReader.scala:47)
  at geotrellis.util.FileRangeReader.readAll(FileRangeReader.scala:31)
  ... 40 elided
```

**Comment by jbouffard** [comment]
This error appears to be due to with how we convert the `URI` to a `File` in `FileRangeReaderProvider`: https://github.com/locationtech/geotrellis/blob/master/util/src/main/scala/geotrellis/util/FileRangeReaderProvider.scala#L31

**Comment by jbouffard** [comment]
It looks like just changing `uri.toString` to `uri` will resolve this problem:

```
scala> val uri = new java.net.URI("file:///tmp/test.json")
uri: java.net.URI = file:///tmp/test.json

scala> Paths.get(uri).toFile
res13: java.io.File = /tmp/test.json
```

**Comment by jbouffard** [comment]
Actually, upon further review, the solution is a bit more complicated. `Paths.get` is able to accept a `URI`, [but it must have predetermined parameters](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.net.URI)) or else it will throw. Therefore, we will need to do some checks to determine the proper way to convert the `URI` to a `File`.

**Comment by echeipesh** [comment]
> Actually, upon further review, the solution is a bit more complicated. `Paths.get` is able to accept a `URI`, [but it must have predetermined parameters](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.net.URI)) or else it will throw. Therefore, we will need to do some checks to determine the proper way to convert the `URI` to a `File`.

Which parameters are you thinking about, the scheme? I believe `file:/` always refers to the default file system, but I'm not sure if there is another concern.

**Comment by jbouffard** [comment]
@echeipesh The `Scheme` as well as the `Authority`. From the docs, whether or not `Paths.` accepts a `URI` with an `Authority` is OS dependent. In the case of Linux, you can't have one in the `URI`.

I believe you're correct that `file:` always refers to the local file system.

**Comment by echeipesh** [comment]
Ah gotcha. I'm not sure I'd ever expect `file:` URI to have `Authority`, not sure what OS would make use of that. But the `canProcess` method is the guard to make sure that the URI is in correct shape that won't throw.

**Comment by jbouffard** [comment]
@echeipesh I'm not sure if we want to utilize `canProcess` here to ensure that the `URI`s are in the correct shape. This is because there are valid `URI`s that `Paths.get` cannot accept. For example:

```
scala> Paths.get(new URI("file:good-cropped.tif"))
java.lang.IllegalArgumentException: URI is not hierarchical
  at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:48)
  at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
  at java.nio.file.Paths.get(Paths.java:138)
  ... 40 elided
```

So it seems to me that we need to have additional logic that constructs the `File` using something other than `Paths.get`.
