### ISSUE TITLE
Borders around output geotiffs

### ISSUE THREAD

**Issue by marygriffus** [locationtech/geotrellis#3035]
Ran into this problem ingesting a tiff, reprojecting, and outputting as tiff. When I output, it adds a black border around the edges. The initial tiff does not have nodata set, but if I just ingest, convert to rdd, and convert back to geotiff, it seems to work without issues.

```
val baseRDD: RDD[(ProjectedExtent, Tile)] = HadoopGeoTiffRDD.spatial(tilesDir, options)
val meta: TileLayerMetadata[SpatialKey] = TileLayerMetadata.fromRDD(baseRDD, floatingLayout)._2
val gridded: RDD[(SpatialKey, Tile)] = baseRDD.tileToLayout(meta, NearestNeighbor)
val inputRDD: TileLayerRDD[SpatialKey] = new ContextRDD(gridded, meta).reproject(crs, floatingLayout, NearestNeighbor)._2
val layout = inputRDD.metadata.layout

inputRDD.foreach({
    case (key, tile) => {
      val extent = key.extent(layout)
      val gTiff = GeoTiff(tile.withNoData(Option(0)), extent, inputRDD.metadata.crs)
          GeoTiffWriter.write(gTiff, filepath)
      }
})
```

If i use the above but take out the reprojection and .withNoData(Option(0)), it just outputs a tiff with no borders added.
I asked about this on Gitter, and it seems to work fine with other geotiffs without nodata set correctly, but I cannot share the data that this is being used on. If there are any other pieces of metadata that will help troubleshoot, however, I can add those.

Example of border:
<img width="119" alt="Screen Shot 2019-07-22 at 4 02 42 PM" src="https://user-images.githubusercontent.com/17263295/61661517-4095a200-ac9a-11e9-9f63-ae32f2a18d88.png">

**Comment by pomadchin** [comment]
Hey @marygriffus thanks for reporting! can you provide a `gdalinfo`? (but with erased extent, since it probably can be a sensitive information, but with all other information like projection (with a proj4 string), band types, etc)

**Comment by marygriffus** [comment]
Hi, thanks so much for helping! Let me know if any other info would be helpful.

```
Driver: GTiff/GeoTIFF
Files: xxx.tif
Size is 5402, 5402
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (XXX.XX,XX.XX)
Pixel Size = (0.000046296296296,-0.000046296296296)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_SOFTWARE=IMAGINE TIFF Support
Copyright 1991 - 1999 by ERDAS, Inc. All Rights Reserved
@(#)$RCSfile: etif.c $ $Revision: 1.10.1.9.1.9.2.11 $ $Date: 2004/09/15 18:42:01EDT $
  TIFFTAG_XRESOLUTION=1
  TIFFTAG_YRESOLUTION=1
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( XXX.XXX,  XX.XXX) (XE, XN)
Lower Left  ( XXX.XXX,  XX.XXX) (XE, XN)
Upper Right ( XXX.XXX,  XX.XXX) (XE, XN)
Lower Right ( XXX.XXX,  XX.XXX) (XE, XN)
Center      ( XXX.XXX,  XX.XXX) (XE, XN)
Band 1 Block=5402x1 Type=Byte, ColorInterp=Palette
```
