### ISSUE TITLE
import errors with default sbt console 

### ISSUE THREAD

**Issue by soxofaan** [locationtech/geotrellis#3051]
(disclaimer: I'm rather new to scala and sbt so I might be doing something wrong)

Based on quickstart docs (https://docs.geotrellis.io/en/latest/tutorials/quickstart.html) I tried to run sbt's `console` in the root of geotrellis project (instead of in the geotrellis-sbt-template project)  and got these errors:

```
$ ./sbt
...
geotrellis > console
[info] Starting scala interpreter...
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> <console>:12: error: not found: value geotrellis
             import geotrellis.raster._
                    ^
<console>:13: error: not found: value geotrellis
             import geotrellis.vector._
                    ^
<console>:14: error: not found: value geotrellis
             import geotrellis.proj4._
                    ^
<console>:15: error: not found: value geotrellis
             import geotrellis.spark._
                    ^
Interpreter encountered errors during initialization!

[error] (Thread-3) java.lang.InterruptedException
[error] java.lang.InterruptedException
[error] 	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:879)
[error] 	at scala.tools.nsc.interpreter.SplashLoop.run(InteractiveReader.scala:77)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

which is pretty confusing (for me as a newcomer) because these projects (raster, vector, ...) appear to build without problems.

After googling/messing around, I found out that problem goes away when I add the following to 
`Project("geotrellis")`:
```
  dependsOn(raster, vector, proj4, spark).
```

Is that something useful to make a PR for, or is that the wrong kind of solution (or there isn't even a problem) ?

**Comment by pomadchin** [comment]
Hey @soxofaan the right solution would be to remove [these lines](https://github.com/locationtech/geotrellis/blob/master/build.sbt#L134-L142). I don't think it makes sense to aggregate and depend on all projects at the same time.

**Comment by CloudNiner** [comment]
@pomadchin do we have an issue somewhere that encapsulates updating the instructions for which project template to start with? It looks like the one we currently link to, https://github.com/geotrellis/geotrellis-sbt-template, is still setup to use GT 1.0 and was last updated in 2017. We also have two g8 templates in the geotrellis org:
- https://github.com/geotrellis/geotrellis.g8: Ancient, updated in 2013
- https://github.com/geotrellis/geotrellis-spark-job.g8: Specific to spark jobs, will need updating to gt3.0 on release

I found https://github.com/locationtech/geotrellis/issues/2985 but it appears to be more about example topics. Perhaps we should create a separate issue, or morph this one into one about clearifying the correct starter template to use if you need one, and to get said template up to date?

**Comment by pomadchin** [comment]
@CloudNiner I think we have _smth like that_ but it is not consolidated; Probably we need to create an Epic that will describe the need in the following:

1. Describe instructions how to write Spark applications and to describe a template for doing this https://github.com/geotrellis/geotrellis-spark-job.g8
2. Template and instructions for non a non-Spark application (mb 1. already incapsulates it so there are no needs)
3. To update instructions how to start a GeoTrellis Zeppelin cluster (https://github.com/locationtech/geotrellis/issues/2976)

This issue I think is a bit different, since there was even a similar [SO issue](https://stackoverflow.com/questions/56171908/geotrellis-spark-is-not-a-member-of-package-geotrellis-when-pulled-from-curren).

**Comment by CloudNiner** [comment]
👍 as noted in standup I'll create epic/issues today or early tomorrow.
