### ISSUE TITLE
Read tiff fail reason

### ISSUE THREAD

**Issue by Silence-Soul** [locationtech/geotrellis#3066]
Hey, @pomadchin #3065 The reason maybe when the offset is read from the IFH of the TIFF.
Bytes 4-7 are the addresses of the first offset. Below is the hexadecimal content of the TIFF file.
Bytes 4-7 are b0, 23, af, 84. 
![2](https://user-images.githubusercontent.com/6566601/64064641-c19b6e00-cc36-11e9-9f5f-bf2abbb46f96.PNG)
### **The decimal should be 176, 23, 175, 132.**
But the decimal value obtained during the debugging negative number. 
The decimal: -80, 35, -81, -124
![1](https://user-images.githubusercontent.com/6566601/64064629-9f095500-cc36-11e9-9347-1991fac9a2b7.PNG)
### **These negative numbers correspond to hexadecimal ffffffb0, 23, ffffffaf, ffffff84.**

byte is 8 bits and int is 32 bits, when the byte may be converted to int or byte and int type operation, it will expand the byte memory high bit complement 1 (that is, by sign bit complement) to 32 bits.
So `byte & 0xff `

0xff can set the high 24 bits to 0, and the lower 8 bits remain unchanged, ensure the consistency of the binary data.

        String path ="d:\\tmp\\18FEB28040147-P2AS-058185565030_01_P001.TIF";
        FileInputStream in = new FileInputStream(path);
        DataInputStream din = new DataInputStream(in);
        byte[] bytes = new byte[10];
        din.read(bytes, 0, 8);
        for (byte b: bytes){
            String str1 = Integer.toHexString(b);
            System.out.print(str1);
            System.out.print("--------");
            System.out.print("HEX:"+Integer.parseUnsignedInt(str1, 16));
            System.out.print("              ");
            String str2 = Integer.toHexString((b & 0xff) + 256).substring(1);
            System.out.print(str2);
            System.out.print("--------");
            System.out.println("HEX:"+Integer.parseUnsignedInt(str2, 16));
        }
![3](https://user-images.githubusercontent.com/6566601/64064743-2f946500-cc38-11e9-892b-7cc62d78e3d5.png)

**Comment by pomadchin** [comment]
Closing this one, since it duplicates #3065
