### ISSUE TITLE
RasterSource reads on an overview resolution return nodata / incorrect values

### ISSUE THREAD

**Issue by Lknechtli** [locationtech/geotrellis#3075]
# Description
RasterSource reads appear to consistently fetching 0/NaN values when fetching from an overview.
This doesn't appear on all tiffs, but virtually all Landsat tiffs exhibit this behavior, independent of the type of RasterSource used.
This has been tested with multiple tiffs, both GeoTiffRasterSource and GDALRasterSource.

This does not appear occur when using the native resolution instead of an overview.

# Reproduction
Run the following code in a repl on the `master` branch
Fetching any value on the specified overview results in Nodata, None, NaN, or 0.0 values instead of expected actual data.

```
def testTiff(url: String) = {
  import geotrellis.raster.gdal.GDALRasterSource;
  val rasterSource = GDALRasterSource(url)
  val idealResolution = rasterSource.resolutions.minBy(res => scala.math.abs(250000 - res.rows * res.cols))
  val tile = rasterSource.read(idealResolution.gridBounds).get.tile
  val histogram = tile.histogramDouble(80)
  val band0Hist = histogram(0)
  println(s"Band 0 histogram min: ${band0Hist.minValue}, max: ${band0Hist.maxValue}, mean: ${band0Hist.mean}")
  println(s"Middle of tile pixel: ${tile.band(0).getDouble(tile.band(0).cols / 2, tile.band(0).rows / 2)}")
}

testTiff("s3://landsat-pds/c1/L8/205/042/LC08_L1TP_205042_20190119_20190119_01_RT/LC08_L1TP_205042_20190119_20190119_01_RT_B4.TIF")
```
I can provide additional test files, but they aren't all publicly available.

**Comment by jisantuc** [comment]
For comparison, here is the histogram of the full resolution image according to rasterio:

![hist](https://user-images.githubusercontent.com/5702984/64982833-ba09d500-d884-11e9-9a03-044158141110.png)

There are a lot of zeros! But also a lot of non-zeros.

**Comment by Lknechtli** [comment]
and this is what it looks like in qgis
![image](https://user-images.githubusercontent.com/4392704/64982977-77002f80-d88d-11e9-92f6-2d51c8aa1083.png)

**Comment by Lknechtli** [comment]
My bad. We got confused with how read work. Switching to using resampleToGrid(...).read() fixed things.
