### ISSUE TITLE
Update computeResolution in cost distance

### ISSUE THREAD

**Issue by jmtaysom** [locationtech/geotrellis#3103]
The current compute resolution in iterativeCostDistance calculates the resolution of the cell sizes as if it were at the equator. The further away from the equator the larger it estimates the cell size. Around 40 degrees latitude it will compute a 10 meter cell as being over 13 meters. However in another function there is a different computeResolution function that more correctly calculates the cell size by scaling the value based on the average latitude of the tile. This takes a 30% error at 40 degrees latitude to less than a 2% error. 

Replacing the inaccurate computeResolution with the more accurate other compute resolution will solve the issue.

**Comment by echeipesh** [comment]
@jmtaysom thank you for the report. 
Could you include links to the function you're talking about in the issue?

Also, would you be interested in preparing PR for this? [Contributing](https://geotrellis.readthedocs.io/en/latest/CONTRIBUTING.html) would require signing the ECA with Eclipse. We could cut a back-port release for you if its needed.

**Comment by jmtaysom** [comment]
The inaccurate one is
https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala#L76

The more accurate one is 
https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/viewshed/IterativeViewshed.scala#L131

I am working on the PR for it. I have signed the ECA and am not working on the PR.
