### ISSUE TITLE
Create 2.x release with LazyLogger removed from Tile hierarchy.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#3114]
RasterFrames has an issue when shading is applied to SLF4J/ScalaLogging, which therefore changes the `Tile` type definition. As a result, Spark SQL `DataSet[T]` that contains `Tile` fails due to the `Encoder[T]`  API using Scala reflections `TypeTag[T]`s, which checks every type up the inheritance hierarchy between what was there at compile time vs what's there at runtime. IOW, Spark + Scala detects that the type hierarchy has changed, and throws an exception.

Once done, this is hopefully addressed:

https://github.com/locationtech/rasterframes/issues/293

**Comment by metasim** [comment]
Couldn't find an existing ticket for removing LazyLogger from type hierarchy, but feel like there was one...

**Comment by pomadchin** [comment]
There was no, thank you for creating this one.

**Comment by metasim** [comment]
I am making a leap of faith that this does address all the issues we have with shading and DB deployment. If you'd prefer to do an "RC" release and we test against that, I'm game.

**Comment by pomadchin** [comment]
@echeipesh we can recover the old [LazyLogger](https://github.com/locationtech/geotrellis/blob/2.0/util/src/main/scala/geotrellis/util/LazyLogging.scala) we had in 2.0.

Tbh I'm really curious why there are problems with shading this dependency and why it is not possible to shade it.

**Comment by metasim** [comment]
@pomadchin 

> we can recover the old LazyLogger we had in 2.0. It would be a pretty straightforward shift back.

This is the not problem at hand (but may be one workaround).  It's the fact that `Tile` inherits from any kind of class that gets renamed during the shading process. This is because Spark SQL's API `Encoder[T: TypeTag]` captures the type hierarchy of `Tile` at *compile* time  (when `Encoder[Tile]` is resolved), stored in some `scala.reflection` data structure. At run time, when the function is called, `scala.reflection` tells the `Encoder[T]` api that the run time class doesn't match the compile time class, because `LazyLogger` has been shaded.

My suggestion is to change the relationship between `Tile` and `LazyLogger` such that it is a "has a" relationship instead of a "is a" one.  

Example: https://github.com/s22s/rasterframes/commit/c07ccea238b900473eb471b7b97b99549e6ceca8#diff-6d174d260f23bb8ae4ec3061b03365f8R36-R39

**Comment by metasim** [comment]
Here's the exception site:

```
java.lang.AssertionError: assertion failed: unsafe symbol Logger (child of package scalalogging) in runtime reflection universe
	at scala.reflect.internal.Symbols$Symbol.<init>(Symbols.scala:184)
	at scala.reflect.internal.Symbols$TypeSymbol.<init>(Symbols.scala:3009)
	at scala.reflect.internal.Symbols$ClassSymbol.<init>(Symbols.scala:3201)
	at scala.reflect.internal.Symbols$StubClassSymbol.<init>(Symbols.scala:3496)
	at scala.reflect.internal.Symbols$Symbol.newStubSymbol(Symbols.scala:498)
	at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler
```

(from https://github.com/locationtech/rasterframes/issues/293#issuecomment-523114815)

**Comment by echeipesh** [comment]
@metasim https://github.com/locationtech/geotrellis/releases/tag/v2.3.3 is now released to LocationTech and maven central.
