### ISSUE TITLE
Upgrade Cats Ecosystem Dependencies

### ISSUE THREAD

**Issue by notthatbreezy** [locationtech/geotrellis#3139]
There are a few libraries in the `cats`/`typelevel` ecosystem that would be great to see upgraded as binary compatibility concerns prevent us from upgrading some of the libraries we use pretty heavily in Raster Foundry and other projects:

 - `circe`: (core - 0.12.3, generic-extras - 0.12.2)
 - `fs2`: 2.0.1
 - `cats`: 2.0
 - `cats-effect`: 2.0

I think that's all of them - this might depend on https://github.com/locationtech/geotrellis/pull/3132 - I upgraded this on a branch and as far as I could tell absent the issues around `geomesa` and `geowave` subprojects only working for scala `2.11` there was only one minor change required in `store` to get things compiling.

**Comment by echeipesh** [comment]
This is potentially longer term thing. `circe-0.12.3` is not published for scala 2.11. The last version of `circe` published for scala 2.11 is `0.11.1`.

This places the GT library in a difficult position because we can't drop scala 2.11 support until spark is deployable with scala 2.12, which is not expected until spark version 2.5 I believe (~ 6 months ?)

I'm not sure what the reasonable solution here is. We could devise some kind of cockamamie scheme to advance different subproject with different dependencies if this causing significant down-stream pain.

**Comment by notthatbreezy** [comment]
Thanks for the update - I think I understand the difficulties involved now around `circe`.

It seems like we'd be able to at least upgrade `fs2`, `cats`, and `cats-effect` then without too much fanfare at least since those libraries are still publishing for scala 2.11.

We might be able to avoid compatibility issues downstream for `circe` if we ensure we're not using any `codec` from GT as we upgrade things or delay our own upgrade of `circe` -- that's more of our concern than yours, it's unclear how difficult doing either of these things will be at the moment.

**Comment by notthatbreezy** [comment]
Just realized that `circe` `0.11.1` depends on `cats 1.x` so that probably isn't a good idea to just upgrade those to libraries :man_facepalming: 

So this seems like something we'll have to live with if 2.11 is a requirement for EMR since Spark still published [artifacts](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/2.4.4) for 2.12 so it's kind of an Amazon thing at this point :( like you said.

**Comment by pomadchin** [comment]
@notthatbreezy yeah, that is how we support 2.12 / 2.11 crosspublish, and 2.12 would be a default build soon https://github.com/locationtech/geotrellis/pull/3132

**Comment by echeipesh** [comment]
this issue will be resolved with release of GT 3.2.0 sometime next sprint.
I'm a little fuzzy what bumping dependency versions means in terms of SemVer but feels more than a bug release so /shrug.
