### ISSUE TITLE
Provide AvroRecordCodec implementations for JTS geometry types

### ISSUE THREAD

**Issue by CloudNiner** [locationtech/geotrellis#3159]
We have a few codecs in https://github.com/locationtech/geotrellis/tree/master/store/src/main/scala/geotrellis/store/avro/codecs for things like Extent, but not for the geometry types.

Something like https://github.com/sksamuel/avro4s might make it easier to write and maintain these?

**Comment by pomadchin** [comment]
@CloudNiner I think in our case `avro4s` will still require to write custom codecs manually https://github.com/sksamuel/avro4s#custom-type-mappings We have complex types and lot's of them are not case classes. Also mb it makes no sense to include into codecs smth we don't use explicitly in the library code? Anything else (like JTS types) is a user-defined code in my opinion, I see no ways how GeoTrellis can use it to persist layers.

But we could have some separate library with JTS Avro codecs / etc.

**Comment by pomadchin** [comment]
Btw this is a perfect taks for the `geotrellis-contrib`

**Comment by CloudNiner** [comment]
Ooo great point. Closing this and opened https://github.com/geotrellis/geotrellis-contrib/issues/241
