### ISSUE TITLE
GeometryCollection encoding issue

### ISSUE THREAD

**Issue by atararaksin** [locationtech/geotrellis#3167]
The following code
```
val p = Point(1, 1)
println(GeometryCollection(multiPoints = Seq(MultiPoint(p, p))).toGeoJson)
```
prints
```
{
  "type" : "GeometryCollection",
  "geometries" : [
    {"type" : "MultiPoint", "coordinates" : [[1.0, 1.0], [1.0, 1.0]]},
    {"type" : "GeometryCollection", "geometries" : [
      {"type" : "Point", "coordinates" : [1.0, 1.0]},
      {"type" : "Point", "coordinates" : [1.0, 1.0]}
    ]}
  ]
}
```
The same duplication happens with `MultiPolygons` and `MultiLines` when nested into `GeometryCollection`. It appears that this is because a `MultiPoint` IS a `GeometryCollection`, so the `Encoder` retrieves it two times - first by `getAll[MultiPoint]`, then by `getAll[GeometryCollection]`.

**Comment by atararaksin** [comment]
Besides serialization, some other operations are also affected by this:
```
scala> val p = Point(1, 1)
p: org.locationtech.jts.geom.Point = POINT (1 1)

scala> val gc = GeometryCollection(multiPoints = Seq(MultiPoint(p, p)))
gc: org.locationtech.jts.geom.GeometryCollection = GEOMETRYCOLLECTION (MULTIPOINT ((1 1), (1 1)))

scala> gc.reproject(WebMercator, LatLng)
res0: org.locationtech.jts.geom.GeometryCollection = GEOMETRYCOLLECTION (MULTIPOINT ((0.0000089831528412 0.000008983152841), (0.0000089831528412 0.000008983152841)), GEOMETRYCOLLECTION (POINT (0.0000089831528412 0.000008983152841), POINT (0.0000089831528412 0.000008983152841)))
```
 Though, on the other hand, `MultiPoint extends GeometryCollection`, and from this point of view `.getAll[GeometryCollection]()` behaves correctly, the caller might expect to get all subclasses of `GeometryCollection`.

**Comment by pomadchin** [comment]
@atararaksin I moved your last comment into a separate issue: https://github.com/locationtech/geotrellis/issues/3289
