### ISSUE TITLE
The Reading GeoTiffs tutorial use files that don't exist

### ISSUE THREAD

**Issue by RyanHeins** [locationtech/geotrellis#3178]
I'm trying to follow the tutorial and noticed it has me read the file `path/to/geotrellis/raster/data/geotiff-test-files/lzw_int32.tif`, but there is no file of that filename in that directory of the repo. It also refers to a non-existent multi-band file `path/to/raster/data/geotiff-test-files/3bands/3bands-striped-band.tif`.

**Comment by pomadchin** [comment]
Hey @RyanHeins if you'll run geotrellis tests at least one time it will unpack [geotiff-test-files.zip](https://github.com/locationtech/geotrellis/blob/master/raster/data/geotiff-test-files.zip) that contains these files. 

You can also download this archive, unpack it and find these files.

**Comment by CloudNiner** [comment]
Accounted for in #3306
