### ISSUE TITLE
stitch method can't be called by the object of TileLayerRDD[SpatialKey]

### ISSUE THREAD

**Issue by zxhcodes** [locationtech/geotrellis#3185]
val resultRdd = ContextRDD(tileRdd, metadata)
resultRDD.stitch    //error in version 3.0.0, but is ok in 1.x

the error:

> value stitch is not a member of geotrellis.spark.TileLayerRDD[geotrellis.layer.SpatialKey]

**Comment by pomadchin** [comment]
hey @zxhcodes check out your imports:

```scala
import geotrellis.spark._
import geotrellis.raster._
import geotrellis.layer._

import org.apache.spark.rdd.RDD

val rdd: RDD[(SpatialKey, Tile)] = ???
val md: TileLayerMetadata[SpatialKey] = ???
val contextRDD = ContextRDD(rdd, md) // TileLayerRDD[SpatialKey]
val result = rdd.stitch
```

**Comment by zxhcodes** [comment]
> hey @zxhcodes, check out your imports:
> 
> ```scala
> import geotrellis.spark._
> import geotrellis.raster._
> import geotrellis.layer._
> 
> import org.apache.spark.rdd.RDD
> 
> val rdd: RDD[(SpatialKey, Tile)] = ???
> val md: TileLayerMetadata[SpatialKey] = ???
> val contextRDD = ContextRDD(rdd, md) // TileLayerRDD[SpatialKey]
> val result = rdd.stitch
> ```
> 
> Implicits are stored [here](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/stitch/Implicits.scala)

Thank you !!! 
The error disappears after add the import:

> import geotrellis.spark._
