### ISSUE TITLE
An outdated how to get started tutorial

### ISSUE THREAD

**Issue by doug-aero** [locationtech/geotrellis#3190]
Is there an up-to-date Docker container image for geotrellis?

**Comment by pomadchin** [comment]
Hey @doug-aero what do you need a docker container for? To run GeoTrellis you only need JDK set on your machine, so you can take an openjdk:8 container and run your experiments inside it.

**Comment by doug-aero** [comment]
I have run into issues when trying to build the project. These likely stem from my unfamiliarity with scala/java, a proxy issue, or both. I was thinking a prebuilt docker container might solve these problems.

For example, when running ./sbt as described in https://geotrellis.readthedocs.io/en/latest/tutorials/quickstart.html, I get a lot of errors and warnings:

```
./sbt: line 201: [[: .: syntax error: operand expected (error token is ".")
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /dev/shm/scala_test/geotrellis-sbt-template/project
[info] Updating {file:/dev/shm/scala_test/geotrellis-sbt-template/project/}geotrellis-sbt-template-build...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.5: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.5 {compile=[default(compile)]}:: 
[warn] 	Index 1 out of bounds for length 1
[warn] 	Index 1 out of bounds for length 1
[warn] 	Index 1 out of bounds for length 1
[warn] 	:: net.virtual-void#sbt-dependency-graph;0.9.0: Resolution failed several times for dependency: net.virtual-void#sbt-dependency-graph;0.9.0 {compile=[default(compile)]}:: 
[warn] 	Index 1 out of bounds for length 1
```
...
And much more.

**Comment by pomadchin** [comment]
ah this template us outdated, you can manually create an sbt project and add all the dependencies you need into it.

**Comment by jpolchlo** [comment]
@pomadchin: The purpose of the SBT template repo is to give people new to scala a head start.  Even years in to being a GT user, I dread writing a new build.sbt.  It's an awful task, and we shouldn't foist it on someone if we can help it.

I also noticed just yesterday that there are significant compatibility issues with many of our usual SBT plugins and SBT 1.3.x.  Not sure if that is contributing to the problems logged above.

But, @doug-aero, to @pomadchin's point, the Docker container won't help you if your build.sbt isn't correct.  Note that the current master of that SBT template repo is a few GT versions behind, so I made a [branch](https://github.com/jpolchlo/geotrellis-sbt-template/tree/update/gt-3.2) on a forked repo that you can check out.  It works for me.  I didn't update the SBT version as high as it can go, though, since I was having plugin trouble.  Please check it out and try again!

**Comment by pomadchin** [comment]
@jpolchlo moved it into documentation (see the label) so this issue is not dropped; we definitely need to update our templates and docs how to get started.

**Comment by pomadchin** [comment]
hey @doug-aero I changed the title of this issue a little bit, we'll let you know when it would be done;+ follow @jpolchlo recommendations as well.

You're also welcome to join our [gitter channel](https://gitter.im/geotrellis/geotrellis) with any questions.

**Comment by doug-aero** [comment]
@jpolchlo Just to be fully clear, here is what I ran just now: 
```
git clone https://github.com/jpolchlo/geotrellis-sbt-template.git
cd geotrellis-sbt-template/
git checkout origin/update/gt-3.2
./sbt test
```
It seems to have resulted in the same errors and warnings.

**Comment by pomadchin** [comment]
hm @doug-aero  are you sure that you have access to [maven central](https://repo1.maven.org/maven2/org/locationtech/geotrellis/geotrellis-raster_2.12/)?

**Comment by jpolchlo** [comment]
@doug-aero I ran a check in docker:
```bash
docker run --rm -it -v $(pwd)/geotrellis-sbt-template:/work openjdk:8 bash

cd /work
rm -rf target
./sbt
```

Running `console` from that SBT session worked just fine.  This should have taken care of any artifacts based on the Ivy cache hiding a resolution problem.

I'm trying to think through where we might be missing something, but for the moment, I'm coming up dry.

**Comment by doug-aero** [comment]
By running a slightly modified, `docker run --network=host --rm -it -v $(pwd)/geotrellis-sbt-template:/work openjdk:8 bash` I get this:

```
Downloading sbt launcher for 1.0.3:
  From  http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.0.3/sbt-launch.jar
    To  /root/.sbt/launchers/1.0.3/sbt-launch.jar
Getting org.scala-sbt sbt 1.0.3 ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.3/sbt-1.0.3.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;1.0.3!sbt.jar (16ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.4!scala-library.jar (147ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.0.3/main_2.12-1.0.3.jar ...
	[SUCCESSFUL ] org.scala-sbt#main_2.12;1.0.3!main_2.12.jar (236ms)
```
...
```
These apparent successes are followed by:
:: problems summary ::
:::: WARNINGS
	Your proxy requires authentication.

	Your proxy requires authentication.

	Your proxy requires authentication.

	Your proxy requires authentication.

```
And then follow the same errors and warnings seen before. It looks like these problems are indeed on my end with the proxy.

**Comment by pomadchin** [comment]
Yes, it looks like you have issues using your proxy. You can't download aything because of having connection troubles.

**Comment by CloudNiner** [comment]
Superseded by #3305
