### ISSUE TITLE
Vector MethodExtensions as value class

### ISSUE THREAD

**Issue by f-loris** [locationtech/geotrellis#3204]
Since version 3 the JTS geometries are not wrapped anymore but instead extended through "extension methods" . When using such an extension it leads to an allocation of the implicit class since it is no value class.
For example: https://github.com/locationtech/geotrellis/blob/3e59f26807fc9d3a2dbf47fe358a1f1dbd2205ae/vector/src/main/scala/geotrellis/vector/methods/Implicits.scala#L8

Shouldn't be `AnyVal` considered to save unnecessary allocations? I think it can lead to notable performance improvements when using the extensions heavily. I know this might need some re-design of the implicits, but it might be worth the effort. What do you guys think about that?

**Comment by pomadchin** [comment]
Hey @f-loris, it definitely _could_, but to do that you need to reorganize implicits; value classes can’t be defined in traits.

And also I don’t think it matters too much in this case, its objects are already heavy so probably it would not make any real difference anywhere (mb some benchmarks are necessary here).

**Comment by f-loris** [comment]
Thanks for your response @pomadchin ! Indeed, reorganizing might not be the effort worth compared to the gain. I just wanted to raise awareness for this topic. 
As you mentioned, we we'll need some benchmarks to see if the impact is significant. At least for simple getters the overhead would be measurable: https://github.com/locationtech/geotrellis/blob/3e59f26807fc9d3a2dbf47fe358a1f1dbd2205ae/vector/src/main/scala/geotrellis/vector/methods/PointMethods.scala#L7

I'll close it for now and if I find time for some benchmarks I'll post them here.

**Comment by pomadchin** [comment]
@f-loris just for the particular case you mentioned, about the `PointMethods` overloads - there is no way to make it work 'better'. 

`Point` is a type alias for the `org.locationtech.jts.geom.Point`, its `getX` and `getY` implenetations are the same as we have [reference to the Point.java code](https://github.com/locationtech/jts/blob/jts-1.16.1/modules/core/src/main/java/org/locationtech/jts/geom/Point.java#L100-L116).

Thank you so much for asking! Benchmarks coverage would be indeed very convenient to track down possible regressions; I expect that in some places we're loosing performance on extra allocations.
