### ISSUE TITLE
Deploy master branch docs to RTD

### ISSUE THREAD

**Issue by jcallin** [locationtech/geotrellis#3205]
I noticed the `geotrellis-slick` module is now included in `geotrellis-contrib` and the documentation does not reflect this https://geotrellis.readthedocs.io/en/latest/guide/module-hierarchy.html

I assume other docs are out of date as well and the new docs just need to be deployed

**Comment by pomadchin** [comment]
Hi @jcallin, it is a shame, but all the documentation is pretty much out of date. We totally forgot to remove the slick package from the docs as well (but we wanted at least to do that).

**Comment by CloudNiner** [comment]
As @pomadchin alluded to, we updated the docs on master branch but never published them. I updated the issue title to reflect the task that needs to be done, which is to publish our current docs on `master` to the live docs site.
