### ISSUE TITLE
RasterSources resolutions should be consistent across implementations

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3210]
At this point `GeoTiffRasterSource.resolutions` and `GeoTrellisRasterSource.resolutions` functions return the base overview `cellSize` as well. 

The task is to double check that the behavior across all the RasterSources implementation is the same and returns only _overviews_ resolutions / contain the base resolution as well.

UPD: resolutions is an external API, and [you can find its usage in the `geotrellis-server`](https://github.com/geotrellis/geotrellis-server/search?q=resolutions&unscoped_q=resolutions) where resolutions are used to walks through all the supported resolutions by the overview, and in this usecase it is really convenient to have the base reslution in this list.

**Comment by echeipesh** [comment]
What triggered this issue, do we have an example where they're not right now?

**Comment by pomadchin** [comment]
@echeipesh [a review](https://github.com/geotrellis/geotrellis-pointcloud/pull/61) by @jpolchlo triggered it. So I decided to check all the RasterSources behavior, and both GeoTiffRasterSource and GeoTrellisRasterSource contain the base cellSize as well. 

I guess the question here is that - do we need to add it into the `GDALRasterSource.resolutions` as well? Or do we need to change all RasterSources to contain only _overviews_ resolutions.

**Comment by pomadchin** [comment]
I guess for now - `resolutions` can really contain the base resolution. Originally (in the beginning of the RasterSources), it was called differently and indeed meant overvews resolutions.

**Comment by moradology** [comment]
I'm very much for including base among the resolutions

**Comment by echeipesh** [comment]
My mental model is that `RasterSource.resolutions` contains the base resolution. 

The prime use case is that the user is using this information to decide at which resolution its reasonable to sample the source raster. Its always reasonable to sample the raster at base resolution, so that information would have to remain there.

Counterexample is if a user resampled a raster source to some cell size, looking at `resolutions` list should indicate that its safe to go back to original resolution, otherwise it becomes "lost" as an option.

**Comment by pomadchin** [comment]
A short summary

1. #3211 addresses the similarity in behavior, in the sense of adding the base cellType into the resolutions list.

2. However, GDAL upsamples cellSizes even if it was a resample and not only in reprojection cases.
3. We already have `RasterSources` resolution behavior:

* [GDALRasterSource with upsampling cellSizes in the resample case](https://github.com/locationtech/geotrellis/blob/master/gdal/src/test/scala/geotrellis/raster/gdal/GDALRasterSourceSpec.scala#L64-L69)
* [GeoTiffRasterSource does not upsample cellSizes in the resample case](https://github.com/locationtech/geotrellis/blob/master/raster/src/test/scala/geotrellis/raster/geotiff/GeoTiffRasterSourceSpec.scala#L75-L77)
* [GeoTrellisRasterSource does not upsample cellSizes in the resample case](https://github.com/locationtech/geotrellis/pull/3211/files#diff-28fce00d2a6d9757847488e95fe46c87R104-R109)

The conclusion that I have now is that adding base extent in the resolutions list is required and only GDAL bahaves slightly different during the resample operation.

I'm ok with it now. It looks like GDAL knows how to work with these resampled cellSizes on reads and does it under the hood.
