### ISSUE TITLE
Nearest Neighbor Resampling

### ISSUE THREAD

**Issue by ricardobarroslourenco** [locationtech/geotrellis#3234]
I was looking into the [Nearest Neighbor Resampling class](https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/raster/src/main/scala/geotrellis/raster/resample/NearestNeighborResample.scala) and I got a doubt on what the `tile` and `extent` parameters mean in this context.

**Comment by pomadchin** [comment]
Hi @ricardobarroslourenco! 

`tile` is the tile that is the source of the resample and `extent` is the extent of this (source) `tile`.

**Comment by ricardobarroslourenco** [comment]
Thanks for the prompt answer @pomadchin ! So the aspect of nearest neighbor would be a 1-NN and not a k-NN (when applying the resampling)?

**Comment by pomadchin** [comment]
@ricardobarroslourenco yes; it is a resample method; there are a bunch of them: nearest neighbor, bilinear, bicubic, etc. 

KNN is a different operation, and I believe we have only a spark version of it: https://github.com/locationtech/geotrellis/blob/1d1561cf8e79dbd738902a18716619dd58aa9f6a/spark/src/main/scala/geotrellis/spark/knn/KNearestRDD.scala

**Comment by ricardobarroslourenco** [comment]
Thanks for the clarification. I was curious if the method was able to consider variability on the number of neighbors being considered, as a manner of smoothing the interpolation process.
