### ISSUE TITLE
WebMercator is reported as deprecated EPSG:3785 instead of  EPSG:3857 in metadata

### ISSUE THREAD

**Issue by jdenisgiguere** [locationtech/geotrellis#3247]
Current situation
===

When I reproject a layer into a `ZoomLayoutScheme` using `geotrellis.proj4.WebMercator` as CRS, the  json file of metadata of the resulting layer will contain this srs definition:

```json
"crs":"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs "
```

If I query the `AttributeStore` metadata for `crs.epsgCode` it will return: 3785.
EPSG:3785 is a deprecated code for Web Mercator. 

In `geotrellis.proj4.WebMercator`, we explicitly expose `epsgCode` as 3857.

Expected situation
===

When looking at `metadata.crs.epsgCode` of a layer reprojected to `geotrellis.proj4.WebMercator` , I would expect the value to be 3857.

**Comment by pomadchin** [comment]
@jdenisgiguere it is a proj4j bug: https://github.com/locationtech/proj4j/issues/61
It is not a critical issue though.

**Comment by pomadchin** [comment]
Would be addressed here: https://github.com/locationtech/proj4j/pull/71

**Comment by pomadchin** [comment]
Closed via https://github.com/locationtech/geotrellis/pull/3294/files
