### ISSUE TITLE
GridExtent rounding issues

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3248]
In the `GridExtent` funtions we use floors, ceils and rounds pretty [inconsistently](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/GridExtent.scala#L33-L49). 

QGIS and GDAL use ceils and floors with some tolerance that helps to [handle corner cases better](https://github.com/qgis/QGIS/blob/607664c5a6b47c559ed39892e736322b64b3faa4/src/analysis/raster/qgsalignraster.cpp#L38).

This task is about doublecheking how we work with rounding floating numbers, and consider usage of the `ceilWithTolerance` as well (a long with the [floorWithTolerance](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/GridExtent.scala#L414) function we already use).

**Comment by jisantuc** [comment]
:wave: I put a test tif at `s3://geotrellis-test/3248/failing-withResolutions.tif`. You can reproduce the error with this ammonite script that mimics the [process for calculating a histogram](https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/common/src/main/scala/utils/CogUtils.scala#L51-L63) in Raster Foundry

```scala
import $ivy.`org.locationtech.geotrellis::geotrellis-raster:3.3.0`
import $ivy.`org.locationtech.geotrellis::geotrellis-s3:3.3.0`
import $ivy.`org.locationtech.geotrellis::geotrellis-vector:3.3.0`

import geotrellis.raster._
import geotrellis.vector._
import geotrellis.raster.geotiff._

def viableCellSizes(
        rs: RasterSource,
        baseCellSize: CellSize,
        sizes: List[CellSize],
        target: Long
    ): List[CellSize] = {
      val width = rs.cols
      val height = rs.rows

      val isGood: CellSize => Boolean = (cs: CellSize) => {
        val cellCount = width / (cs.width / baseCellSize.width) * (height / (cs.height / baseCellSize.height))
        println(s"Cell count for $cs: $cellCount")
        cellCount < target
      }

      sizes.filter(isGood)
    }

val rsSb = GeoTiffRasterSource("trl-transformed-cog.tif")
val viableSb = viableCellSizes(rsSb, rsSb.cellSize, rsSb.resolutions, 400000)

viableSb.headOption map { res => println(s"Single band 1: ${rsSb.gridExtent.withResolution(res)}") }
viableSb.lastOption map { res => println(s"Single band 2: ${rsSb.gridExtent.withResolution(res)}") }
```

**Comment by CloudNiner** [comment]
@jisantuc I downloaded the test tiff and copied your ammonite script and was able to reproduce the issue there using geotrellis 3.3.0.

I then loaded up master and created a new test case in GridExtentSpec:
```scala
it("should not crash in withResolution") {
      def viableCellSizes(rs: RasterSource,
                          baseCellSize: CellSize,
                          sizes: List[CellSize],
                          targetCellCount: Long): List[CellSize] = {
        val width = rs.cols
        val height = rs.rows

        val isGood: CellSize => Boolean = (cs: CellSize) => {
          val cellCount = width / (cs.width / baseCellSize.width) * (height / (cs.height / baseCellSize.height))
          println(s"Cell count for $cs: $cellCount")
          cellCount < targetCellCount
        }

        sizes.filter(isGood)
      }
      val path = baseGeoTiffPath("failing-withResolutions.tif")
      val rsSb = GeoTiffRasterSource(path)
      val viableSb = viableCellSizes(rsSb, rsSb.cellSize, rsSb.resolutions, 400000)
      viableSb.headOption map { res => println(s"Single band 1: ${rsSb.gridExtent.withResolution(res)}") }
      viableSb.headOption map { res => println(s"Single band 1: ${rsSb.gridExtent.withResolution(res)}") }
    }
```

And this passes:
![Screen Shot 2020-06-16 at 3 40 41 PM](https://user-images.githubusercontent.com/1818302/84820520-c70c4e00-afe7-11ea-8e62-90e0c6e1e283.png)

In the absence of further information, I'm going to guess that at least one of the fixes in @pomadchin's #3252 addressed this issue.

**Comment by pomadchin** [comment]
@CloudNiner are you sure about that? It fails for me on the master branch:

```scala
$ git reset --hard HEAD^
HEAD is now at dafceaf9b Fix issue with resource management in Jpeg compressed GeoTiffs (#3249)

scala> viableSb.lastOption map { res => println(s"Single band 2: ${rsSb.gridExtent.withResolution(res)}") }
java.lang.IllegalArgumentException: requirement failed: Extent(4114885.5876404666, -770072.0469938816, 4129027.727803043, -758864.1346488822) at CellSize(64.57598247751807,64.41328933907688) does not match 219x175
  at scala.Predef$.require(Predef.scala:281)
  at geotrellis.raster.GridExtent.<init>(GridExtent.scala:48)
  at geotrellis.raster.GridExtent.withResolution(GridExtent.scala:133)
  at geotrellis.raster.GridExtent.withResolution(GridExtent.scala:144)
  at geotrellis.raster.GridExtent.withResolution$mcJ$sp(GridExtent.scala:143)
  at .$anonfun$res1$1(<console>:38)
  at .$anonfun$res1$1$adapted(<console>:38)
  at scala.Option.map(Option.scala:230)
  ... 36 elided
```

**Comment by CloudNiner** [comment]
Whew. I can reproduce this now. Looks like I somehow ended up with an incorrect copy of the test case.

**Comment by CloudNiner** [comment]
@jisantuc The PR in #3250 should address this specific issue once merged, but here's some background on this issue in this PR comment: https://github.com/locationtech/geotrellis/pull/3250#discussion_r442838624 along with a discussion around how usage of `withResolution` can lead to unexpected results in new issue #3261. Not sure if this affects your code, but wanted to highlight it nonetheless.

**Comment by pomadchin** [comment]
Closed in https://github.com/locationtech/geotrellis/issues/3248 and the follow up discussions would be done here #3261
