### ISSUE TITLE
Review HttpRangeReader location

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3256]
This task is to review HttpRange reader, its location (the package location) and the library we use to implement it. 

In terms of https://github.com/locationtech/geotrellis/issues/3254 we moved out HttpRangeReader out of the `spark` package into the `store`, but mb there is a better place for it?

My original thought was `geotrellis.spark.store.http.util` => `geotrellis.store.http.utill` but it looks like we need to revisit this descision.

**Comment by echeipesh** [comment]
My vote is to get it as close to `geotrellis.raster` as possible so `GeoTiffRasterSouce` is able to read COGs from HTTP without bringing in the `store` package which is generally to do with the indexed layers.

**Comment by pomadchin** [comment]
@echeipesh hm, where should the `FileRangeReader` live in this case?

**Comment by pomadchin** [comment]
And also the `HdfsRangeReader`

**Comment by CloudNiner** [comment]
There was an argument to move this into `geotrellis.util` which "might be weird because it uses `scalaj`". 

There was also an argument for `geotrellis.raster` because this is really a `GeotiffHttpRangeReader` so its real utility is coupled to geotiffs defined in `geotrellis.raster`.
