### ISSUE TITLE
Geotrellis converts tif file format

### ISSUE THREAD

**Issue by wenjunzhangp** [locationtech/geotrellis#3277]
Hello, I have a problem now. I try to convert ordinary tif into `cog` format. How to do it?
How does `geotrellis` convert common format tif files into `cog` format? Is there a ready-made `api` to do it?
Thanks for answering my doubts~

**Comment by pomadchin** [comment]
This question was also asked in our gitter channel: https://gitter.im/geotrellis/geotrellis?at=5f24203fa2be904990825cab

I'll copy it here: 

```scala
// imagine it is not a COG (i.e. some striped tiff with no overviews)
val path: String = ???
val tiff = GeoTiffRasterSource(path).tiff
// change the internal tiff segments structure
tiff
  .copy(options = tiff.options.copy(storageMethod = Tiled(256, 256))) // it can be 512x512 / smth else you would like to have
  // lets build some overviews
  .withOverviews(NearestNeighbor, List(2, 4, 8))
  // write it out
  .write("/tmp/out.tiff")
```

**Comment by wenjunzhangp** [comment]
Thank you very much for your help, thank you~~

**Comment by wenjunzhangp** [comment]
I tried to transfer a few `tif`, but all got consistent errors. The log is as follows:
```
Exception in thread "main" java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\data\test\meta\xxx.tif
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at geotrellis.contrib.vlm.package$.getByteReader(package.scala:34)
	at geotrellis.contrib.vlm.geotiff.GeoTiffRasterSource.tiff$lzycompute(GeoTiffRasterSource.scala:35)
	at geotrellis.contrib.vlm.geotiff.GeoTiffRasterSource.tiff(GeoTiffRasterSource.scala:34)
	at Test$.main(Test.scala:12)
	at Test.main(Test.scala)
```
I am running in a `windows` environment, is there a problem with my `tif`?

**Comment by pomadchin** [comment]
@wenjunzhangp yep that can be the windows thing; for the quick check that it works, you can try it under WSL.

Sorry, we don't have a well tested Windows support. I believe we have some set of windows related issues which are still unsolved.

**Comment by wenjunzhangp** [comment]
@pomadchin thanks,okay.I will try it on the linux platform later~

**Comment by wenjunzhangp** [comment]
```
 .copy(options = tiff.options.copy(storageMethod = Tiled(256, 256)))
 .withOverviews(NearestNeighbor, List(2, 4, 8))
```
Hello, I have another question about these parameters, I don’t know what they mean.
Q1:Tiled Does the parameter in the Tiled method refer to the tile size?
Q2:What does NearestNeighbor mean and what does the following List(2,4,8) represent?
Thanks for answering my doubts~

**Comment by pomadchin** [comment]
@wenjunzhangp so what are COGs: TIFFs that are: 

1. Tiled (segments of tiffs are square chips so it would be possible to perform efficient range reads); segments should be small enough (256x256 or 512x512)
2. Contain internal overviews

Get familiar with it here:

* https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF
* https://gdal.org/drivers/raster/cog.html
* https://www.cogeo.org/

The method `.withOverviews` builds these overviews; `NearestNeighbor` is the resample method used to produce the output . The `List(2, 4, 8)` is the list of decimations (how much smaller in cols / rows the overviews should be). 

In this code example the result would be a COG tiled 256x256 with 3 overviews that are 2, 4 and 8 times smaller than the original raster.

**Comment by wenjunzhangp** [comment]
Thank you very much for your patience reply, I think it helped me a lot, thank you.
I have read the link you recommended, I am familiar with this, and understand a bit.
