### ISSUE TITLE
GDALRasterSource gives segmentation fault when reading rasters with NBITS=1

### ISSUE THREAD

**Issue by jterry64** [locationtech/geotrellis#3300]
## Describe the bug

When trying to read rasters using GDALRasterSource that have nbits=1 and CCITTFAX4 compression GDAL options, I get the following error:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5618facf8a, pid=13276, tid=0x00007f55e9371700
#
# JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x9af8a]  __memcpy_sse2_unaligned_erms+0x1fa
```

If I change to the same raster but without any special GDAL options, it works fine. 

## To Reproduce

Here's a sample of a raster file that causes the issue: [is__umd_tree_cover_gain_20N_100E.tif.zip](https://github.com/locationtech/geotrellis/files/5459888/is__umd_tree_cover_gain_20N_100E.tif.zip)

This how I'm using the GDALRasterSource and LayoutTileSource in my code:

https://github.com/wri/gfw_forest_loss_geotrellis/blob/3947899c4b985e9fad4f57bb7cf18bfc8fb279af/src/main/scala/org/globalforestwatch/layers/Layer.scala#L166

https://github.com/wri/gfw_forest_loss_geotrellis/blob/3947899c4b985e9fad4f57bb7cf18bfc8fb279af/src/main/scala/org/globalforestwatch/layers/Layer.scala#L314

I'm reading raster tiles from S3.

## Expected behavior

No segmentation fault.

## Environment

- Java version: 8
- Scala version: 2.12.6
- GeoTrellis version: 3.5.0
- GDAL version: 3.1.2

## Additional context

Discussed with @pomadchin in gitter for context

**Comment by jterry64** [comment]
Hey @pomadchin, just checking in since it's been a few months - is there a plan to fix this at some point in the future?

**Comment by pomadchin** [comment]
Hi @jterry64 unfortunately we didn't have a chance to look into it. I can confirm that this bug is not present in Py bindings though, so that should be smth very specific to our bindings.

**Comment by pomadchin** [comment]
Hey @jterry64, could you verify that https://github.com/locationtech/geotrellis/pull/3368 solves your issue? 

Be careful with its testing though. The demo file size is only `8.4M`, however, it is a `40000 x 40000` raster. Meaning that it would require a `40000 x 40000` `Byte` array allocation in JVM.

**Comment by pomadchin** [comment]
This issue was closed, but feel free to reopen if it is still an issue. Shortly the new [3.5.3-SNAPSHOT release would be available in our eclipse snapshots repo](https://repo.eclipse.org/content/groups/snapshots/org/locationtech/geotrellis/geotrellis-gdal_2.12/3.5.3-SNAPSHOT/). That would simplify testing!
