### ISSUE TITLE
JDK 11 CI Builds

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3301]
Java 11 is the current LTS and accroding to https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html is very well supported by Scala. 

Even though all major builds still should remain built against Java 8, we need to consider adding the Java 11 support builds, at least to remain up to date. The current master can't be compiled with Java 11+.

Requires upgrade up to Hadoop 3.3 and all deps that depend on lower hadoop versions, see https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Java+Versions

**Comment by pomadchin** [comment]
This issue turned out to be a bit more complicated, since not only the codebase changes are required but also some libs deps updates.

**Comment by pomadchin** [comment]
We support JDK11, see https://github.com/locationtech/geotrellis/pull/3383

Let's reframe this issue into adding the CI that would run tests with JDK 11.

**Comment by pomadchin** [comment]
I think we can start seriously thinking about dropping JDK8 builds, EMR supports JDK 11 already (https://docs.aws.amazon.com/emr/latest/ReleaseGuide/configuring-java8.html (guide to configure JDKs) + https://stackoverflow.com/questions/70886684/how-to-use-java-runtime-11-in-emr-cluster-aws)

**Comment by metasim** [comment]
@pomadchin Thanks for the head's up. It's been a long time coming, and definitely needed. Not sure when I'll get to an RF build tho. :/
