### ISSUE TITLE
storageMethod in GeoTiffOptions for SingleBandTiff writing doesn't work

### ISSUE THREAD

**Issue by tosen1990** [locationtech/geotrellis#3335]
## Describe the bug

storageMethod in GeoTiffOptions for SingleBandGeoTiff writing doesn't work.

Attached [TIFF](https://dsafsadfafdsa.s3.ap-northeast-2.amazonaws.com/OUTPUT.tif)
When writing out a singleBandTiff using `GeoTiffOptions`  `storageMethod` couldn't generate a will tiled Tiff,still a striped one. While it works well for MultibandGeoTiff.
## To Reproduce

Provide as able:

- Steps to reproduce the behavior
- Code example
`MultibandGeoTiff(MultibandTile(tile_ndvi), extent, crs,
      GeoTiffOptions.DEFAULT.copy(
        storageMethod = Tiled(256, 256) 
        compression = Deflate 
      )).write("xx")`.   // generate a well tiled tif

`
  SinglebandGeoTiff(tile_ndvi, extent, crs,
      mtb_tiff.tags,
      GeoTiffOptions.DEFAULT.copy(
        storageMethod = Tiled(256, 256),
        compression = Deflate
      )).write("xx).  //still write out a striped tif
`
- Inputs
- Actual output
- Expected output

## Environment

- Java version:1.8
- Scala version:2.11.12
- GeoTrellis version: 3.3.1

**Comment by moradology** [comment]
This appears to have either been fixed or else to not be a bug as of my last testing - do you happen to have a tif that has this issue or some code which can replicate a tiff that won't respect its storage method argument? I'll be adding a test that verifies the current behavior later today but if there are further clues for us to use in searching for the issue, please feel free to share them!
