### ISSUE TITLE
Consider releasing a subset of packages that don't depend on Spark against 2.13

### ISSUE THREAD

**Issue by philvarner** [locationtech/geotrellis#3358]
## Is your feature request related to a problem? Please describe.

Spark 2.x and 3.1.x only support Scala 2.11 and 2.12
Spark 3.2 (unreleased) will only support Scala 2.12 and 2.13

This situation couples the Spark 3 and Scala 2.13 upgrades. However, not all geotrellis packages depend on Spark, and could be published independently.

Packages that don't depend on Spark (accumulo, cassandra, gdal, geotools, hbase, layer, macros, mdoc, proj4, raster, s3, shapefile, store, util, vector, vectortile) will compile under Scala 2.11, 2.12, and 2.13 (pending a few minor fixes). There are other projects, such as stac4s, that only depend on these non-Spark components, and I've also used them on internal projects. The limitation here is that since geotrellis only supports 2.12, great libraries like stac4s can't be integrated into projects that already use 2.13 without down-versioning the project. If the non-Spark libraries were released for 2.13, stac4s could cross-compile for it, and be more available to be used by more projects.

## Describe the solution you'd like

Packages that don't depend on Spark to be cross-compiled and released for 2.13. 

It may even make sense to split the geotrellis build into two separate repos -- one with the non-Spark components that can move "ahead" more cleanly, and another with the Spark components that depends on those non-Spark versions. Obviously this would be a big move, but it's something to think about.

## Describe alternatives you've considered

1. down-versioning 2.13 projects that want to use geotrellis or stac4s to 2.12
2. building and publishing 2.13 compiled geotrellis and stac4s to a private repo
3. Copying geotrellis or stac4s code into the 2.13 project

## Additional context

none

**Comment by philvarner** [comment]
https://github.com/locationtech/geotrellis/pull/3363 does just this, by setting cross-compile for each package that's spark only to be only 11 & 12. 

The PR is a bit messy right now b/c it includes changes that are in other PRs, but it's actually a pretty small change only to the build.  

The only thing that's broken right now is that mdoc fails for 2.13 b/c it relies on some spark pkgs, but I think this could be resolved pretty easily by only building mdoc against the appropriate modules for that scala version.

**Comment by pomadchin** [comment]
Hey @philvarner we talked through all the related covnersation with the team, and I think that it is a very timely [3.2.0-SNAPSHOT release for Scala 2.13](https://github.com/locationtech/geotrellis/issues/2893#issuecomment-801574621).

I think a fairly conservative approach to decrease the chaos level by all these changes could be the following:

1. Drop Scala 2.11 #3259
2. Upgrade up to Spark 3 #3218 (at least up to 3.0.1 (https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-6x.html)
3. Experiment with Scala 2.13 / 2.12 cross publish with spark (3.0.1 (for Scala 2.12) and 3.2.0-SNAPSHOT (for Scala 2.13))

I am not very excited by partial packages publication but that can be _fine_ (if 3. for some reason would not be possible to implement) but as snapshot versions only. 

A slight comment about #3363 - there is no CI set for 2.13 packages.

**Comment by philvarner** [comment]
That sounds like a good plan. 

I'll add that I think that anyone who really wants geotrellis non-Spark packages on 2.13 can build and publish privately. That might require them to apply a handful of build.sbt modifications, but it's way better than also needing to apply the tens of changes in my recent PRs.

**Comment by pomadchin** [comment]
https://github.com/locationtech/geotrellis/pull/3294 cc @philvarner @metasim
