### ISSUE TITLE
How geotrellis converts tif 16bit to 8bit?

### ISSUE THREAD

**Issue by wenjunzhangp** [locationtech/geotrellis#3367]
In geotrellis, how to convert a tif file from 16bit to 8bit.

Looking forward to your reply, thank you very much.

**Comment by pomadchin** [comment]
Hi @wenjunzhangp I posted the answer to that in the gitter channel [here](https://gitter.im/geotrellis/geotrellis?at=605b36e1a7dfe1372ef49f0f).

I'll put the same message in this post as well just in case some one would have a very similar one.

So the procedure you need is the conversion into the `ByteCellType`:

```scala
def to8bit(tiff: GeoTiff[Tile], overviews: List[GeoTiff[Tile]] = Nil): SinglebandGeoTiff =
  SinglebandGeoTiff(
    tiff.tile.convert(ByteCellType), 
    tiff.extent, 
    tiff.crs, 
    tiff.tags, 
    tiff.options, 
    overviews
)

val tiff: SinglebandGeoTiff = ???

// converts tiff and all its overviews
to8bit(tiff, tiff.overviews.map(to8bit(_)))
```

It won’t perform any rescaling though, if you want rescaling you can modify the `to8bit` function:

```scala
def to8bit(tiff: GeoTiff[Tile], overviews: List[GeoTiff[Tile]] = Nil): SinglebandGeoTiff =
  SinglebandGeoTiff(
    tiff.tile.rescale(0, 255).convert(ByteCellType), 
    tiff.extent, 
    tiff.crs, 
    tiff.tags, 
    tiff.options, 
    overviews
)
```

I'll close this issue, but feel free to reopen it / continue our conversation in the gitter channel!
