### ISSUE TITLE
GeoTools 27.x upgrade

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3470]
I noticed a regression while doing the https://github.com/locationtech/geotrellis/pull/3389 task, I was able to locate the version change that breaks geotools tests: https://github.com/geotools/geotools/compare/25.4...25.5

The reason is a TIFF with -inf nodata values. it requires more investigations. It could happen due to one of the underlying geotools libraries upgrade i.e. `jai-ext`; see the gitter thread: https://gitter.im/geotools/geotools?at=62c9fdcc76cd751a2fea9b49

**Comment by pomadchin** [comment]
^ https://github.com/geotools/geotools/pull/3992

**Comment by pomadchin** [comment]
Apparently, the fix that is in the main geotools branch just never got released.

**Comment by jodygarnett** [comment]
Please check if you can update to GeoTools 30.x series as outlined above :)

**Comment by pomadchin** [comment]
Supreseded via https://github.com/locationtech/geotrellis/issues/3515
