### ISSUE TITLE
There seems to be a bug in crs

### ISSUE THREAD

**Issue by yang162132** [locationtech/geotrellis#3501]
![image](https://user-images.githubusercontent.com/71556279/220570482-9b88e00e-654f-4f42-b45a-03d9af8907e5.png)
I create a gt catalog  for tiff with crs(EPSG:4490), but when I read it by GeoTrellisRasterSource,it seem in crs(EPSG:4019)
<img width="544" alt="4823427410e71aa4b3e65ff38f45a1c" src="https://user-images.githubusercontent.com/71556279/220571212-0d621b53-d14d-4de3-a1ed-585ab4f11b9a.png">

**Comment by yang162132** [comment]
I Guess by the metada.json only save proj4 for crs 
<img width="377" alt="a1ef3ab20f55defa6444341c3836b1f" src="https://user-images.githubusercontent.com/71556279/220571684-e395439c-9144-4f94-91c2-04952eb924e3.png">
EPSG:4019 and EPSG:4490 hava the same proj.4 string

**Comment by pomadchin** [comment]
Hello @yang162132, unfortunately it is not really a bug, but a _feature_. There is not much we can do when rely on proj4 strings. The right solution is most likely to use WKT2 CRS representation, but that's a significant separate chunk of work.

**Comment by yang162132** [comment]
> 你好@yang162132，不幸的是，它并不是真正的错误，而是一个_功能_。当依赖 proj4 字符串时，我们无能为力。正确的解决方案最有可能使用 WKT2 CRS 表示，但这是一项重要的独立工作。
By the way, when I ditched EPSG:4490 and switched to EPSG:4326, another problem occurred， Imatadate.json "extent":{"xmin":104.26474802744501,"ymin":35.21886419452063,"xmax":107.71963960409457,"ymax":39.401297179680384} and   "bounds":{"minKey":{"col":808,"row":287},"maxKey":{"col":818,"row":311}}}
![image](https://user-images.githubusercontent.com/71556279/220814912-5e6dfc7b-fc76-465e-abc6-067836eaf4ad.png)
![image](https://user-images.githubusercontent.com/71556279/220814946-153114fc-8c6f-469b-9308-f5d8354a6733.png)
The extents and bounds doesn't seem to conform

**Comment by pomadchin** [comment]
Hey @yang162132, I don't think I was able to understand your message properly, but these two different projections may mean different transformations. Unfortunately due to their proj4 string representation and the fact GT relies on it makes it impossible to differentiate between projections for the reader.

**Comment by yang162132** [comment]
@pomadchin  
I don't mean that, I have given up using EPSG:4490, just press the normal WGS84, but the position of the TMS image is still abnormal

**Comment by pomadchin** [comment]
@yang162132 could you make a separate issue with a more detailed descirption? 

The input, transformation, and the expected vs actual results?

**Comment by yang162132** [comment]
(104.26474802744501,35.21886419452063)

**Comment by yang162132** [comment]
![image](https://user-images.githubusercontent.com/71556279/220827842-7314ded1-4da2-4315-a927-ef9c991960bf.png)

The metedata.json for the catalog with crs 3857 and 4326 is here.The key of 3857 is right ,but for EPSG:4326, it wrong, is there any configuration I am missing.
![image](https://user-images.githubusercontent.com/71556279/220827382-8bbd75c6-5204-47c5-9d20-e2f2b9e9172a.png)
![image](https://user-images.githubusercontent.com/71556279/220827730-6a49d1a3-96ed-4f1f-a4b6-5fbf0e5a2820.png)

**Comment by yang162132** [comment]
I probably found the cause of the problem, because the slicing rule of TMS requires a square, and the range of EPSG:4326 is [-180,90,180,-90], it seems to be forced into [-180,180,180,-180]
