### ISSUE TITLE
Upgrading to GeoTools 30.x series, refactor to org.geotools.api interfaces

### ISSUE THREAD

**Issue by jodygarnett** [locationtech/geotrellis#3515]
As part of https://github.com/geotools/geotools/wiki/Remove-OpenGIS we are contacting affected projects to coordinate upgrade to GeoTools 30.x series and refactoring the org.opengis package to org.geotools.api.

**Comment by pomadchin** [comment]
Thanks for bringing it up! Connected with https://github.com/locationtech/geotrellis/issues/3470

**Comment by jodygarnett** [comment]
For more information see https://geotoolsnews.blogspot.com/2023/07/construction-ahead-refactoring.html

**Comment by jodygarnett** [comment]
We had a really good sprint result and the GeoTools 30-SNAPSHOT jars are now ready for your evaluation.

Please see update instructions here: https://docs.geotools.org/latest/userguide/welcome/upgrade.html 

There is a massive ant script we put together to refactor source code; you may need to adapt this for your use : )

**Comment by pomadchin** [comment]
@jodygarnett thx for reminding about it, all our tests pass with the update up to 30.0-SNPASHOT (https://github.com/locationtech/geotrellis/pull/3521) 🔥 Looking forward to see the release!

**Comment by jodygarnett** [comment]
That is such a vote of confidence - thanks :)

**Comment by pomadchin** [comment]
Depends on https://github.com/locationtech/geotrellis/issues/3301

**Comment by pomadchin** [comment]
Blocked by https://github.com/locationtech/geotrellis/issues/3522

**Comment by jodygarnett** [comment]
The GeoTools 30-RC is now available from maven.

The [announcement](http://geotoolsnews.blogspot.com/2023/09/geotools-30-rc-released.html) provides an overview. 

Thank you so much for testing

**Comment by pomadchin** [comment]
@jodygarnett ✅ updated today, thx for keeping this thread up to date

**Comment by jodygarnett** [comment]
The release goes out today :)
