### ISSUE TITLE
Convert NODATA ByteConstantTile and ShortConstantCellType: unexpected result

### ISSUE THREAD

**Issue by bossie** [locationtech/geotrellis#3525]
## Describe the bug

A NODATA `ByteConstantTile` that is converted to its own `CellType`, is no longer NODATA.

## To Reproduce

```scala
import geotrellis.raster.{ByteConstantTile, byteNODATA}

val t = ByteConstantTile(byteNODATA, cols = 1, rows = 1)
assert(t.isNoDataTile)
assert(t.convert(t.cellType).isNoDataTile) // boom
```

## Expected behavior

Seeing as the `CellType` doesn't change, this should be a no-op and the tile should remain NODATA.

## Environment

- Java version: openjdk version "1.8.0_382"
- Scala version: 2.12.15
- GeoTrellis version: 3.6.0

**Comment by pomadchin** [comment]
Ok, there is a bug in the noData conversion. :+1: nice catch; wondering if any other cellTypes might be affected.

**Comment by moradology** [comment]
Looked into this a small amount yesterday and it appears to be related to `NoData` in particular, so I'd guess this can happen in other contexts. Going to see about addressing this today

**Comment by jdries** [comment]
@moradology  I did a quick PR, I can expand it a bit further if you believe this general direction is fine.
We'd like to solve this one as it's a fairly important issue for correctness.
