### ISSUE TITLE
Use Conda for GDAL dependencies

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3537]
I wonder if we could use GDAL installed via conda instead of prebuilt containers.

**Comment by moradology** [comment]
Personally not a fan of conda and I kind of like our containers. Given the maintenance burden of a largely unfunded OS project though, this might be sensible?

**Comment by pomadchin** [comment]
It is actually easier to maintain our images + actions services are not that convenient.

https://github.com/locationtech/geotrellis/blob/master/.github/docker/gdal/3.x/ubuntu/Dockerfile

We use official image as a base and add JDK. Properly configured LD_LIBRARY_PATH does the rest of it.
