### ISSUE TITLE
Add 'gridBounds' to Tile.

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#938]
I spent a minute tracking down a bug while coding where I said
`val tileGridBounds = GridBounds(0, 0, tile.cols, tile.rows)`
when it should have said
`val tileGridBounds = GridBounds(0, 0, tile.cols - 1, tile.rows - 1)`.

We should really just have a method so I can do
`val tileGridBounds = tile.gridBounds`
and be done with it.

**Comment by johanstenberg92** [comment]
Fixed #950.
